module.exports = {
// element-by-element specification: [clause, element, requirement]
spec: [
["4.1","Interface with substructure","Modules are set on bases constructed under P1 Civil Works. The tenderer shall issue setting-out drawings and a base tolerance specification not later than eight weeks before the first delivery. Level tolerance across any single base: ±5 mm. Plan position tolerance: ±10 mm. Relative level between adjacent bases supporting one module: ±3 mm. The tenderer shall inspect and accept the bases in writing before delivery; delivery to unaccepted bases is at the tenderer's risk."],
["4.2","Module frame and structure","Steel or timber framed volumetric modules, designed to BS EN 1990 and the relevant material Eurocode, for the loadings at Appendix 8. Design working life 25 years minimum notwithstanding the intended 38-month deployment, to permit relocation. All lifting points designed, certified and clearly marked; a lifting plan issued with each delivery."],
["4.3","External walls","Composite panel or framed construction achieving the U-value at 6.1. External finish: factory-applied coated steel or fibre cement, colour from the approved range at Appendix 5. Impact resistance to withstand normal site traffic adjacent to haul routes. All penetrations sealed and weathered; no site-applied sealant relied upon as the primary weather line."],
["4.4","Roof","Pitched or flat to falls not less than 1:80 after deflection. Single-ply membrane or profiled sheet, with a 20-year manufacturer's material warranty assigned to the client at handover. Rainwater goods sized to BS EN 12056-3 for the design rainfall at Appendix 8, discharging to the drainage provided under P1 at the termination points scheduled at 5.2."],
["4.5","Windows and external doors","As the room data sheets. All external doors: 44 mm, weather-sealed, with a threshold not exceeding 15 mm. Escape doors to open in the direction of escape and be openable without a key from the inside at all times, in accordance with the fire strategy issued by the client's fire engineer at Appendix 2."],
["4.6","Internal walls and partitions","Full height to the underside of the floor above, achieving the acoustic and fire performance scheduled at 6.2 and 6.3. No service penetration shall reduce the rated performance; all penetrations firestopped by a competent installer and recorded in the firestopping register required at 10.4."],
["4.7","Corridors and circulation","Minimum clear corridor width 1200 mm, and 1500 mm where required by the fire strategy or by BS 8300 for accessible routes. Wall protection to 1200 mm AFFL throughout, and corner protection at every change of direction. Floor finish continuous, slip resistance PTV ≥ 36 wet and dry."],
["4.8","Stairs","Where blocks are two storey: stairs to the fire strategy, minimum 1200 mm clear width between handrails, handrails both sides at 900–1000 mm, tactile and visual contrast to nosings. External stairs to have a slip resistance maintained when wet and a means of preventing ice accretion or a stated winter maintenance regime."],
["4.9","Internal finishes","As the room data sheets for rooms and ensuites. Circulation and amenity areas: wall finishes wipe-clean to 1200 mm minimum; floors slip resistant and welded. No carpet in any circulation or amenity space. All finishes to be maintainable with standard commercial cleaning products, and a schedule of approved products issued in the O&M manual."],
["4.10","Mechanical services — heating","Electric panel heating as scheduled, or an alternative proposed by the tenderer and priced separately as a departure. Central plant, where offered, to be located, acoustically treated and access-provisioned to 4.14. Controls to prevent a room being heated with the window open shall be offered as a priced option."],
["4.11","Mechanical services — water","Hot and cold water distribution from the central plant provided under this package. Design to CIBSE Guide G and the Water Supply (Water Fittings) Regulations. Dead legs minimised and recorded; every dead leg exceeding 3 pipe diameters to be scheduled in the O&M. Hot water stored at 60 °C minimum and distributed at 50 °C minimum at every outlet within one minute, with outlet temperature limited to 41 °C by TMV3 valves at every basin and shower."],
["4.12","Mechanical services — legionella","The tenderer shall prepare and hand over a written scheme of control to HSG274 Part 2 and ACOP L8. THE DUTY PASSES AT FIRST FILL, NOT AT FIRST OCCUPATION. Where the system is filled and then stands at low or nil occupancy before handover, the tenderer shall operate and record a flushing regime, and shall hand over the log with the O&M manual. This is scheduled as interface IF-10 and is not a matter the tenderer may leave to the operator."],
["4.13","Electrical services","Installation to BS 7671 as amended. Distribution boards accessible from circulation, not from bedrooms. Separate final circuits for lighting and power to each floor of each block. RCBO protection to every final circuit. Full test results, certificates and an as-installed schedule to be issued at handover; a certificate covering 'all circuits' without individual results will be rejected."],
["4.14","Plant and access","All plant requiring inspection, servicing or replacement shall be accessible without entering a bedroom and without removing permanent construction. Safe access provided for work at height. A maintenance access strategy drawing shall be submitted with the tender."],
["4.15","Fire detection and alarm","Category L1 system to BS 5839-1 unless the fire strategy at Appendix 2 requires otherwise. Addressable, with a repeat panel at reception and a mimic to the village management system. Zoning to the fire strategy. Cause and effect matrix submitted for approval before installation and demonstrated at commissioning."],
["4.16","Emergency lighting","To BS 5266-1, three-hour duration, self-testing where offered. Escape route illumination to 1 lux minimum on the centre line, open areas 0.5 lux. Full photometric calculation submitted for approval."],
["4.17","Lightning protection","Risk assessment to BS EN 62305 to be carried out by the tenderer for the village as sited, and protection installed where the assessment requires it. The assessment shall be issued whether or not it results in installation."],
["4.18","Access control","Offline battery locks as the room data sheets, integrated with the village management system supplied under this package. Audit trail retained for 90 days minimum. Master, floor-master and housekeeping key hierarchies to be agreed with the client before commissioning. Mechanical override provided and its keys handed over under a documented key control procedure."],
["4.19","Security and CCTV interface","Cabling, containment and power for external CCTV and the gatehouse interface are within this package to the termination points scheduled at 5.2. The cameras, recording and monitoring are supplied under P5 FM and Operation. Positions coordinated before installation, not after."],
["4.20","Signage and wayfinding","Statutory and fire signage throughout. Room numbering, floor identification and directional signage to a scheme submitted for approval. Signage to be legible under emergency lighting conditions."],
],

// performance schedule: [criterion, requirement, how verified]
perf: [
["Airborne sound insulation, between bedrooms","DnT,w + Ctr 45 dB minimum","Pre-completion testing to BS EN ISO 16283-1 on the sample at 9.3"],
["Airborne sound insulation, bedroom to corridor","DnT,w + Ctr 40 dB minimum, including the doorset","Pre-completion testing, same sample"],
["Impact sound insulation, floors","L'nT,w 62 dB maximum","Pre-completion testing to BS EN ISO 16283-2"],
["Rain noise","Demonstrated not to exceed 45 dB LAeq in a bedroom during the design rainfall event","Calculation, or manufacturer's test data for the roof build-up"],
["Fire resistance, separating construction","REI 60 between rooms, and between rooms and circulation","Third-party certified system, evidence submitted before order"],
["Fire resistance, doorsets","FD30S to bedrooms; FD60S where the fire strategy requires","Certified doorsets, labelled, register issued at handover"],
["Reaction to fire, internal linings","Class B-s3,d2 or better to circulation and escape routes","Manufacturer's classification report"],
["Thermal transmittance, external wall","0.22 W/m²K maximum","Calculation to BS EN ISO 6946, submitted with the tender"],
["Thermal transmittance, roof","0.16 W/m²K maximum","As above"],
["Thermal transmittance, floor","0.18 W/m²K maximum","As above"],
["Thermal transmittance, windows and doors","1.4 W/m²K maximum, whole unit","Manufacturer's data"],
["Thermal bridging","Psi values calculated for every junction type; no junction left to a default value","Calculation, submitted before manufacture"],
["Air permeability","5.0 m³/(h·m²) at 50 Pa maximum","Testing to ATTMA TSL1 on the sample at 9.4"],
["Overheating","Compliance with the criterion at Appendix 9","Dynamic thermal modelling to CIBSE TM59"],
["Ventilation, ensuite extract","15 l/s minimum, humidity sensing, 15 minute overrun","Commissioning measurement, every room, recorded"],
["Water outlet temperature","41 °C maximum at basin and shower; 50 °C minimum at the TMV inlet within one minute","Commissioning measurement, recorded per outlet"],
["Illuminance, bedroom","300 lux at the desk plane","Commissioning measurement on a sample of one room in ten"],
["Illuminance, escape routes","1 lux minimum on the centre line","Photometric calculation plus site verification"],
["Wireless coverage","−67 dBm minimum in every bedroom and amenity space, supporting 2 devices per resident concurrently","Site survey at commissioning, heat map issued"],
["Slip resistance, wet areas","PTV ≥ 36 wet","Manufacturer's data plus in-situ pendulum test on a sample"],
["Structural, floor loading","1.5 kN/m² imposed, bedrooms; 2.0 kN/m² circulation","Design calculations, submitted for approval"],
["Structural, wind","To BS EN 1991-1-4 for the site exposure at Appendix 8, including the temporary condition during installation","Design calculations"],
["Durability","All finishes to withstand 38 months of continuous single-occupancy use without replacement, fair wear and tear excepted","Warranty and a defined maintenance regime in the O&M"],
],

// interfaces: [ref, with, what is handed over, who certifies, when]
ifaces: [
["IF-01","P1 Civil Works","Bases set out, constructed and surveyed to the tolerance at 4.1","P1 issues the survey; this tenderer accepts it in writing","Not later than 2 weeks before each delivery"],
["IF-02","P1 Civil Works","One termination point per service per block — water, foul, power, data — at the position and invert on the coordination drawing","Joint drawing signed by both parties before either orders materials","Before P1 commences drainage"],
["IF-03","P1 Civil Works","Craneage hardstanding, access route and turning provision for the delivery vehicles and crane","P1, against this tenderer's stated loadings and swept path","4 weeks before first delivery"],
["IF-04","P3 Kitchen","Kitchen and dining building shell, with agreed penetrations, floor loading, drainage falls and extract routes","This tenderer supplies the shell; P3 confirms the penetration schedule before manufacture","Before module manufacture commences"],
["IF-05","P4 Furniture","The bedroom specification, item by item, dividing fixed joinery from loose furniture","Both parties against a single common schedule issued by the client","Before either package is let"],
["IF-06","P4 Furniture","Access for furniture installation after module setting and before handover","Programme coordination; this tenderer provides secure storage if the sequence slips","Per the agreed installation programme"],
["IF-07","P5 FM and Operation","Building services commissioning complete and demonstrated before any occupation","This tenderer, witnessed by P5 and by the client","Before the first resident arrives"],
["IF-08","P5 FM and Operation","O&M manuals, as-installed drawings, warranties, asset register and training","This tenderer; P5 acknowledges receipt against a checklist","2 weeks before handover"],
["IF-09","P5 FM and Operation","Access control key hierarchy and the audit trail configuration","Jointly, to a procedure agreed before commissioning","At commissioning"],
["IF-10","P5 FM and Operation","The water system at first fill, with the legionella duty and the flushing log","This tenderer operates and records until handover, then transfers with the log","At first fill, and again at handover"],
["IF-11","Client's fire engineer","The fire strategy, cause and effect matrix and the compartmentation drawing","The client's fire engineer approves; this tenderer implements","Before manufacture, and again at commissioning"],
["IF-12","Client","Planning conditions affecting external appearance, lighting and hours of installation","Client discharges; this tenderer complies and evidences","Before delivery commences"],
],
};
