// P1 — pricing, and the twenty-five questions answered.
module.exports = {

pricing: [
["1","How this is priced",
  "The tender is priced against the schedule below in its issued structure. A tenderer who alters it produces a return that cannot be compared with the others, and it will be marked accordingly.\n\nRates are inclusive of everything necessary to complete the item — labour, materials, plant, temporary works, design, testing, supervision, overheads and profit — except where an item is stated to be priced separately. A rate left blank is a rate of nil and the item is deemed included elsewhere; a tenderer intending to exclude something lists it as a departure under {{spec.1}} rather than leaving a cell empty."],
["2","What is firm and what is remeasured",
  "The following are the Employer's and are firm: the number of bases, 114; the number of blocks, 8; the areas and extents shown on NR-TW-VIL-0201, including the 0.42 ha laydown; the sectional bed numbers at {{§programme}}; and the loadings, tolerances, discharge rates and supply characteristics stated throughout this document.\n\nThe following are remeasured against the Contractor's own design and its own investigation: earthworks volumes, ground improvement, pavement thicknesses, drainage lengths and depths, and imported and exported material. The Contractor prices them against its stated assumptions, states those assumptions, and they are measured as executed.\n\nA tenderer that prices remeasured items against an unstated assumption has given a number nobody can evaluate."],
["3","The four items priced separately, and why",
  "Four items are pulled out of the general rates because folding them in makes them invisible and an invisible obligation is one that is not performed.\n\nSETTLEMENT MONITORING at {{spec.5}} — because it runs for 38 months, long after the site team has gone, and monitoring inside a preliminaries figure stops when the preliminaries stop.\n\nTHE AS-BUILT SURVEY AND ASSET DATA at {{spec.20}} — because it is a deliverable in its own right, it is used for 38 months and again at removal, and a record priced as an overhead is a record compiled at the end from memory.\n\nREINSTATEMENT at {{§demob}} — because it happens in 38 months and it is the item every tenderer forgets. Pricing it now also changes the design of what is built.\n\nTHE OCCUPIED-VILLAGE REGIME at {{§occupied}} — the marshalling, the monitoring, the wheel washing, the sweeping, the standby tanker and generator. It is not a preliminary. It is a method of working that starts in month 3 and costs money every week thereafter, and a tenderer that has not priced it has priced a different job."],
["4","Payment",
  "Payment is by monthly application against work properly executed, valued against this schedule.\n\nEach sectional payment is conditional on the deliverables for that section: the base surveys accepted, the commissioning certificates at {{spec.18}} issued, the fire access and hydrant availability statement at {{spec.14}} issued, and the asset data for that section issued within 4 weeks per {{info.2}}.\n\nRetention is released against sectional completion and against the completion of the reinstatement at {{demob.4}}, in the proportions the Contract states. The reinstatement and aftercare sums are not released against practical completion of the construction works."],
],

// [item, description, basis, note]
schedule: [
["A","DESIGN, INVESTIGATION AND MOBILISATION","",""],
["A1","Ground investigation to {{spec.2}}, including all in-situ and laboratory testing","Lump sum","State the number of holes, the depths and the testing schedule"],
["A2","Earthworks, pavement, foundation and drainage design","Lump sum","Including the settlement prediction supporting {{spec.5}}"],
["A3","Survey control network to {{spec.6}}, establishment and quarterly verification","Lump sum","4 permanent stations, and every reverification issued"],
["A4","Pre-development condition survey and the CEMP baseline","Lump sum","{{demob.3}}. Without it there is no reference for reinstatement"],
["A5","Mobilisation, site establishment and temporary services","Lump sum",""],
["B","EARTHWORKS AND GROUND","",""],
["B1","Site clearance, within the CEMP's seasonal constraints","m² / Lump sum","State the seasonal assumption. {{sustain.2}}"],
["B2","Excavation, filling and compaction to formation","m³, remeasured","State the cut and fill balance assumed. {{sustain.1}}"],
["B3","Material imported to site","m³, remeasured","State the source and haul distance"],
["B4","Material taken off site, by classification","m³, remeasured","{{sustain.1}} and {{spec.19}}"],
["B5","Ground improvement","Provisional, remeasured","{{spec.3}}. Priced against the Contractor's own investigation"],
["B6","Formation testing and proof rolling","Rate per test","1 per 200 m² minimum, {{spec.3}}"],
["C","BASES AND SLABS","",""],
["C1","Module bases, complete to the tolerances at {{§tolerance}}","Rate per base × 114","Including the individual survey of each"],
["C2","Kitchen and dining building slab to the loadings at {{spec.4}}","m²","5.0 / 7.5 / 3.0 kN/m², NOT the 3.0 kN/m² of P2 Appendix 8"],
["C3","Amenity and reception building slabs","m²",""],
["C4","Generator base, plinth, bunding and enclosure base","Lump sum","{{spec.12}}"],
["C5","Independent survey check of the Employer's 10% sample","Lump sum","{{spec.6}}. At the Contractor's cost, including any 100% re-survey triggered"],
["D","ROADS, HARDSTANDING AND EXTERNAL AREAS","",""],
["D1","Site roads and haul routes, designed for construction AND 38 months of operation","m²","{{spec.8}}. One pavement, not two"],
["D2","CRANE HARDSTANDING, including plate bearing proof and every re-test","Rate per crane position","{{spec.7}}. State the design bearing pressure priced"],
["D3","Laydown area, 0.42 ha, surfaced and drained","Lump sum","Extent is fixed and is smaller than a tenderer may assume"],
["D4","Car parking and the transport pick-up, sized for the P5 vehicle without reversing","Lump sum","{{iface.IF-12}}"],
["D5","Footpaths, ramps and external steps to {{spec.11}}","m²","PTV ≥ 36 wet, tested on the installed surface"],
["D6","External finished levels at door thresholds to {{tolerance.4}}","Included in D5","Measured and surveyed at every external door"],
["E","DRAINAGE","",""],
["E1","Foul drainage, collection to outfall","m, remeasured","{{spec.9}}. State the discharge unit loading and simultaneity used"],
["E2","Surface water drainage and flow control","m, remeasured","{{spec.10}}"],
["E3","Attenuation storage for the 1 in 100 year event + 40%","m³","State the volume and the rainfall data assumed"],
["E4","Treatment, interceptors and silt traps","Lump sum",""],
["E5","Grease separator chamber, connection and tanker hardstanding","Lump sum","{{spec.10}} and {{iface.IF-10}}. Emptied without entering the village"],
["E6","CCTV survey, air or water testing of every run","Lump sum","{{spec.18}}"],
["F","SERVICES TO THE TERMINATION POINTS","",""],
["F1","Water supply, distribution, boosting and storage to the duty at {{spec.13}}","Lump sum","2.0 bar at 1.5 l/s, static ≤ 5 bar, at 9 terminations"],
["F2","Chlorination, sampling and bacteriological testing at EACH sectional occupation","Rate per stage × 4","{{spec.13}}. Not once at practical completion"],
["F3","Electrical distribution to 8 blocks at 250 kVA and the kitchen at 200 kVA","Lump sum","{{spec.12}}"],
["F4","Earthing, fault level and loop impedance measurement at every termination","Lump sum","{{iface.IF-06}}. Measured, not assumed"],
["F5","Standby generation — 500 kVA set, changeover, fuel storage and bunding","Lump sum","{{spec.12}}. Including the 4-hour full-load witnessed test"],
["F6","Data ducting, draw rope, and 2 fibre pairs per block terminated and tested","Lump sum","{{spec.15}}"],
["G","FIRE, LIGHTING, BOUNDARY AND LANDSCAPE","",""],
["G1","Fire appliance access routes to {{spec.14}}","Included in D1","Availability from FIRST occupation is the requirement, not completion"],
["G2","Hydrants, tested individually at 1,500 l/min at 1.7 bar","Rate per hydrant","{{spec.14}}"],
["G3","Fire access and hydrant availability statement before each sectional occupation","Rate per statement × 4","{{spec.14}}. Reissued on any change to the construction arrangement"],
["G4","External lighting to the levels at {{spec.11}}, full cut-off","Lump sum","Including the illuminance and light-spill measurement"],
["G5","Fencing, gates and the gatehouse position","m / Lump sum","{{spec.16}}"],
["G6","THE SEGREGATION LINE, including every planned move at months 3, 6, 9 and 12","Lump sum","{{spec.16}}. Four moves, each a planned operation"],
["G7","Landscape, planting and CEMP ecology works","Lump sum","{{sustain.2}}"],
["H","THE OCCUPIED-VILLAGE REGIME — PRICED SEPARATELY","",""],
["H1","Marshalling of every construction and pedestrian crossing point","Rate per week","{{occupied.2}}. A person, not a sign"],
["H2","Noise and vibration monitoring, 2 boundary positions, logged and issued weekly","Rate per week","{{occupied.3}}"],
["H3","Dust suppression, wheel washing and mechanical road sweeping","Rate per week","{{occupied.4}}"],
["H4","Standby tanker and temporary generator provision for service interruptions","Rate per event / Lump sum","{{occupied.5}}. Assume not fewer than 4 events"],
["H5","Temporary drainage of the working area, maintained","Lump sum","{{hse.2}}. The temporary work that is forgotten"],
["J","COMMISSIONING, TESTING AND RECORDS","",""],
["J1","Commissioning and testing of every service, results per termination","Lump sum","{{spec.18}}"],
["J2","Sectional commissioning at months 3, 6, 9 and 12","Rate per section × 4","Not one event at practical completion"],
["J3","AS-BUILT SURVEY AND ASSET DATA — PRICED SEPARATELY","Lump sum","{{spec.20}}. Issued within 4 weeks of each sectional completion"],
["J4","Health and safety file information and O&M to P5","Lump sum","{{iface.IF-13}}"],
["K","SETTLEMENT MONITORING — PRICED SEPARATELY","",""],
["K1","Monitoring point installation and baseline survey of every base","Rate per base × 114","{{spec.5}}"],
["K2","Monitoring and reporting, months 1–6, monthly","Rate per report","With computed differentials, not absolute levels alone"],
["K3","Monitoring and reporting, months 7–12, quarterly","Rate per report",""],
["K4","Monitoring and reporting, month 13 to end of deployment, six-monthly","Rate per report","This is the one that gets dropped. It is priced here"],
["L","REINSTATEMENT AND AFTERCARE — PRICED SEPARATELY","",""],
["L1","Removal of bases, slabs, roads, hardstanding, fencing and lighting","Lump sum","{{demob.2}}"],
["L2","Removal or capping of buried services to 600 mm below reinstated level","Lump sum","{{demob.2}}. What is left is the Employer's decision, not the Contractor's"],
["L3","Subsoil ripping and decompaction","m²","{{demob.3}}. The step that is skipped"],
["L4","Topsoil replacement, seeding, planting and habitat works","m²","To the CEMP, within its seasonal windows"],
["L5","Aftercare, 24 months, including replacement of failures","Lump sum","{{demob.4}}"],
],

register: [
["G01","No design responsibility matrix or Contractor's Proposals mechanism","{{spec.1}}: the outcomes the Employer states are listed, everything else is the Contractor's design, the Contractor's Proposals are specified item by item, a Schedule of Departures is required with the tender, and review is stated not to transfer responsibility"],
["G02","Prescriptive and performance specification mixed","Every one of the 24 works lines at {{§works}} carries an E or C code — 16 prescribed, 8 contractor-designed — and clause 1.2 states that the only prescribed lines are a tolerance another package must build to, or a statutory or life-safety requirement. Everything else is a duty"],
["G03","No stated failure mode","{{spec.12}}: standby changeover on load within 15 seconds, 72 hours of fuel at the essential load, and a bund that does not discharge to any drainage system. {{spec.14}}: fire access and hydrants available from FIRST occupation and maintained throughout construction, with an availability statement before each section is occupied"],
["G04","No damages or delay mechanism","{{programme.5}}: £145 per bed per day per sectional date, the same rate as the P2 sectional damages because it is the same loss, with the five causes of an extension of time named and a 10-working-day notification duty"],
["G05","No defects regime","{{§defects}}: 12 months per section, 24 months for buried services, and SETTLEMENT FOR THE WHOLE 38-MONTH DEPLOYMENT because settlement does not appear in twelve months. Three priorities with times, and Priority 1 shorter than P2's because an open excavation cannot wait for a manufacturer's engineer to travel"],
["G06","No temporary works regime","{{hse.2}}: BS 5975, a named Temporary Works Coordinator, excavation support and inspection, and TEMPORARY DRAINAGE named as a temporary work in the register — the one that is forgotten, and the one that floods the occupied section"],
["G07","Relocation imposed without a requirement","{{§demob}}: what is removed, what may be left and who decides, the 600 mm rule, decompaction, the pre-development condition survey taken BEFORE work starts as the reference, and 24 months of aftercare. All of it priced now at section L"],
["G08","No information requirements","{{§info}}: the P2 Appendix 11 schema unamended, coordinated to the survey network, issued progressively within 4 weeks of each sectional completion and conditional on payment. A scanned PDF is stated not to discharge it"],
["G09","No site constraints","{{§occupied}}: six clauses on building the last section without crossing the first, written for a person walking to a bus at 05:00 in January. Sequence, noise, dust and mud, service interruptions, and security in a village that is somebody's home"],
["G10","No electrical supply characteristics","{{spec.12}}: 400/230 V, 50 Hz, TN-S, 250 kVA per block and 200 kVA to the kitchen, with the prospective fault current and earth loop impedance MEASURED at every termination rather than taken from the connection offer"],
["G11","No water supply characteristics","{{spec.13}}: 2.0 bar dynamic at 1.5 l/s, static not exceeding 5 bar — both ends stated, because below the first the showers fail and above the second the fittings leak. Plus the stagnation regime for a village that fills in four stages over nine months"],
["G12","No evacuation or alarm strategy","{{spec.14}} and {{iface.IF-16}}: 45 m access to every point of every storey, hydrants within 90 m at 1,500 l/min, and no excavation or closure of a fire route without a documented alternative in place FIRST"],
["G13","A figure that was tight for the technology","The tolerances at {{§tolerance}} are tight and they are stated as rejection thresholds with the reason for each. The 3 mm relative level between adjacent bases is the tightest figure in the document, and {{tolerance.3}} says why: a module spanning two bases at different levels is racked before it is loaded"],
["G14","No loading or serviceability criteria","{{spec.4}} carries the full loading schedule AND states the fault in the Employer's own pack: P2 Appendix 8 gives 3.0 kN/m² for amenity and dining and NO kitchen production loading at all. This document requires 5.0 / 7.5 / 3.0 kN/m² and says the appendix is to be updated. It is the same statement the P3 requirements make from the other side"],
["G15","No change control","{{§change}}: written instruction from the named representative only, valuation before instruction, the unforeseen-conditions test at {{change.3}}, and the rule that a change originating in another package is instructed by the Employer and never agreed between contractors"],
["G16","Float ownership not stated","{{programme.2}}: float belongs to the project and is available to whichever party needs it until it is gone. The Contractor also shows the statutory connections as they really are and states the date at which a delay in each becomes critical"],
["G17","No sustainability requirement","{{§sustain}}: monthly reporting of cut and fill balance, imported and exported material with destinations, cement replacement, diesel and lorry movements — and {{sustain.3}}, which asks the Contractor to state honestly what it has designed to be recoverable in 38 months and what it has not"],
["G18","No testing regime for the thing that fails","{{spec.7}}: PLATE BEARING PROOF of every crane hardstanding before the first lift, at 2 positions per crane position, with re-testing after winter idleness, flooding or nearby excavation. A design calculation is stated not to be proof"],
["G19","Missing drainage detail","{{spec.9}} and {{spec.10}}: congested-use discharge loading rather than domestic, gradients and invert tolerances, the 1.20 m foul invert below FFL that P2 designs from, and every chamber that has to be emptied reachable by a tanker without entering the village"],
["G20","No obsolescence or support period","{{spec.8}}: the pavement's residual design life at completion and the maintenance regime it requires, issued to P5 who prices its operation from it. {{spec.5}}: monitoring for the full deployment. {{demob.4}}: 24 months of aftercare"],
["G21","No inspection checklist","{{§performance}}: 35 criteria, each with a figure and a stated method of verification, and {{spec.17}}: an Inspection and Test Plan per element with five named hold points that cannot be passed without written release"],
["G22","No definitions","{{§definitions}}: 11 terms, including differential settlement, outrigger pressure, termination point, the segregation line, and tolerance defined as the figure beyond which work is rejected rather than an aspiration"],
["G23","No ethical labour requirement","{{§labour}}: no recruitment fee, no document retention, direct payment into the worker's own account, flow-down to every tier and every agency worker, audit without notice, and conduct standards for people working where 225 others live"],
["G24","Clauses with no measurable requirement","Every performance criterion carries a figure and a verification method; every tolerance is a number with a measurement method; illuminance, light spill, noise, vibration, slip resistance, hydrant flow, changeover time, generator noise and settlement all carry a value and the way it is measured"],
["G25","No security requirement","{{occupied.6}}: excavations covered or fenced whenever unattended without exception, plant immobilised, materials stored inside the construction area, personnel identifiable and inducted, and fuel security treated as a real risk because diesel on a remote site disappears"],
],
};
