// P1 — the occupied-village regime, performance, and the management sections.
module.exports = {

// ---------------------------------------------------------------- occupied
occupied: [
["1","The condition that governs everything from month 3",
  "From month 3 this site is TWO SITES sharing a boundary: a live construction site, and a village where up to 225 people sleep, eat, wash and wait for a bus. They are separated by the line at {{spec.16}} and by nothing else.\n\nOne of those two populations has not been inducted, is not wearing PPE, is asleep for half of every day, and includes people who have just finished a twelve-hour shift. They are not visitors and they are not trespassers. They live here, and they will take the shortest route to the canteen.\n\nEVERY REQUIREMENT IN THIS SECTION FOLLOWS FROM THAT. None of it is boilerplate, and a tenderer that prices this package as a greenfield civils job has priced the wrong job."],
["2","Sequence, and building the last section without crossing the first",
  "The village is occupied in four sections — 65 beds at month 3, cumulative 150 at month 6, 205 at month 9 and 225 at month 12.\n\nThe Contractor shall submit, with its tender, a sequence and logistics plan showing for each of those four stages: where the segregation line runs; the construction access route and how it reaches the remaining work WITHOUT crossing the occupied village; where deliveries and cranes stand; where the fire access routes at {{spec.14}} run and how they stay available; and the pedestrian routes residents will use.\n\nA plan in which a construction vehicle route crosses a resident pedestrian route at grade will be rejected unless the crossing is controlled, signalised or marshalled, and the plan says which.\n\nWHERE A CROSSING IS UNAVOIDABLE, it is marshalled — by a person, not by a sign. The Contractor shall price the marshalling."],
["3","Noise, and a village where somebody is always asleep",
  "THE SITE RULES AT APPENDIX 3 GIVE ONE LIMIT and this document states it before adding to it: once any block is occupied, no work generating more than 65 dB(A) at the facade of an occupied block between 20:00 and 07:00 without the Employer's written agreement.\n\nTHAT RULE WAS WRITTEN FOR A SITE WHERE PEOPLE SLEEP AT NIGHT. In this village 101 residents work nights and sleep during the working day, and there is no hour at which noisy work is free. Appendix 3 continues to govern and nothing below reduces it; where this clause and Appendix 3 differ, the MORE ONEROUS applies.\n\nTHIS CONTRACTOR SHALL NOT PROGRAMME any activity between 20:00 and 07:00 that depends on the Employer's written agreement being given. If it needs that agreement it has programmed the work into the wrong window.\n\nADDITIONALLY, and measured to BS 5228-1 at the facade of the nearest occupied block:\n\n65 dB LAeq,1h between 07:00 and 20:00 generally.\n55 dB LAeq,1h between 08:00 and 16:00 at any block P5 has designated as night-shift sleeping accommodation. P5 designates those blocks and notifies the Contractor monthly; the designation moves as the shift pattern moves.\nPILING, BREAKING, VIBRATORY COMPACTION AND ROCK BREAKING within 50 m of an occupied block only within a window agreed with the Employer and P5 not less than 5 working days in advance, and notified to residents by P5.\nVIBRATION at any occupied block not exceeding 3 mm/s peak particle velocity, measured to BS 5228-2, monitored continuously during any activity capable of exceeding it, with the record issued weekly.\nReversing alarms within the village boundary shall be broadband, not tonal.\n\nMONITORING. Continuous noise monitoring at not fewer than 2 positions on the village boundary from first occupation, logged, and the log issued weekly with any exceedance explained. An exceedance discovered from a complaint rather than from the log means the monitoring was not doing its job.\n\nA CONTRACTOR THAT WAKES THE NIGHT SHIFT loses the site's cooperation for the rest of the deployment, and it is not recovered by apologising."],
["4","Dust, mud and the things that arrive on a boot",
  "DUST. Dust suppression on every haul route, every stockpile and every earthworks operation, with water bowsers available and used, and stockpiles sheeted or seeded where they will stand for more than 4 weeks. Dust deposition monitored at the village boundary and the record issued monthly.\n\nDust from an earthworks operation lands on the washing line, on the cars in the car park, and in the kitchen's fresh air intake. The last of those is a food safety issue and it belongs to P3 to manage and to this package not to cause.\n\nMUD. Wheel washing at every exit from the working area onto a route used by residents or by the public, and mechanical road sweeping of those routes, not brushing. A road with mud on it is the slip hazard in this document that actually injures somebody, and it injures them at 05:00 in the dark in work boots.\n\nMUD ON THE FOOTPATHS is removed the same day. Not at the end of the week."],
["5","Interruptions to a service somebody is living on",
  "From first occupation, every service this package provides is a service somebody is living on. A water shut-off is 225 people who cannot shower before shift.\n\nNO PLANNED INTERRUPTION to water, power, drainage, data, lighting, heating or fire cover to any occupied part of the village without:\n\nNot less than 10 working days' written notice to the Employer and to P5, stating the service, the area, the start, the duration and the contingency;\nAn agreed window, which for water and power shall be outside 04:30–07:30 and 17:00–20:00 unless P5 agrees otherwise, because those are the shift-change windows;\nA contingency in place before the interruption starts — temporary supply, tankered water, or a generator, provided by this Contractor at its cost;\nAnd for any interruption to fire detection, alarm, fire access or hydrant cover, an alternative in place FIRST and the Employer's written release, per {{spec.14}}.\n\nUNPLANNED INTERRUPTION. Notify P5 and the Employer within 15 minutes, restore or provide a temporary supply within 4 hours, and issue a written account within 24 hours of what failed and what has changed so that it does not recur.\n\nThe Contractor shall price the standby provision this clause requires. A tenderer that has not priced a tanker and a temporary generator has assumed nothing will go wrong on a site where excavation happens next to a live main for eighteen months."],
["6","Security, and two populations who both belong here",
  "This site has residents who are entitled to be here and are not construction workers, and construction workers who are entitled to be here and are not residents. Access control is written for both.\n\nThe Contractor's personnel shall be identifiable, inducted and recorded, and shall not enter the occupied village outside the areas and times their work requires.\n\nEXCAVATIONS AND OPENINGS within or adjoining the village shall be physically covered or fenced whenever unattended, without exception and regardless of duration, and inspected at the end of every shift. An excavation left open behind a barrier on a site where people walk home in the dark after a twelve-hour shift is an excavation somebody will fall into.\n\nPLANT shall be immobilised and keys removed when unattended. Fuel, materials and plant shall be stored inside the construction area and not in the village.\n\nSAFEGUARDING AND CONDUCT. The Contractor's personnel are working in what is, for 225 people, their home. The standards of conduct at {{§labour}} apply to every person this Contractor brings to site, including every subcontractor and every agency worker, and a breach is a removal from site."],
],

// -------------------------------------------------------------- performance
// [criterion, requirement, verification]
perf: [
["Base level","± 5 mm across any single base","Levelled survey of every base, issued before module delivery"],
["Base position","± 10 mm on plan","Coordinated survey against the setting-out drawing"],
["Relative level, adjacent bases under one module","± 3 mm","Survey of every adjacent pair, computed and reported"],
["Base flatness","3 mm under a 1 m straightedge","Straightedge at not fewer than 5 positions per base"],
["Threshold level at external doors","−15 mm to 0 mm relative to module FFL","Survey at every external door after external works"],
["Independent survey check","100% of a block re-surveyed on any failure in the 10% sample","Employer-selected sample, at the Contractor's cost"],
["Total settlement","15 mm maximum over the deployment","Monitoring per the frequency at {{spec.5}}"],
["Differential settlement, one module","5 mm maximum","Monitoring, computed for every adjacent pair"],
["Differential settlement, one block","10 mm maximum","Monitoring, computed across the block"],
["Formation strength","The CBR the pavement design assumes","Plate bearing or DCP, 1 test per 200 m²"],
["Earthworks compaction","As the Contractor's specification requires","1 in-situ density test per 500 m² per layer, minimum 3"],
["Crane hardstanding capacity","Not less than the outrigger pressure P2 states","Plate bearing test, 2 positions per crane position, before first lift"],
["Road and hardstanding level","± 20 mm","Survey grid at not more than 10 m centres"],
["Ponding","No standing water anywhere on any trafficked or walked surface","Visual inspection after a rainfall event, recorded"],
["Surface water discharge","5 l/s per hectare maximum","Flow control device proved by measurement"],
["Flood risk","No flooding of any building, road or footpath in the 1 in 100 year event + 40%","Design calculation, submitted and accepted"],
["Foul gradient","Within 10% of design, never flatter than self-cleansing","Invert survey at every manhole"],
["Drainage integrity","No defect on CCTV; air or water test passed","CCTV survey of every run, and test certificate"],
["Water pressure at each termination","≥ 2.0 bar dynamic at 1.5 l/s; static ≤ 5 bar","Measurement at each termination point individually"],
["Water quality","Satisfactory bacteriological result","Sampling and testing before EACH sectional occupation"],
["Electrical supply at each termination","≥ 250 kVA per block; ≥ 200 kVA kitchen; TN-S","Measurement and test certificate per termination"],
["Standby changeover","On load within 15 seconds","Demonstrated at commissioning, and monthly thereafter by P5"],
["Standby run","4 hours at full essential load","Witnessed test with fuel consumption recorded"],
["Generator noise","≤ 40 dB LAeq at the nearest bedroom window at night","Measurement during a night-time test run"],
["Hydrant performance","≥ 1,500 l/min at 1.7 bar at every hydrant","Flow test, each hydrant individually"],
["Fire appliance access","Within 45 m of every point of every storey","Drawing and swept path, verified on the completed route"],
["Fire cover availability","Complete and tested before each sectional occupation","Availability statement issued before occupation"],
["Footpath illuminance","10 lux average, 3 lux minimum, uniformity ≥ 0.25","Measured on a grid on the installed installation"],
["Light spill at bedroom windows","≤ 5 lux vertical, 23:00–07:00","Measured at the window, in the plane of the glass"],
["Footpath slip resistance","PTV ≥ 36 wet","Tested on the installed surface"],
["Construction noise at occupied blocks","65 dB LAeq,1h 07:00–20:00; 55 dB LAeq,1h 08:00–16:00 at a designated night-shift block","Continuous monitoring at 2 boundary positions, logged weekly"],
["Night working noise","65 dB(A) at the facade, 20:00–07:00, per the Appendix 3 site rule — and not programmed for","Appendix 3 governs; this Contractor does not rely on the written agreement"],
["Vibration at occupied blocks","≤ 3 mm/s peak particle velocity","Continuous monitoring during any capable activity"],
["Unplanned service interruption","Temporary supply within 4 hours","Incident record, issued within 24 hours"],
["As-built data","Issued within 4 weeks of each sectional completion","Employer's acceptance against the schema at P2 Appendix 11"],
],

// --------------------------------------------------------------- programme
programme: [
["1","The dates this package is measured against",
  "This package has no single completion date that matters. It has four, and they are the sectional occupation dates the whole village is built around: 65 beds at month 3, cumulative 150 at month 6, 205 at month 9, and 225 at month 12.\n\nFor each section, this package's works are complete when: the bases are surveyed and accepted; the access and fire routes at {{spec.14}} are available; every service to that section is commissioned and certified under {{spec.18}}; the footpaths and lighting to that section are complete; and the as-built data for it has been issued.\n\nA section is not occupied on a promise that the lighting follows. The people occupying it walk to the canteen that night."],
["2","The programme the Contractor submits, and what it has to show",
  "With its tender the Contractor shall submit a programme in a critical path method form, showing the sectional dates above, the earthworks seasons, the ground investigation at {{spec.2}}, the design and approval periods, the statutory connections at {{iface.IF-15}}, the crane hardstanding dates against P2's lift programme, and the float it holds and where.\n\nIT SHALL SHOW THE STATUTORY CONNECTIONS AS THEY REALLY ARE. A DNO connection and a water undertaker's connection are procured by the Employer and delivered by third parties on their own timescales, and they are the single most common cause of a village that is built and cannot be occupied. The Contractor shall state the dates it requires and the date by which a delay in each becomes critical.\n\nFLOAT belongs to the project and is available to whichever party needs it, until it is gone. It is not owned by the Contractor by virtue of having programmed it."],
["3","Progress, and reporting that is worth reading",
  "Monthly progress report against the accepted programme, stating: percentage complete by element; the bases surveyed and accepted to date against the number required for the next sectional date; the critical path as it now stands and how it has changed; every open interface at {{§iface}} and its status; the test and hold point record; and any matter that could affect a sectional occupation date, whether or not it is this Contractor's responsibility.\n\nThe last of those is the point of the report. A contractor that reports only its own works reports a project that is on programme up to the month it is not."],
["4","Adverse weather, and the two winters in this programme",
  "This programme contains two winters and a full earthworks operation. Weather is not an unforeseen event on a civil engineering project in the United Kingdom; it is a planned condition.\n\nThe Contractor shall state in its Proposals the weather limits at which it will stop each principal operation, and shall programme on the basis of the published 10-year average for the site's region for rainfall days, temperature and wind.\n\nAN EXTENSION OF TIME FOR WEATHER is available only where the weather encountered in a month is worse than that 10-year average for that month, measured at the nearest published station, and only for the operations actually prevented. It is not available for the winter itself.\n\nThe Contractor shall record the weather daily from the first day on site, including the operations affected and the hours lost. A claim supported by a retrospective weather report and no site record will not be accepted, because by then nobody can say what was being done that day."],
["5","Delay, and what a late section actually costs",
  "Delay damages apply to each sectional occupation date separately, at £145 PER BED PER DAY for every bed in that section that cannot be occupied on its date.\n\nThat is the same rate as the P2 sectional damages because it is the same loss. When a section is late the Employer houses those people somewhere else, and the cost is a bed in a hotel, a longer bus journey and a shift that starts late — and it is incurred whether the bed is late because the module is late or because the base under it is not ready.\n\nIt is stated as a genuine pre-estimate of that loss and it is not a penalty. It is stated in this document rather than left to a schedule so that a tenderer prices the risk of a late section knowingly.\n\nWHERE THE DELAY IS NOT THE CONTRACTOR'S, an extension of time is granted and damages do not run. The causes are: a change instructed under {{§change}}; an unforeseen physical condition meeting the test at {{change.3}}; weather exceeding the threshold at {{programme.4}}; a statutory connection at {{iface.IF-15}} delivered late by the third party; and any act of prevention by the Employer or by another package.\n\nA claim shall be notified within 10 working days of the event becoming apparent and shall be supported by the records kept at the time. It is not established two years later from a programme rebuilt after the fact."],
["6","Acceleration, and what the Employer will and will not pay for",
  "Where a sectional occupation date is at risk for a cause within the Contractor's control, the Contractor shall accelerate at its own cost and shall submit a recovery programme within 10 working days of the risk becoming apparent.\n\nWhere the Employer instructs acceleration for a cause that is not the Contractor's, it is a change under {{§change}} and it is valued before it is carried out, not after.\n\nWORKING LONGER HOURS IS NOT ALWAYS AVAILABLE HERE. From month 3, acceleration by extending hours runs straight into the noise limits at {{occupied.3}}, and those limits are a planning condition and a duty to the people asleep in the village. A recovery programme built on evening working is not a recovery programme."],
],

// --------------------------------------------------------------------- hse
hse: [
["1","The duties this section does not restate",
  "The Contractor is a designer and a contractor under the Construction (Design and Management) Regulations 2015 and shall discharge those duties. It shall also comply with the Health and Safety at Work etc. Act 1974, the Work at Height Regulations 2005, the Lifting Operations and Lifting Equipment Regulations 1998, the Control of Substances Hazardous to Health Regulations 2002, the Confined Spaces Regulations 1997 and every other applicable statutory requirement.\n\nNothing in this document reduces those duties and nothing in this document is a substitute for them. The clauses that follow are the requirements this site has that a competent contractor's standard arrangements do not automatically cover."],
["2","Temporary works, and the ones that fail quietly",
  "All temporary works designed, checked and controlled to BS 5975, with a Temporary Works Coordinator appointed by name and a register maintained.\n\nEXCAVATION SUPPORT. No person shall enter any excavation deeper than 1.2 m that is not supported or battered to a design, and every excavation shall be inspected at the start of every shift and after any event that could have affected it, with the inspection recorded.\n\nTEMPORARY DRAINAGE IS A TEMPORARY WORK AND IT IS THE ONE THAT IS FORGOTTEN. The site shall be drained throughout construction so that a partly built village does not flood the part that is occupied, and so that surface water from the working area does not run onto an occupied section, a footpath or a road. The temporary drainage design shall be in the register, shall be reviewed at each change of the working arrangement, and shall be maintained — a temporary ditch that has silted up is not drainage.\n\nCRANE HARDSTANDING is a temporary work in the register and its proof testing at {{spec.7}} is a hold point under {{spec.17}}."],
["3","Underground services, and the permit to dig",
  "Every excavation on this site is carried out under a permit to dig, from the first excavation to the last, without exception for depth, duration or urgency.\n\nThe regime shall follow HSG47 and shall include, before every excavation: current service drawings including this package's own as-built record at {{spec.20}}; a cable avoidance tool and signal generator survey by a trained operative; the marking of located services on the ground; and safe digging practice, with hand digging within 500 mm of any located or suspected service.\n\nAS THE VILLAGE FILLS, THE RISK GETS WORSE AND NOT BETTER. Every month there is more buried service and more of it is live and occupied. From month 3 a struck cable is 65 people without power; by month 12 it is 225 people without power, without hot water, and possibly without fire detection.\n\nA STRIKE OR NEAR MISS shall be reported to the Employer within 2 hours, investigated, and the finding issued in writing. A near miss that is not reported is the strike that happens next month, and it happens to somebody else."],
["4","Lifting over an occupied village",
  "Every lifting operation planned under LOLER by an Appointed Person, with a written lift plan for every lift and not one plan for a category of lifts.\n\nNO LOAD SHALL BE SLEWED OVER ANY OCCUPIED BUILDING, occupied part of the village, resident pedestrian route or public highway. Where the geometry of a lift makes that impossible, the lift does not proceed until the area beneath is cleared and controlled, and the clearance is a documented and marshalled operation agreed with P5, not an announcement.\n\nWIND. A stated maximum wind speed for every lift, measured at the crane and not forecast, and a documented stop.\n\nThe hardstanding proof at {{spec.7}} is a precondition of every lift and its record is held with the lift plan."],
["5","The people this package brings to site",
  "Every person inducted before starting work, with the induction covering the segregation line at {{spec.16}}, the noise regime at {{occupied.3}}, the permit to dig at {{hse.3}}, the fire access routes at {{spec.14}}, and the fact that 225 people live on the other side of the fence.\n\nCompetence recorded for every person carrying out a task requiring it, including plant operators, banksmen, the Appointed Person and the Temporary Works Coordinator, and verified rather than asserted.\n\nAccident, incident and near miss reporting to the Employer within 4 hours for anything reportable under RIDDOR and within 24 hours for anything else, with the investigation issued within 10 working days."],
],

// -------------------------------------------------------------------- info
info: [
["1","What is delivered, and in what form",
  "Asset information to the schema at P2 Appendix 11, which applies to this package unamended. Every asset carries the identifier that schema specifies and is coordinated to the survey control network at {{spec.6}}.\n\nThe deliverables are: the as-built survey at {{spec.20}}; the operation and maintenance information for every asset that P5 will maintain; the health and safety file information required under CDM 2015; the test, commissioning and certification records at {{spec.18}}; the settlement monitoring baseline and the subsequent reports at {{spec.5}}; and the maintenance access drawing at {{spec.10}}.\n\nA scanned PDF of a marked-up drawing is not asset data and does not discharge this section."],
["2","When, which is progressively and not at the end",
  "Information for each section is issued within 4 weeks of that section's completion, at months 3, 6, 9 and 12, and is a precondition of the payment for that section under {{§pricing}}.\n\nInformation held to the end of the package is information compiled from memory by people who have moved to another job. The Employer would rather have four accurate sets than one complete one."],
["3","Why this package's record matters more than most",
  "P5 operates this site for 38 months and every excavation it makes is planned from this record. P2, P3 and P4 all work to positions this package set. At the end of the deployment the village is removed and, if the Employer elects, relocated, and what is dug up is read off this record.\n\nA depth that is wrong on this record is a struck service in year three, and nobody will be able to ask the person who dug it."],
],

// ------------------------------------------------------------------ change
change: [
["1","The only route by which anything changes",
  "No change to the Employer's Requirements, to the Contractor's accepted Proposals, to a tolerance, to a level, to a termination point or to a specification takes effect except by a written instruction from the Employer's authorised representative.\n\nNo instruction given verbally, in a meeting, on a drawing marked up on site, or by any other package's contractor has any effect whatsoever. This package sets levels that eight other parties build to, and a level changed by conversation is a level that exists in two versions."],
["2","Valuation, and knowing the price before the work",
  "Every proposed change is valued and its programme effect stated BEFORE it is instructed, using the rates in the priced schedule at {{§pricing}}, or where no rate applies, by a build-up the Contractor submits and the Employer accepts.\n\nThe Contractor shall submit its quotation within 10 working days of a request. Where the Employer instructs work to proceed before the valuation is agreed, the instruction shall say so expressly and the records required to value it shall be kept from the first day, agreed daily, and signed."],
["3","Unforeseen physical conditions, and where the line is",
  "A physical condition is unforeseen only if it meets the test at {{spec.2}}: it could not reasonably have been anticipated by an experienced contractor from the factual data provided, a site inspection, and the investigation this document requires the Contractor to carry out.\n\nWHERE IT MEETS THAT TEST, it is a change, valued under {{change.2}}, with the programme effect assessed. Where it does not, it is at the Contractor's risk and it was priced in the tender.\n\nTHE NOTIFICATION DUTY IS SEPARATE FROM THE COMMERCIAL ONE. The Contractor shall notify within 4 hours of encountering a condition it considers unforeseen, per {{spec.19}}, whether or not it has decided to claim, and shall keep the evidence — photographs, survey, samples — before disturbing it. A notification is not a claim and the Employer will not treat it as one.\n\nThe reason this is written this way is that the alternative does not work. A contractor that thinks notifying means claiming waits until it has priced the claim, and by the time anybody looks, the material is in a lorry."],
["4","Change originating in another package",
  "Where another package requires a change to this one — a termination moved, a level altered, a loading increased, a hardstanding relocated — it is instructed by the Employer under {{change.1}} and valued under {{change.2}}. It is not agreed between contractors.\n\nWhere this Contractor becomes aware that a requirement of another package cannot be met because of something delivered under this one, it shall notify the Employer immediately and shall not leave it for that package to discover on arrival. The cost of finding it here is a survey. The cost of finding it there is a module standing on a low-loader."],
],

// ----------------------------------------------------------------- defects
defects: [
["1","The defects period, and the two things it has to cover",
  "The defects liability period is 12 months from the completion of each section, running separately for each, and 24 months for buried drainage and buried services.\n\nSETTLEMENT IS DIFFERENT AND IT IS LONGER. The settlement limits at {{§tolerance}} apply for the whole of the 38-month deployment and the monitoring at {{spec.5}} runs for the whole of it. A settlement exceedance arising from the Contractor's design or workmanship is a defect whenever it appears, and it is not extinguished by the expiry of a 12-month period.\n\nThat is stated plainly because settlement does not appear in twelve months. It appears in year two, in the wet, in one block, and it is the defect this package is most likely to leave behind."],
["2","Response, when the site is occupied",
  "A defect in this package's work, once the village is occupied, is a defect in somebody's home or in the route they walk to work. Response times are:\n\nPRIORITY 1 — anything affecting fire access, hydrant cover, life safety, a live electrical hazard, an open excavation or a total loss of water, power or drainage to an occupied section. Attend within 2 hours, make safe immediately, temporary provision within 4 hours.\nPRIORITY 2 — partial loss of a service, a drainage blockage, a failed lighting circuit on a pedestrian route, standing water on a route or a settlement exceedance. Attend within 24 hours, rectify or provide a temporary solution within 5 working days.\nPRIORITY 3 — everything else. Rectify within 20 working days, or by an agreed programme where the work must wait for weather or for an occupation break.\n\nThese are shorter than the P2 defects response times for Priority 1 and they are meant to be: an open excavation and a struck main cannot wait for a manufacturer's engineer to travel."],
["3","Rectification while people are living here",
  "Rectification is planned work in an occupied village and it is subject to the same regime as construction: the interruption rules at {{occupied.5}}, the noise limits at {{occupied.3}}, the permit to dig at {{hse.3}} and the fire access requirements at {{spec.14}}.\n\nReinstatement after a rectification excavation shall restore the surface, the falls, the slip resistance and the lighting to the original requirement. A patch in a footpath that ponds is a new defect and it will be recorded as one.\n\nWhere a defect is rectified, the as-built record at {{spec.20}} is updated and reissued. An out-of-date record is the second defect."],
["4","Recurrence",
  "The same defect occurring three times in the same location, or the same defect type occurring five times across the site within any 12-month period, requires a root cause investigation and a written report within 15 working days, and a permanent remedy rather than a further repair.\n\nThree blocked gullies in one location is not three blockages. It is a gradient."],
],

// ----------------------------------------------------------------- sustain
sustain: [
["1","Earthworks, which is where the carbon in this package is",
  "The carbon in a civils package is in the concrete, the imported aggregate, and the lorry movements taking material away and bringing material in. The Contractor shall report, monthly:\n\nVolume of material excavated, reused on site, and taken off site, with the destination of what left.\nVolume of material imported, with the source and the haul distance.\nConcrete volume placed, with the cement replacement percentage achieved.\nDiesel consumed on site, by plant and by generation.\nLorry movements to and from site.\n\nWith its tender the Contractor shall state the cut and fill balance it expects to achieve and the cement replacement percentage it will use. A design that balances cut and fill on site is worth more than any other single measure available to this package, and it is a design decision made in the first month."],
["2","Water, waste and the site itself",
  "Water used for dust suppression, wheel washing and testing shall be metered and reported. Water from dewatering shall be treated before discharge and shall not be discharged to a watercourse or to the surface water system without consent.\n\nWaste segregated on site and reported by stream and by destination, with a target of not less than 95% diverted from landfill by weight, excluding hazardous waste and contaminated material.\n\nThe Construction Environmental Management Plan and its seasonal ecological constraints govern and are at {{§appendices}}. Those constraints are a programme risk, not a formality: a nesting season that stops clearance for eleven weeks is eleven weeks, and a tenderer that has not read them has not priced them."],
["3","What is left behind, which is the real measure",
  "This package builds a village that is removed in 38 months. The measure of its sustainability is not the specification of its materials; it is how much of what it built can be taken up, reused or recycled, and how completely the site returns to what it was.\n\nThe Contractor shall state, in its Proposals, which of its permanent works it has designed to be recoverable at the end of the deployment and which it has not, and shall say so honestly. A base that can be lifted and reused is worth more than a base with a low embodied carbon that has to be broken out. {{§demob}} is where that decision is paid for."],
],

// ------------------------------------------------------------------ labour
labour: [
["1","Standards that apply to everybody this Contractor brings",
  "The requirements below apply to every person working on this package, including every subcontractor at every tier and every agency worker, and the Contractor is responsible for them throughout its supply chain.\n\nNo person shall pay any fee to obtain or to keep work on this project. No person's passport or identity document shall be retained by anybody. Every person shall have a written contract in a language they understand, shall be paid not less than the applicable statutory minimum, shall be paid directly into an account in their own name, and shall be paid in full and on time.\n\nWorking hours and rest periods shall comply with the Working Time Regulations 1998. On a remote site where accommodation is provided, the pressure to work excessive hours is structural and the Contractor shall manage it actively rather than rely on individuals to decline.\n\nThe Modern Slavery Act 2015 applies and compliance is evidenced, not asserted. The Employer may audit at any tier without notice."],
["2","Local employment and social value",
  "The social value framework at P2 Appendix 12 applies to this package unamended. The Contractor shall report against it quarterly.\n\nThis package is on site before any other and it is on site longest at the labour-intensive end. Its opportunity for local employment, apprenticeships and local supply chain spend is the largest of any package on the project, and the Employer will hold it to that."],
["3","Conduct in a village that is somebody's home",
  "From month 3 this Contractor's personnel are working where 225 people live. The standards of conduct in the site rules at {{§appendices}} apply in full, to every person, at every tier.\n\nHarassment, intimidation, filming or photographing residents, and entering residential areas without a work reason are removals from site. There is no verbal warning stage for any of them.\n\nThe Contractor shall make it possible for a resident or a worker to report a concern without going through the person they are reporting, and shall tell the Employer within 24 hours of any report received."],
],

// ------------------------------------------------------------------- demob
demob: [
["1","The item everybody forgets to price",
  "In 38 months this village is removed. This package takes up what it laid, removes what it built, and returns the site to the condition the planning consent requires.\n\nIT IS PRICED NOW, at {{§pricing}}, as a separate and identified sum, and it is priced now for two reasons. The first is that a reinstatement obligation left unpriced is an obligation that is argued about in year four by people who were not there. The second is that pricing it now changes the design: a contractor that has to remove its own bases in 38 months designs them differently from one that does not."],
["2","What is removed, and what may be left",
  "The presumption is that everything built under this package is removed: bases, slabs, roads, hardstanding, fencing, external lighting, the generator base and its bunding, and all buried services to a depth of not less than 600 mm below the reinstated ground level.\n\nWHAT MAY BE LEFT is decided by the Employer and not by the Contractor, and it will be decided against the planning consent, the landowner's requirements and the state of the ground. Deep services below 600 mm may be capped, grouted and left in place where the Employer agrees and where they are recorded. Nothing is left because it is difficult to remove.\n\nRECOVERY. Where the Employer elects to relocate the village, this package's role is to release it: bases surveyed, services isolated and capped, access maintained for the removal traffic, and the as-built record at {{spec.20}} issued as the removal information. The Contractor shall state in its Proposals which elements it has designed to be recoverable, per {{sustain.3}}."],
["3","Reinstatement, and the condition it has to reach",
  "The site shall be reinstated to the condition the planning consent and the CEMP require, which as a minimum is: all imported material removed or, where the Employer agrees, incorporated; the ground restored to the pre-development profile within ± 100 mm; the subsoil ripped and decompacted to relieve the compaction 38 months of construction and operation put into it; topsoil replaced to the depth recorded in the pre-development survey; and seeding, planting and habitat works to the CEMP's requirement, within its seasonal windows.\n\nDECOMPACTION IS THE ONE THAT IS SKIPPED. Ground that has carried cranes and haul roads for three years does not recover on its own, and grass sown on compacted ground fails in the first dry summer, which is after everybody has left.\n\nA pre-development condition survey shall be carried out by the Contractor BEFORE it starts work, agreed with the Employer and the landowner, and it is the reference against which reinstatement is measured. Without it the argument in 38 months has no evidence on either side."],
["4","Handover and the end of the deployment",
  "Reinstatement is complete when the Employer, the landowner and the planning authority accept it against the pre-development survey, and not when the Contractor leaves.\n\nAn aftercare period of 24 months applies to planting, habitat and reinstated ground, with replacement of failures and maintenance to the CEMP's requirement. Seeding that fails in the first summer is replaced, and the aftercare is priced at {{§pricing}} as a separate sum for the same reason the reinstatement is."],
],
};
