// P1 — the element-by-element specification and the interface schedule.
module.exports = {

spec: [
["1","Design responsibility, and the Contractor's Proposals",
  "This is a contractor-designed package. The Employer has stated the outcomes: the tolerances at {{§tolerance}}, the loadings at {{spec.4}}, the settlement limits at {{spec.5}}, the discharge rate at {{spec.10}}, the supply characteristics at {{spec.12}} and {{spec.13}}, and the life-safety requirements at {{spec.14}}. The earthworks, pavements, foundations, drainage and services that achieve them are the Contractor's design and the Contractor warrants that they do.\n\nWITH ITS TENDER the Contractor shall submit Contractor's Proposals containing, as a minimum: its ground investigation strategy under {{spec.2}}; its earthworks specification and the class of material it intends to reuse; its pavement design and the subgrade CBR it has assumed; its foundation type for the bases and the settlement prediction that supports {{spec.5}}; its drainage design with the hydraulic calculations and the attenuation volume; its crane hardstanding design under {{spec.7}}; and its programme against the sectional dates at {{§programme}}.\n\nEVERY DEPARTURE from this document shall be listed in a Schedule of Departures with the clause, what is offered instead, the reason, the effect on every other requirement, and the price effect as a plus or a minus. A departure not listed is not accepted, whether or not it is visible on a drawing.\n\nDESIGN SUBMISSION AFTER AWARD. Each design package shall be submitted not less than 4 weeks before the work it covers is due to start, and the Employer shall respond within 10 working days. A package submitted later than that does not create an entitlement to time, and a response not given within 10 working days does. Both are stated because a design approval regime with a period on only one side of it is a delay mechanism.\n\nReview, comment or acceptance by the Employer does not transfer design responsibility, and it applies to an accepted submission as fully as to a commented one."],

["2","Ground investigation, and what the Employer's information is and is not",
  "THE EMPLOYER'S INFORMATION IS FACTUAL. The ground investigation issued at {{§appendices}} is a factual report. It reports what was found in the holes that were sunk. It contains no interpretation, no design parameters and no warranty, and no interpretative report will be issued.\n\nIt is not exhaustive and it is not represented as exhaustive. It was carried out before the layout was fixed and it does not have a hole under every base.\n\nTHE CONTRACTOR SHALL CARRY OUT ITS OWN INVESTIGATION before it completes its design, and shall price it. As a minimum that investigation shall include not fewer than one exploratory hole per accommodation block and one per building, taken to a depth not less than 1.5 times the width of the widest foundation below formation or as its own design requires, whichever is the deeper, together with sufficient in-situ and laboratory testing to establish the parameters its foundation, pavement and drainage designs rely on.\n\nUNFORESEEN CONDITIONS. A physical condition is unforeseen for the purposes of {{change.3}} only if it could not reasonably have been anticipated by an experienced contractor from the factual data provided, a site inspection, and the investigation required above. A condition that the required investigation would have found is not unforeseen, and a condition that no reasonable investigation would have found is not the Contractor's risk.\n\nThat definition is written down for one reason: an undefined ground risk is priced as an invisible allowance by every tenderer, at a different number, and it is settled two years later by argument. This states the line before anybody prices it."],

["3","Earthworks, formation and the testing that proves it",
  "Earthworks shall be carried out and tested to Series 600 of the Specification for Highway Works, or to an equivalent standard the Contractor states in its Proposals and justifies.\n\nMATERIAL. Cut and fill balanced on site so far as the levels permit. The Contractor shall state in its Proposals the classes of material it intends to reuse and the volume it expects to take off site; material removed from site is a cost, a lorry movement and a carbon consequence, and it is reported under {{§sustain}}.\n\nCOMPACTION AND TESTING. Compaction to the method or end-product specification the Contractor's design requires, tested at not fewer than one in-situ density test per 500 m² per layer, with a minimum of three tests per layer in any one area, and every result recorded and issued.\n\nFORMATION. Every formation shall be proof-rolled and inspected before anything is laid on it, and the inspection recorded with photographs and a date. Formation strength shall be verified at not fewer than one test per 200 m² by plate bearing test or dynamic cone penetrometer, and shall achieve the CBR the Contractor's design assumes.\n\nA formation shall not be left open for more than 24 hours without protection, and any formation that has been softened by water, frost or trafficking shall be removed and replaced. It shall not be dried out and re-rolled.\n\nWORKING IN WINTER. Earthworks on this site will run through two winters. The Contractor shall state in its Proposals the weather limits beyond which it will stop, and shall programme accordingly. A programme that assumes an uninterrupted earthworks season is not accepted, and the consequences of stopping are dealt with at {{programme.4}}, not by a claim."],

["4","Bases and slabs, and the loadings they are designed to",
  "THE BASES. 114 module bases, to the tolerances at {{§tolerance}}, each surveyed individually and the survey issued before any module is delivered to it. The foundation type is the Contractor's; the tolerance and the settlement limit are not.\n\nEach base shall be designed for the module reactions P2 states in its Contractor's Proposals. Until those are stated, and for tender purposes, the Contractor shall design for a bedroom module of 3.6 m by 12.0 m with a self-weight not exceeding 14 tonnes, plus the imposed loads below, and shall confirm the design against P2's stated reactions before construction — see {{iface.IF-02}}.\n\nTHE LOADINGS. Imposed floor loads, from Appendix 8 of the P2 Employer's Requirements:\n\nBedrooms — 1.5 kN/m². Circulation and stairs — 2.0 kN/m². Amenity and dining — 3.0 kN/m². Roof, maintenance access only — 0.6 kN/m². Characteristic ground snow load — 0.50 kN/m².\n\nTHE KITCHEN, WHICH THAT APPENDIX DOES NOT COVER. Appendix 8 gives 3.0 kN/m² for 'amenity and dining' and states NO loading for a kitchen production floor. A kitchen production floor is not an amenity floor. The slab to the kitchen and dining building shall therefore be designed for:\n\n5.0 kN/m² uniformly distributed across the production kitchen and wash-up.\n7.5 kN/m² beneath the walk-in chill and freezer rooms and beneath any equipment the P3 Contractor's schedule identifies as exceeding it.\n3.0 kN/m² across dining.\nPoint loads item by item as the P3 fixing schedule states them, confirmed under {{iface.IF-09}}.\n\nThese are the same figures the P3 Employer's Requirements require of the shell. They are stated here as well because this package builds the slab, and because a tenderer that reads Appendix 8, prices a 3.0 kN/m² floor and then finds a cold room standing on it has been failed by the Employer's own documents. Appendix 8 is to be updated to carry these figures; until it is, this clause prevails.\n\nSLAB TOLERANCE. Building slabs to the same level and flatness tolerances as the bases at {{tolerance.1}} and {{tolerance.5}}, and the kitchen slab additionally to the falls the P3 drainage design requires — falls are set here and the P3 Contractor cannot create them later without losing the coving detail."],

["5","Settlement, and the 38 months of monitoring nobody prices",
  "THE LIMITS at {{tolerance.11}}, {{tolerance.12}} and {{tolerance.13}} are: 15 mm total settlement of any base; 5 mm differential between adjacent bases supporting one module; 10 mm differential across any one block.\n\nTHE 5 mm FIGURE IS THE ONE THAT MATTERS. A whole village settling 15 mm uniformly damages nothing. Two bases under one module settling 5 mm apart racks the module, opens the inter-module joint, breaks the service connection at the termination point and produces a leak that is diagnosed as a plumbing defect for six months before anybody measures the ground.\n\nMONITORING IS PART OF THIS PACKAGE AND IT DOES NOT END AT COMPLETION. The Contractor shall install monitoring points to every base and shall monitor and report:\n\nBefore module delivery — a baseline reading of every base, issued with the base survey.\nMonths 1 to 6 after a module is set — monthly.\nMonths 7 to 12 — quarterly.\nMonth 13 to the end of the deployment — six-monthly, and after any exceedance.\n\nEach report states the reading, the movement since baseline, the movement since the last reading, and the computed differential for every adjacent pair and across every block. A report that gives absolute levels without the computed differentials does not discharge this clause, because the differential is the number that matters and nobody calculates it by eye.\n\nEXCEEDANCE. Reaching 60% of any limit triggers an immediate report to the Employer, an increase to monthly monitoring, and the Contractor's assessment of the trend. Reaching a limit triggers remedial action at the Contractor's cost where the cause is within its design or workmanship.\n\nEvery report is issued to the Employer and to P5 under {{iface.IF-14}}, because P5 is the party that will see the door start to bind.\n\nTHIS IS PRICED SEPARATELY at item {{§pricing}} so that it is visible. Monitoring folded into a preliminaries figure is monitoring that stops in month 14 when the site team leaves."],

["6","Setting out, survey and the control network",
  "THE CONTROL NETWORK. The Contractor shall establish and maintain a survey control network, tied to OSGB36 / OSTN15 and to Ordnance Datum Newlyn, with not fewer than 4 permanent stations sited outside the working area and outside the zone of influence of any excavation, each protected and each verifiable.\n\nThe network shall be re-verified at not more than quarterly intervals and after any event that could have disturbed a station, and the verification issued. Every setting-out dimension, every base level and every as-built record in this project is measured from this network, and a network that has moved is a village that is out of position with a full set of records saying it is not.\n\nONE VERSION OF THE TRUTH. P2 sets modules using this network. P3, P4 and P5 all work to what it produced. The Contractor shall issue the network and its verifications to the Employer for reissue to those packages under {{§info}} and {{iface.IF-01}}.\n\nSURVEY OF THE WORK. Every base surveyed individually and the record issued before the module for it is delivered; every service termination surveyed as built; every drainage invert surveyed at every manhole. The tolerances at {{§tolerance}} are demonstrated by survey and not by assertion, and a base is not handed over until its survey has been issued and accepted — {{iface.IF-03}}.\n\nINDEPENDENT CHECK. Not fewer than 10% of bases, selected by the Employer and not by the Contractor, shall be re-surveyed independently at the Contractor's cost. A discrepancy exceeding the tolerance in any checked base triggers a 100% re-survey of that block."],

["7","Crane hardstanding, and the number neither party may assume",
  "THIS IS THE MOST DANGEROUS CLAUSE IN THIS DOCUMENT. 114 modules are lifted over a site where, from month 3, people are asleep in the buildings already erected. A crane that settles under an outrigger during a lift is not a civils defect. It is a fatality.\n\nTHE NUMBER. The bearing pressure imposed by each outrigger, the pad size, the crane configuration and the lift radii are stated by the P2 Contractor as part of its lifting plan. This Contractor designs the hardstanding to them.\n\nNEITHER PARTY MAY ASSUME THE OTHER'S NUMBER. This Contractor shall not design to an assumed outrigger pressure and shall not proceed on a figure taken from a previous project. P2 shall not lift from a hardstanding whose design capacity it has not been given in writing. Where P2's figures are not available at the time this Contractor must build, the Contractor shall design to a stated capacity, shall state that capacity in writing on the as-built record and on a permanent sign at the hardstanding, and P2's lifting plan shall then be checked against it — see {{iface.IF-04}}.\n\nPROOF BEFORE ANY LIFT. Every crane hardstanding shall be proved by plate bearing test to not less than the design bearing pressure, at not fewer than 2 positions per crane position, before the first lift from it, and the results issued to the P2 Contractor and to the Employer. A design calculation is not proof. The test is.\n\nRE-PROOF. The hardstanding shall be re-tested after any period of more than 14 consecutive days on which it has not been used for lifting during the months of November to March, after any flooding of the area, and after any excavation within 5 m of it. Ground that carried a crane in September does not necessarily carry one in February.\n\nRECORD. A register of every hardstanding, its design capacity, its test results and its re-test dates shall be maintained by the Contractor, held on site and issued with the as-built record at {{spec.20}}."],

["8","Roads, hardstanding and pavement design",
  "THE TRAFFIC IS TWO DIFFERENT THINGS AND THE PAVEMENT IS DESIGNED FOR BOTH. Construction traffic includes 114 abnormal load deliveries, the mobile cranes that lift them, and the plant that builds the village. Operational traffic runs for 38 months thereafter: buses at every shift change, delivery vehicles to the kitchen, waste and tanker movements, and the fire service.\n\nThe pavement shall be designed for the whole life without reconstruction between the two phases. A road built to a construction standard and re-laid for operation is two roads, it is built while the village is occupied, and it is not accepted.\n\nGEOMETRY. The Contractor shall design the horizontal and vertical geometry, the swept paths and the turning provision for the largest vehicle that will use each route, and shall state that vehicle. As a minimum the design shall accommodate: the module transporter on the delivery route to every block; a 12 m rigid refuse vehicle to every bin store; a tanker to the grease separator position without entering the village or crossing a footpath, per {{spec.10}}; the bus specified by P5 at the transport pick-up, turning without reversing; the furniture delivery vehicle P4 states at {{iface.IF-11}}; and the fire appliance to {{spec.14}}.\n\nNO REVERSING AT THE PICK-UP. A bus that reverses in a village where 225 people are walking to shift in the dark is a design that has been left to the operator to manage. The turning circle is sized here.\n\nSURFACES. Finished levels to {{tolerance.9}}. All surfaces laid to falls that drain to the drainage system and not to a low point that ponds; there shall be no location on any road, footpath, hardstanding or parking area where standing water can accumulate. Ponding in front of a delivery bay is the one that stops the job.\n\nMAINTENANCE HANDOVER. The Contractor shall state the pavement's residual design life at completion and the maintenance regime it requires, and shall issue both to P5 under {{iface.IF-13}}. P5 prices the operational maintenance from it."],

["9","Foul drainage, and why domestic loading is the wrong basis",
  "THE LOADING. The system shall be sized for the peak occupancy at Appendix 6 of the P2 Employer's Requirements — 225 residents — using a CONGESTED-USE discharge unit loading and not a domestic one.\n\nWHY. In a domestic building people get up at different times. In this village 124 residents leave for day shift and 101 come off nights inside the same 40 minutes, twice a day, every day, for 38 months. Showers, WCs and the laundry all run in the same window. A system designed on domestic simultaneity is a system that surcharges twice a day and is reported as a smell.\n\nThe Contractor shall state in its Proposals the discharge unit loading and the simultaneity it has used, and the calculation for the peak flow at the outfall.\n\nGRADIENTS. Every run laid within 10% of its design gradient and never flatter than the minimum self-cleansing gradient for the pipe size — {{tolerance.10}}. Invert levels surveyed at every manhole and issued, {{tolerance.8}}.\n\nTERMINATION. One foul termination per block, and one to the kitchen under {{iface.IF-08}}, at the position and invert on the coordinated drawing, with the invert not less than 1.20 m below the module finished floor level unless the Contractor's design demonstrates otherwise and P2 accepts it in writing. That figure is carried in P2 Appendix 8 as an assumption TO BE CONFIRMED; this clause confirms it, and the appendix is to be updated to record that it is now a requirement and not an assumption. P2 designs its below-floor drainage from this figure and cannot change it after manufacture — {{iface.IF-05}}.\n\nPHASED CONNECTION. Blocks are occupied in four sections at months 3, 6, 9 and 12. The system shall work at 65 beds and at 225 beds. A drainage system sized for 225 and laid at the flat gradients that a full flow scours can silt during the nine months it is running at a third of it, and the Contractor shall state how its design deals with that.\n\nADOPTION OR PRIVATE. The Contractor shall state whether it intends the system to be offered for adoption or to remain private, and shall price accordingly. An adoptable standard applied late is a redesign; a private system handed to P5 is an operating cost P5 has to have been told about."],

["10","Surface water, attenuation, and the chambers somebody has to empty",
  "DISCHARGE. Surface water discharge from the site is restricted to 5 litres per second per hectare. That is a planning condition and it is not negotiable by design.\n\nATTENUATION. Storage sized for the 1 in 100 year event with a 40% allowance for climate change, with no flooding of any building, road, footpath or hardstanding in that event, and no flooding of any adjoining land at any return period that the pre-development site did not flood. The Contractor shall submit the calculation, the storage volume and the assumed rainfall data with its Proposals.\n\nTREATMENT. Runoff from the parking, the roads and the fuel storage area shall pass through appropriate treatment before discharge, sized on the SuDS treatment index for the surface it drains. The generator fuel storage bund at {{spec.12}} shall not discharge to the surface water system at all.\n\nTHE CHAMBERS THAT HAVE TO BE EMPTIED. The grease separator serving the kitchen is provided under P3. Its chamber, its access and its connection are provided here, and they shall be sited so that a tanker can empty it WITHOUT ENTERING THE VILLAGE AND WITHOUT CROSSING A FOOTPATH — from a hardstanding on the perimeter road, with a hose run not exceeding 25 m and a level difference within the lift capability the P3 Contractor states.\n\nThe same applies to every interceptor, every silt trap and every attenuation chamber that requires periodic emptying: each shall be reachable, from a surface that carries the vehicle, without closing a route the village depends on. The Contractor shall mark every such chamber on a maintenance access drawing and issue it to P5 under {{iface.IF-13}}.\n\nA separator that can only be emptied by driving a tanker between two occupied blocks is a separator that is emptied late, and a grease separator that is emptied late is a blocked drain in a kitchen serving 490 covers a day."],

["11","Footpaths, external levels and lighting",
  "THE PERSON THIS CLAUSE IS WRITTEN FOR is walking from a bedroom block to the transport pick-up at 05:00 in January, in the dark, in the wet, in work boots, carrying a bag, having slept badly. Every requirement below exists because of them.\n\nROUTES. A surfaced, drained, lit footpath between every accommodation block and the amenity, kitchen and reception buildings, and to the transport pick-up and every assembly point. Step-free throughout, with gradients not exceeding 1 in 20 on any route and 1 in 12 over a length not exceeding 5 m where the site levels make 1 in 20 impossible, with a level landing at each end.\n\nSURFACE. Slip resistance not less than PTV 36 wet on every footpath, ramp and external step, tested on the installed surface and not certified from a data sheet. Cross-fall between 1 in 40 and 1 in 60 — enough to drain, not enough to trip.\n\nTHRESHOLDS. External finished level at every external door within {{tolerance.4}}: from 15 mm below the module finished floor level to level with it, never above. P2 clause 4.5 requires a threshold not exceeding 15 mm and it can only achieve it if this package's finished level is right. This is the tolerance most often missed and it is missed at the last moment, when the paving is laid to the ground rather than to the building.\n\nLIGHTING. Maintained average horizontal illuminance, measured on the installed and aged installation:\n\nFootpaths and pedestrian routes — 10 lux average, 3 lux minimum, uniformity not less than 0.25.\nRoads and car parking — 10 lux average, 2.5 lux minimum.\nTransport pick-up and assembly points — 20 lux average, 5 lux minimum.\nBuilding entrances — 30 lux at the door.\n\nAND NOT INTO A BEDROOM WINDOW. All external luminaires full cut-off, with upward light ratio zero and with vertical illuminance at any bedroom window not exceeding 5 lux between 23:00 and 07:00, measured at the window in the plane of the glass. Half of this village sleeps during the day and the other half sleeps at night; there is no hour at which lighting a bedroom window is acceptable.\n\nThese two requirements pull against each other. Both are stated, both are measured at commissioning under {{spec.18}}, and the Contractor resolves them by design rather than by choosing one."],

["12","Electrical supply, earthing and the standby set",
  "SUPPLY TO EACH BLOCK. 400/230 V, 50 Hz, three phase and neutral, TN-S earthing, at not less than 250 kVA per block at the termination point, plus a dedicated supply to the kitchen at not less than 200 kVA.\n\nThose are the figures P2 and P3 design to. If the Contractor's design or the distribution network operator's connection cannot achieve them, the Contractor shall say so IN ITS TENDER and not after those packages have been let.\n\nEARTHING AND FAULT LEVEL. The earthing arrangement, the prospective fault current and the external earth fault loop impedance at every termination point shall be established by the Contractor by measurement and confirmed in writing, not assumed from the connection offer. P2's protective device discrimination depends on them — {{iface.IF-06}}.\n\nSTANDBY GENERATION. One 500 kVA set with its base, acoustic enclosure, fuel storage, bund and automatic changeover, serving the life-safety and essential loads that P2 and P5 identify and no others.\n\nAUTOMATIC CHANGEOVER within 15 seconds of loss of supply, on load, demonstrated at commissioning and thereafter exercised monthly by P5 under {{iface.IF-13}}.\nFUEL STORAGE for not less than 72 hours at the essential load, bunded to 110% of the tank capacity, with the bund not discharging to any drainage system.\nNOISE from the set, running, not exceeding 40 dB LAeq at the nearest bedroom window at night. The set will be run for a monthly test for 38 months, and a test that wakes the night shift is a test that gets skipped.\nFUEL SECURITY. Locked fill point, contents monitored and alarmed, and the theft risk treated as real. Diesel on a remote site disappears.\n\nWHAT THIS CLAUSE DOES NOT DO is decide which circuits are essential. P2 and P5 state them; this package sizes, provides and proves the set that supports them."],

["13","Water supply, and a village that fills up in stages",
  "AT EVERY TERMINATION POINT — 8 blocks plus the kitchen — not less than 2.0 bar dynamic pressure at a flow of 1.5 litres per second, with the static pressure not exceeding 5 bar.\n\nBoth ends of that range are requirements. Below 2.0 bar the showers in the top rooms fail at shift change. Above 5 bar the fittings P2 has specified leak, and they leak in a bedroom above another bedroom.\n\nBOOSTING AND STORAGE. Where the incoming supply cannot achieve the duty, the Contractor shall provide boosting and storage, sized on the peak demand at the peak occupancy with the same congested-use simultaneity as {{spec.9}}, and shall state the storage volume and the turnover.\n\nSTAGNATION, WHICH IS THE RISK NOBODY PRICES. The village is occupied in four stages, at months 3, 6, 9 and 12. A distribution main sized for 225 residents and serving 65 of them for nine months has a turnover long enough for Legionella to establish, and it establishes in the part of the system that is not yet in use.\n\nThe Contractor shall therefore: design the network so that sections not yet occupied can be isolated and drained rather than left charged and static; state a flushing regime for anything that remains charged; provide sampling points; and hand the regime to P5 with the written record of what was flushed and when. A system commissioned in month 3 and left standing to month 12 is recommissioned before occupation, not merely flushed.\n\nThe Contractor shall carry out chlorination, sampling and bacteriological testing to a satisfactory result at every stage of occupation, not only at practical completion, and shall issue each certificate before the section it covers is occupied.\n\nFIRE MAIN. Where the hydrant supply at {{spec.14}} is taken from the same source, the Contractor shall demonstrate that hydrant flow does not reduce the domestic supply below the duty above, and shall state the effect."],

["14","Fire appliance access and hydrants, available from the FIRST occupation",
  "PEOPLE SLEEP IN THIS VILLAGE FROM MONTH 3. The fire service does not wait for the last block, and neither does this clause.\n\nACCESS. Fire service vehicle access to within 45 m of every point on every storey of every building, on a route designed for an appliance of not less than 12.5 tonnes gross, with a carriageway width of not less than 3.7 m, a gate width of not less than 3.1 m, headroom of not less than 3.7 m, and a turning facility that does not require reversing more than 20 m.\n\nHYDRANTS. Hydrants sited so that no point of any building is more than 90 m from one, each capable of not less than 1,500 litres per minute at 1.7 bar running pressure, tested and the result recorded for each hydrant individually.\n\nAVAILABLE FROM FIRST OCCUPATION, WHICH IS THE WHOLE POINT. The access route and the hydrants serving each section shall be complete, tested, signed and available BEFORE that section is occupied, and shall remain available throughout construction of the sections that follow. A route that is complete but is being used as a laydown, or a hydrant that is buried under a spoil heap, is not available.\n\nThe Contractor shall issue, before each sectional occupation, a fire access and hydrant availability statement covering the section being occupied and every section already occupied, and shall reissue it whenever the construction arrangement changes. The Employer will not accept occupation without it.\n\nMAINTAINED DURING CONSTRUCTION. This is the requirement that gets broken, and it gets broken by the package's own works: a trench across the only access road, a crane standing on it, a delivery parked on it. {{§occupied}} states how it is controlled, and no excavation, closure or obstruction of a fire access route is permitted without a documented alternative route in place first.\n\nSIGNAGE AND RECORD. Every hydrant marked to BS 3251 and recorded on the fire service drawing issued to the local fire and rescue service and to P5."],

["15","Data and communications ducting",
  "Duct and draw rope from the incoming point to every block termination point and to the kitchen, with not fewer than 2 single-mode fibre pairs per block terminated and tested, and spare duct capacity of not less than one spare way per route.\n\nDucts shall be proved by mandrel and by rodding after backfill and before acceptance, and every duct route recorded on the as-built survey at {{spec.20}}. A duct that is collapsed is discovered by the cabling contractor with the village occupied, and the route it follows is under a road by then.\n\nP5 operates the network and P2 terminates inside the building. This package provides the containment and the termination point, and nothing beyond it — {{iface.IF-07}}."],

["16","Fencing, gates and the segregation line",
  "THE VILLAGE BOUNDARY. Fenced, gated and controlled, with the gatehouse position and the vehicle and pedestrian gates as shown on NR-TW-VIL-0201. Vehicle gates sized for the largest vehicle at {{spec.8}} and for the fire appliance at {{spec.14}}, and openable manually on loss of power.\n\nTHE SEGREGATION LINE. A PHYSICAL line between the occupied village and the live construction site, not a notional one and not a line of cones. Continuous, of a height not less than 2.0 m, with no gap and no informal crossing point, and with defined crossings that are controlled.\n\nIt moves as the village grows. Each section brought into occupation at months 3, 6, 9 and 12 changes where the line runs, and each move is a planned operation with a drawing, a date and a check that the fire access at {{spec.14}} still works after it. {{§occupied}} states the regime.\n\nA segregation line that people walk around is worse than no line, because everybody assumes it is working. The Contractor shall inspect it weekly, record the inspection, and close any informal crossing within 24 hours of finding it."],

["17","Materials, testing and rejection",
  "MATERIALS. All materials to the relevant British or European standard, CE or UKCA marked where the standard requires it, and declared in the Contractor's Proposals where a proprietary product is proposed in place of a standard specification.\n\nTESTING. The Contractor shall submit an Inspection and Test Plan before work starts on each element, stating for every test: what is tested, the standard, the frequency, who witnesses it, the acceptance criterion, and what happens on a failure. Work carried out on an element with no accepted ITP is at the Contractor's risk of removal.\n\nEach Inspection and Test Plan shall be submitted not less than 10 working days before work starts on that element, and the Employer shall respond within 5 working days.\n\nHOLD POINTS, which shall not be passed without the Employer's written release: formation before any layer is laid on it; base reinforcement and level before concrete; every crane hardstanding before the first lift; every drainage run before backfill; every buried service before backfill.\n\nThe Contractor shall give not less than 24 hours' notice of a hold point, and the Employer shall attend and release or reject it within 24 hours of the notified time. A hold point not released or rejected within that period is deemed released, because a hold point with no time limit on the Employer is a delay the Contractor cannot price.\n\nA hold point passed without release is not cured by a subsequent test. The work is opened up at the Contractor's cost if the Employer requires it, and the Employer's decision on whether to require it is not a reason to keep working.\n\nREJECTION. Work outside a tolerance at {{§tolerance}} is rejected and corrected before the package that depends on it arrives. It is not accepted subject to a concession, because there is no concession available: the module is already built to the dimension. Where correction is genuinely impossible the Contractor shall notify under {{§change}} immediately, so that the package that will find it can be told before it arrives, rather than after."],

["18","Commissioning, testing and proving the services",
  "Every service provided under this package shall be proved at its termination point, individually, by measurement, and the result recorded against that termination point by reference.\n\nWATER — dynamic pressure and flow at each termination, chlorination and bacteriological certificates, per {{spec.13}}.\nELECTRICAL — supply characteristics, earth fault loop impedance and prospective fault current at each termination, and the full test certificate, per {{spec.12}}.\nSTANDBY — changeover on load within 15 seconds, run at full essential load for not less than 4 hours, fuel consumption measured, and noise measured at the nearest bedroom window.\nFOUL AND SURFACE WATER — CCTV survey of every run, an air or water test to the relevant standard, and the invert survey at every manhole.\nATTENUATION AND FLOW CONTROL — the flow control device proved to discharge at the design rate, by measurement.\nHYDRANTS — flow and pressure at each hydrant individually, per {{spec.14}}.\nLIGHTING — illuminance measured on a grid at each area type, and vertical illuminance at the sample bedroom windows the Employer selects, per {{spec.11}}.\n\nA commissioning record that states an installation is satisfactory without individual results against individual references will be rejected. The reason is not bureaucratic: the fault is always at one termination, and a record that averages across nine of them cannot find it.\n\nSECTIONAL COMMISSIONING. Everything serving a section is commissioned and certified before that section is occupied, at months 3, 6, 9 and 12, and not at practical completion."],

["19","Contamination, and when the ground is not what it was said to be",
  "The factual report at {{§appendices}} records what was found. Where the Contractor encounters contamination, made ground, buried structures, asbestos or any material requiring special handling that is not reasonably inferable from that report and from the investigation required at {{spec.2}}, it shall:\n\nSTOP work in the affected area immediately and secure it.\nNOTIFY the Employer within 4 hours, in writing, with photographs, the location surveyed, and its immediate assessment.\nNOT REMOVE, cover, mix or dispose of the material until the Employer has responded, except where health, safety or the environment requires immediate action, in which case it shall act and report what it did.\n\nThe commercial treatment is at {{change.3}}. The reason the notification duty is separate from the commercial one is that the two get confused: a contractor that believes notifying is claiming will delay notifying until it has priced it, and by then the material has been moved.\n\nDISPOSAL. All material leaving site classified, documented and disposed of lawfully, with duty of care documentation issued to the Employer. Reported under {{§sustain}} by tonnage and destination."],

["20","The as-built survey, and the record the village is relocated with",
  "This package produces a record that outlives it by 38 months and is then used to take the village apart. It is a deliverable in its own right and it is priced as one.\n\nWHAT IS RECORDED. Every base — position, level, foundation type and depth, and its settlement baseline. Every service run — line, level, size, material and depth. Every termination point — position, invert, and the characteristic proved at {{spec.18}}. Every chamber, manhole and invert. Every duct route including spare ways. Every crane hardstanding, its design capacity and its test record. The survey control network and its verifications.\n\nFORMAT. Coordinated to the network at {{spec.6}}, issued as data in the schema at P2 Appendix 11 and as drawings, with every asset carrying the identifier the asset information requirements specify. A PDF drawing set alone does not discharge this clause.\n\nWHEN. Progressively, section by section, issued within 4 weeks of each sectional completion, and not held to the end. A record issued once at the end is a record compiled from memory.\n\nWHY IT MATTERS TWICE. In 38 months this village is removed under {{§demob}} and, if the Employer elects, relocated. What is dug up, what is left, what is reused and what the reinstatement has to achieve are all read off this record. And for the whole of the 38 months in between, every excavation P5 makes in this site is planned from it. A wrong depth on this record is a struck service in year three."],
],

// [ref, with, what crosses, who certifies, when]
ifaces: [
["IF-01","P2 Modular Accommodation","THE SETTING-OUT AND THE SURVEY CONTROL NETWORK at {{spec.6}}. One network, established here, used by everyone","This Contractor issues; the Employer reissues to P2, P3 and P5","Before P2 sets the first module"],
["IF-02","P2 Modular Accommodation","Module reactions, self-weights and base bearing requirements, against which the base design at {{spec.4}} is confirmed","P2 states them in writing; this Contractor confirms its design against them","Before this Contractor constructs the first base"],
["IF-03","P2 Modular Accommodation","The 114 base surveys, each demonstrating the tolerances at {{§tolerance}}","This Contractor issues per base; P2 accepts in writing before delivering a module to it","Base by base, before each delivery"],
["IF-04","P2 Modular Accommodation","OUTRIGGER BEARING PRESSURE, pad size, crane configuration and lift radii, and the hardstanding capacity and plate bearing results against them","P2 states the pressures in its lifting plan; this Contractor states and proves the capacity. Neither assumes the other","Before the first lift from each hardstanding — {{spec.7}}"],
["IF-05","P2 Modular Accommodation","Service termination points: position, foul invert, water duty, electrical characteristics, data","Joint coordination drawing signed by both before either orders material","Before P2 commences manufacture"],
["IF-06","P2 Modular Accommodation","Earthing arrangement, prospective fault current and earth fault loop impedance at each termination","This Contractor measures and confirms; P2's discrimination study is based on it","Before P2 completes its electrical design"],
["IF-07","P2 Modular Accommodation","External door threshold levels — {{tolerance.4}}, the −15 mm to 0 mm band that makes P2 clause 4.5 achievable","Survey by this Contractor at every external door after external works","Before each sectional completion"],
["IF-08","P3 Kitchen","External drainage connection at the invert, and the kitchen water and electrical supplies at {{spec.13}} and {{spec.12}}","Joint before this Contractor lays external drainage","Before drainage commences"],
["IF-09","P3 Kitchen","Kitchen slab loadings — 5.0 / 7.5 / 3.0 kN/m² and the point loads on the P3 fixing schedule","P3 states the schedule; this Contractor confirms the slab design against it","Not later than the P3 shell freeze date"],
["IF-10","P3 Kitchen","GREASE SEPARATOR chamber, position, access and tanker route — emptied without entering the village or crossing a footpath, {{spec.10}}","Joint drawing signed by both, and by P5 who will operate it","Before drainage commences"],
["IF-11","P4 Furniture","Delivery access, unloading position and the route into each building for furniture deliveries during sectional occupation","This Contractor states the available routes; P4 confirms they suit its vehicle","4 weeks before each sectional occupation"],
["IF-12","P5 FM and Operation","The transport pick-up, its turning provision and the bus it is sized for at {{spec.8}}","P5 states the vehicle; this Contractor designs to it","Before the external works design is completed"],
["IF-13","P5 FM and Operation","THE OPERATING HANDOVER: maintenance access drawing, chamber emptying schedule, pavement residual life and maintenance regime, generator exercise regime, water flushing and sampling regime, gritting routes","P5 acknowledges receipt against a checklist, item by item","4 weeks before each sectional occupation"],
["IF-14","P5 FM and Operation","Settlement monitoring reports at {{spec.5}} throughout the deployment, and any exceedance","This Contractor issues; P5 and the Employer both receive","Per the monitoring frequency at {{spec.5}}"],
["IF-15","Employer / statutory undertakers","The DNO connection, the water undertaker's connection, the discharge consent and the adoption position at {{spec.9}}","The Employer procures the connections; this Contractor designs and applies","Per the programme at {{§programme}}"],
["IF-16","Employer / fire and rescue service","Fire access routes, hydrant positions, flow test results and the availability statement before each sectional occupation","This Contractor issues; the Employer submits to the fire and rescue service","Before each sectional occupation — {{spec.14}}"],
],
};
