// P3 — pricing, and the twenty-five questions answered.
module.exports = {
pricing: [
["1","How this is priced",
  "The tender is priced against the schedule below in its issued structure. A tenderer who alters it produces a return that cannot be compared with the others and it will be marked accordingly.\n\nRates are inclusive of everything necessary to complete the item — labour, materials, plant, temporary works, supervision, commissioning, testing, training, overheads and profit — except where an item is stated to be priced separately. A rate left blank is a rate of nil and the item is deemed included elsewhere; a tenderer intending to exclude it lists it as a departure rather than leaving it empty.\n\nQuantities are firm. The demand at {{§demand}} and the areas at {{§areas}} are the Employer's and are not remeasured."],
],
// [item, description, basis, note]
schedule: [
["A","DESIGN AND THE FREEZE","",""],
["A1","Kitchen design, layout, and the Contractor's Proposals","Lump sum","Including the 1:50 layout, the flow demonstration and the equipment schedule"],
["A2","Mechanical, electrical, drainage and ventilation design of the fit-out","Lump sum",""],
["A3","The freeze register information at {{§freeze}} — loadings, penetrations, routes, heights","Lump sum","PRICED SEPARATELY because it is delivered months before mobilisation and is the critical deliverable of this package"],
["A4","Noise assessment, extract calculation and the energy declaration","Lump sum","{{spec.16}}, {{§sustain}}"],
["B","STORES AND REFRIGERATION","",""],
["B1","Walk-in chill room, complete and commissioned","Lump sum","EQ-02"],
["B2","Walk-in freezer room, complete and commissioned","Lump sum","EQ-03"],
["B3","Dry goods store fit-out and shelving","Lump sum","EQ-04"],
["B4","Temperature monitoring, logging and alarm to the Operator","Lump sum","EQ-06"],
["C","PREPARATION AND COOKING","",""],
["C1","Preparation sections, benching, sinks and hand wash provision","Lump sum","EQ-07 to EQ-10"],
["C2","Primary cooking capacity to the duty at EQ-11","Lump sum","State every item selected and the duty calculation behind it"],
["C3","Regeneration, boiling, grilling and frying capacity","Lump sum","EQ-12 to EQ-14"],
["C4","Hot holding and blast chilling","Lump sum","EQ-16, EQ-17"],
["D","SERVERY AND DINING","",""],
["D1","Servery, two independent lines","Lump sum","EQ-18"],
["D2","Packed-meal collection point","Lump sum","EQ-19 — separate from the hot line"],
["D3","Beverage provision, 24 hours","Lump sum","EQ-20"],
["D4","Dining furniture, 100 covers","Rate per cover","EQ-21. IN THIS PACKAGE, not P4 — see IF-07"],
["D5","Dining and servery finishes","m²","EQ-22"],
["E","WASH-UP","",""],
["E1","Dish wash to the duty at EQ-23","Lump sum",""],
["E2","Pot wash, separate","Lump sum","EQ-24"],
["E3","Water softening where required","Lump sum","EQ-26. Price nil if the hardness does not require it, and say so"],
["F","VENTILATION, FIRE AND SERVICES","",""],
["F1","Canopies, extract ductwork and roof termination","Lump sum","EQ-27, {{spec.13}}"],
["F2","Make-up air plant, tempered","Lump sum","EQ-28"],
["F3","Fire suppression to LPS 1223, with power isolation","Lump sum","EQ-31"],
["F4","Extract and cooking-power shutdown interface with the P2 fire alarm","Lump sum","EQ-32, IF-05. Demonstrated, not described"],
["F5","Hot and cold water services within the fit-out","Lump sum","EQ-33, {{spec.15}}"],
["F6","Drainage, gullies and floor falls within the building","Lump sum","EQ-34, {{spec.11}}"],
["F7","Grease separator and its access","Lump sum","EQ-35"],
["F8","Electrical installation, distribution and emergency isolation","Lump sum","EQ-36, EQ-38, {{spec.10}}"],
["F9","Sub-metering to the village management system","Lump sum","EQ-37"],
["G","FINISHES AND BUILDER'S WORK","",""],
["G1","Kitchen and wash-up floor, wall and ceiling finishes","m²","{{spec.4}}"],
["G2","Builder's work in connection, and fixings to the modular structure","Lump sum","{{spec.4}}. Excludes anything P2 provides under the freeze register"],
["H","COMMISSIONING, THE TEST MEAL AND HANDOVER","",""],
["H1","Commissioning, with individual results for every measurement","Lump sum","{{§performance}}"],
["H2","THE TEST MEAL — 124 covers through the servery, and a full wash-up cycle","Lump sum","{{spec.7}}. Priced separately because it is a distinct event with the Operator's staff"],
["H3","Handover deliverables, asset data and O&M","Lump sum","{{§handover}}"],
["H4","Training for P5 — 2 recorded sessions","Lump sum","{{§handover}}"],
["J","SPARES AND CONSUMABLES — PRICED SEPARATELY","",""],
["J1","12 months' consumables from handover","Lump sum","Stated separately so the Employer can decline it knowingly"],
["J2","Critical spares holding, criticality 1 assets","Lump sum",""],
["K","OPTIONS — PRICED, NOT IN THE LUMP SUM","",""],
["K1","Heat recovery from the extract","Lump sum","{{sustain.2}}. State the payback over the remaining term"],
["K2","Gas installation, if offered as a departure","Lump sum","{{spec.12}}. Price the interlock, detection, proving and the fire strategy consequence with it"],
["L","RATES FOR THE VALUATION OF CHANGE","",""],
["L1","All-in hourly rate by trade and grade","Rate","Fixed for the contract period"],
["L2","Percentage addition for overhead","%",""],
["L3","Percentage addition for profit","%",""],
["L4","Percentage addition on sub-contracted work","%",""],
["M","DEPARTURES","",""],
["M1","Each departure, listed and priced individually","Each","{{spec.1}}. A departure not listed is not accepted"],
],

// [ref, the finding against P2 Rev A, where this document answers it]
register: [
["G01","No design responsibility matrix or Contractor's Proposals mechanism","{{spec.1}}: the basis is stated, the Contractor's Proposals and Schedule of Departures are required with the tender, and review is stated not to transfer responsibility"],
["G02","Prescriptive and performance specification mixed","Every one of the 38 equipment lines carries an E or C code. 25 prescribed, 13 contractor-designed — and clause 1.2 states honestly WHY a kitchen carries more prescription than a service contract, in three named groups, rather than claiming to prescribe sparingly and then not doing so"],
["G03","No stated failure mode","{{spec.12}}: the extract and cooking power SHUT DOWN on fire alarm unless the fire strategy requires otherwise in writing; no fire damper in a grease duct; suppression isolates power on discharge; and the kitchen is electric so the gas interlock question does not arise 40 m from where people sleep"],
["G04","No damages or delay mechanism","{{programme.3}}: £145 per bed per day on the same basis as the P2 sectional rate, because it is the same loss, with the build-up referenced rather than restated so there is one version of it"],
["G05","No defects regime","{{§defects}}: 12 months, the systemic-defect rule, three priorities with times, and the access constraint of a kitchen serving five periods a day"],
["G06","No temporary works regime","{{hse.4}}: a lifting and handling plan for every item over 100 kg, covering the floor loading DURING the move, which is a point load on a manufactured floor and not the loading in service"],
["G07","Relocation imposed without a requirement","{{§relocation}}: what is demountable, what is consumed by removal with a budget rate for each, the expected condition after 38 months, and the manufacturer's position on re-commissioning"],
["G08","No information requirements","{{§info}}: the P2 schema rather than a new one, the CDE, the model origin agreed with P2, and criticality ratings that become P5's Priority 1 list"],
["G09","No site constraints","{{hse.1}} and {{hse.2}}: the live site, and working 40 m from people who are asleep at every hour"],
["G10","No electrical supply characteristics","{{spec.10}} and EQ-36: a dedicated supply, stated connected load and maximum demand, the consequence of exceeding them, and refrigeration on the standby supply"],
["G11","No water supply characteristics","{{spec.15}} and EQ-33: the duty, independence from the blocks' demand, hardness to be established, Fluid Category 5 backflow protection and separate metering"],
["G12","No evacuation or alarm strategy","{{spec.12}} and IF-05: the cause and effect interface with P2, demonstrated jointly at commissioning rather than described"],
["G13","A figure that was tight for the technology","The extract floor of 5.0 m³/s and the pressure duty at EQ-28 are stated as floors the Contractor calculates from, not as answers — and the pressure differential is measured with everything running, which is the condition that finds the problem"],
["G14","No loading or serviceability criteria","{{freeze.3}}: 5.0 kN/m² production, 7.5 kN/m² under cold rooms, point loads item by item — AND the statement that P2 Appendix 8 does not currently carry them, which is a fault in the Employer's own pack written down rather than left for a tenderer to find"],
["G15","No change control","{{§change}}: who may instruct, the valuation order, and the rule that a request from the Operator is not an instruction"],
["G16","Float ownership not stated","{{§programme}}: the Contractor shows the float it holds against the first meal service, and the freeze date is named as the earlier and less familiar of the two governing dates"],
["G17","No sustainability requirement","{{§sustain}}: a predicted consumption declaration evaluated at tender and checkable against the sub-metering in operation, whole-life equipment selection, food waste provision, and heat recovery priced as an option"],
["G18","No testing regime for the thing that fails","{{spec.7}}: THE TEST MEAL. 124 covers through the servery followed by a full wash-up, witnessed. Every other test is of a component; this one is of the kitchen"],
["G19","Missing drainage detail","{{spec.11}}: falls, gullies, rodding access, and a grease separator sited so it can be emptied without entering the kitchen — which is the commonest cause of a kitchen closing unexpectedly"],
["G20","No obsolescence or support period","{{defects.3}}: stated spares availability, end-of-life notice, open or proprietary controls, deployment plus 24 months, and no item whose function dies with a subscription"],
["G21","No inspection checklist","{{§performance}}: 22 criteria each with the method of verification, and the test meal as the acceptance event"],
["G22","No definitions","{{§definitions}}: 13 terms, including the E and C basis codes, the freeze date, and what a cover is — because a cover is the only unit that sizes a kitchen"],
["G23","No ethical labour requirement","{{§labour}}: the Employer Pays Principle, flow-down unamended, private worker interviews, and disclosure of the place of manufacture — catering equipment is made globally and an undisclosed factory cannot be audited"],
["G24","Clauses with no measurable requirement","Every performance criterion carries a figure and a verification method; every equipment duty is stated in covers, minutes, temperature or rate; the areas sum to the 610 m² shell exactly"],
["G25","No security requirement","{{spec.18}}: no delivery before the building is lockable, sealed deliveries with recorded seal numbers, secure storage at the Contractor's cost, and key control from first delivery rather than from handover"],
],
};
