// P4 — pricing, and the twenty-five questions answered.
module.exports = {

pricing: [
["1","How this is priced",
  "The tender is priced against the schedule below in its issued structure. A tenderer who alters it produces a return that cannot be compared with the others and it will be marked accordingly.\n\nRATES ARE PER ROOM OR PER ITEM, DELIVERED, ASSEMBLED, IN POSITION AND ACCEPTED. They include delivery, storage, assembly, installation, packaging removal, the room acceptance check, the inventory, overheads and profit. A rate that covers supply only, with installation elsewhere, is not comparable with the others and will not be normalised for the tenderer.\n\nA rate left blank is a rate of nil and the item is deemed included elsewhere; a tenderer intending to exclude something lists it as a departure under {{spec.1}} rather than leaving a cell empty.\n\nQUANTITIES ARE FIRM: 225 rooms — 199 RT-01, 12 RT-02, 14 RT-03 — and the areas at {{§rooms}}. They are the Employer's and they are not remeasured."],
["2","What is priced separately, and why",
  "Four items are pulled out of the room rate because folding them in makes them invisible, and an invisible obligation is one that is performed badly or not at all.\n\nTHE SAMPLE ROOMS at {{spec.13}} — three fully furnished rooms, on site, before any bulk delivery. It is a real cost incurred months early and it is the single most valuable quality control event in this package.\n\nTHE ATTRITION STOCK at {{spec.12}} — because it is delivered at the first handover and must be visible as a quantity, not absorbed into a rate where it quietly shrinks.\n\nTHE RT-02 LAYOUT AND VERIFICATION at {{spec.6}} — twelve rooms measured individually with the furniture in place, and the record issued. It is an hour a room and it is the difference between twelve compliant rooms and twelve that are not.\n\nTHE PACKAGING REMOVAL at {{spec.15}} — because it is a daily logistics operation for the length of the installation, not a line in the preliminaries."],
["3","Payment",
  "Payment is by application at each sectional acceptance, valued against this schedule, and conditional on: every room in that section having passed the room acceptance check at {{spec.13}}; the inventory issued and acknowledged by P5; and the asset data for that section issued within 2 weeks per {{info.2}}.\n\nNO PAYMENT IS MADE FOR FURNITURE DELIVERED BUT NOT INSTALLED AND ACCEPTED. Material on site is not progress in this package: a room full of boxes is a room that cannot be occupied.\n\nRetention is released against sectional acceptance and at the end of the defects period for each section."],
],

// [item, description, basis, note]
schedule: [
["A","PRE-CONTRACT AND SAMPLES","",""],
["A1","Contractor's Proposals, layouts and the access statement","Lump sum","{{spec.1}}. Including the three-largest-item check at {{spec.8}}"],
["A2","Dimensional coordination with P2 and confirmation against the Common Schedule","Lump sum","{{§boundary}}. The deliverable that sits ahead of every other one"],
["A3","THE SAMPLE ROOMS — one RT-01, one RT-02, one RT-03, furnished on site","Lump sum","PRICED SEPARATELY. {{spec.13}}. Condition precedent to bulk delivery"],
["A4","Test evidence, fire classifications and the fire engineer's confirmation","Lump sum","{{spec.3}} and {{iface.IF-12}}"],
["B","BEDROOM FURNITURE","",""],
["B1","RT-01 room set, complete, installed and accepted","Rate per room × 199","F-01 to F-11. State every item and its mass"],
["B2","RT-02 room set, complete, installed and accepted","Rate per room × 12","F-01 to F-14, to the clearances at {{spec.6}}"],
["B3","RT-03 room set, complete, installed and accepted","Rate per room × 14","F-01 to F-11 plus F-15 and F-16"],
["B4","RT-02 layout, measurement and verification, room by room","Rate per room × 12","PRICED SEPARATELY. {{spec.6}}. An hour a room, and the reason 12 rooms stay compliant"],
["B5","Mattress encasements — one fitted plus one spare per bed","Rate per bed × 225","{{spec.5}}. The spare is not optional"],
["C","RECEPTION AND AMENITY","",""],
["C1","Reception counter and waiting area","Lump sum","F-17, F-18. Accessible section at 760 mm"],
["C2","Parcel and post lockers","Lump sum","F-19. Not fewer than 60 compartments"],
["C3","Resident lounge seating for not fewer than 60","Lump sum","F-21. Fire load confirmed under {{iface.IF-12}} before order"],
["C4","Occasional tables and media units","Lump sum","F-22, F-23"],
["C5","Quiet room and study — not fewer than 12 positions","Rate per position","F-24"],
["C6","Games and recreation furniture","Lump sum","F-25"],
["C7","Multi-faith room furniture","Lump sum","F-26. Arrangement confirmed with residents through P5"],
["D","OFFICE AND MANAGEMENT","",""],
["D1","Office desking, chairs and pedestals — not fewer than 10 positions","Rate per position","F-27, F-28"],
["D2","Meeting table and chairs","Lump sum","F-29"],
["D3","Lockable storage and filing","Lump sum","F-30. Keyed to a schedule agreed with P5"],
["E","LAUNDRY, DRYING AND STORES","",""],
["E1","Laundry folding tables and seating","Lump sum","F-31, F-32. The machines are P5's — {{iface.IF-10}}"],
["E2","Laundry and linen trolleys","Rate per unit","F-33"],
["E3","Racking and shelving to stores, with marked capacities","Lump sum","F-34"],
["F","EXTERNAL","",""],
["F1","External seating and tables","Rate per unit","F-35"],
["G","ATTRITION STOCK — PRICED SEPARATELY","",""],
["G1","Bedroom lines, not less than 3%","Rate per line","{{spec.12}}. Delivered at the FIRST sectional handover"],
["G2","Seating lines, not less than 5%","Rate per line","{{spec.12}}"],
["H","INSTALLATION, LOGISTICS AND ACCEPTANCE","",""],
["H1","Delivery, storage, assembly and installation","Included in the room and item rates","Stated here so that nobody prices it twice"],
["H2","PACKAGING REMOVAL FROM SITE","Lump sum","PRICED SEPARATELY. {{spec.15}}. Daily, for the length of the installation"],
["H3","Room acceptance checks — 225 rooms, individually signed","Rate per room","{{spec.13}}. Not a sample"],
["H4","Inventory, asset data and handover deliverables","Lump sum","{{§handover}}, {{§info}}"],
["J","END OF DEPLOYMENT","",""],
["J1","Removal, cleaning, inspection and inventory of reusable lines","Lump sum","{{§relocation}}"],
["J2","Disposal of consumed lines, by stream, with the route stated","Lump sum","{{sustain.3}}"],
["J3","TAKE-BACK CREDIT — residual value offered at month 38","Credit, stated","{{relocation.1}}. Stated as a minus. It is evaluated"],
],

register: [
["G01","No design responsibility matrix or Contractor's Proposals mechanism","{{spec.1}}: the duties the Employer states are listed, product selection is the Contractor's, the Contractor's Proposals are specified item by item, a Schedule of Departures is required with the tender, and test evidence must be submitted rather than promised"],
["G02","Prescriptive and performance specification mixed","All 36 lines at {{§schedule}} carry an E or C code — 18 prescribed, 18 contractor-designed — and clause 1.2 states the only three reasons a line here is prescribed: a dimension that must agree with joinery P2 has already built, a life-safety or accessibility requirement, and a hygiene requirement. NO PRODUCT IS NAMED anywhere in the document"],
["G03","No stated failure mode","{{spec.3}}: BS 7177 medium hazard for mattresses and BS 7176 medium hazard for upholstery, PERMANENTLY LABELLED, with the label itself part of the specification — and the amenity seating schedule confirmed against the fire strategy before it is ordered, because seating added after the strategy was written is how a compartment stops working"],
["G04","No damages or delay mechanism","{{programme.4}}: £145 per bed per day per sectional date, the same rate as the P2 sectional damages, with five named causes of an extension of time including an installation window compressed below the stated minimum. A room without a bed is an unoccupiable room"],
["G05","No defects regime","{{§defects}}: 12 months per section, warranties of 5 years on frames and 2 years on moving parts running past it, three priorities with times, and the SYSTEMIC RULE — the same failure in more than 5% of a line is a defect in the whole line, because 225 of anything fails on a curve and the Contractor sees the curve first"],
["G06","No temporary works regime","Not applicable to loose furniture, and {{spec.7}} says so by prohibiting the thing that would create one: no fixing into the module structure, a partition, a ceiling or a fire-rated element without a detail P2 has accepted in writing. Every scheduled item can be provided free-standing, deliberately"],
["G07","Relocation imposed without a requirement","{{§relocation}}: what is reusable, what is consumed, the take-back terms and the residual value at month 38 — all stated with the tender and all evaluated, with the take-back credit priced at schedule item J3 as a minus"],
["G08","No information requirements","{{§info}}: the P2 Appendix 11 schema unamended, AND the granularity decision made explicitly — beds, mattresses, chairs and amenity seating individually by room because P5 replaces them one at a time; bins and laundry bags by type and quantity because nobody tracks a bin by serial number"],
["G09","No site constraints","{{§hse}}: installing in a village where people are already asleep, delivery routes stated by P1, nothing stored in an escape route at any time, and entry to an occupied room under P5's procedure. Plus {{spec.14}} — being last in the sequence is the programme risk and the minimum installation window is stated by the tenderer, not assumed by the Employer"],
["G10","No electrical supply characteristics","Not applicable — no item in this package is a fixed electrical installation. The charging positions at F-06 and the power provision at F-24 and F-29 are served from outlets P2 provides, and the coordination of those positions is at {{boundary.3}}"],
["G11","No water supply characteristics","Not applicable. The laundry and drying MACHINES that would need them are P5's under its personal laundry service, and this package furnishes the room around them — {{iface.IF-10}}"],
["G12","No evacuation or alarm strategy","{{spec.3}} and {{iface.IF-12}}: this package's contribution to evacuation is the fire load it adds and the fire action notice holder at F-11, and both are addressed. Nothing is stored in an escape route at any time — {{spec.15}}"],
["G13","A figure that was tight for the technology","The 23 kg manual handling limit at {{spec.9}} is stated as a component limit rather than an assembled one, precisely so that it is achievable, and every item above it carries a permanent two-person mark with its mass"],
["G14","No loading or serviceability criteria","{{spec.2}} and {{spec.10}}: BS EN 16139 level L2 seating, BS EN 15372 level 5 tables, BS EN 16121/16122 level 5 storage, BS EN 1725 beds, and stability with the heaviest drawer extended and loaded WITHOUT anchoring — because anchoring would conflict with {{spec.7}}"],
["G15","No change control","{{§change}}: written instruction from the named representative only, valuation before instruction, the rule that an operational request is not an instruction, and the date beyond which a change carries a cancellation cost, stated line by line, because contract furniture is made to order"],
["G16","Float ownership not stated","{{programme.1}} and {{programme.2}}: the minimum installation window is stated by the tenderer and held to by the Employer, and the three deliverables that sit months ahead of any delivery are shown on the programme with the date at which each becomes critical"],
["G17","No sustainability requirement","{{§sustain}}: materials by mass, recycled content, separability at end of life, certified timber without exception, and the halogenated flame retardant question asked honestly — the fire classification is not negotiable, how it is reached is a legitimate question"],
["G18","No testing regime for the thing that fails","{{spec.13}}: THE SAMPLE ROOMS, one of each type, furnished on site in a completed module before any bulk delivery — and 225 individual room acceptance checks, because the failures in this package are individual and a sample cannot find them"],
["G19","Missing drainage detail","Not applicable. This package has no drainage, and {{§rooms}} states what it does have so that the absence is a decision rather than an omission"],
["G20","No obsolescence or support period","{{spec.12}}: model continuity for the deployment plus 12 months, 6 months' written notice of discontinuation, a compatible alternative defined on dimension, fire classification, finish and fixings, and a replacement lead time not exceeding 4 weeks for any bedroom line"],
["G21","No inspection checklist","{{§performance}}: 36 criteria each with a figure and a verification method, and {{spec.13}}: a room acceptance checklist agreed with P5 before the first delivery and signed room by room for all 225"],
["G22","No definitions","{{§definitions}}: 10 terms, including encasement, hazard level, attrition stock, the Common Schedule, and what a furnished room actually is — which is not a room the furniture has been delivered to"],
["G23","No ethical labour requirement","{{§labour}}, and {{labour.2}} in particular: the place of manufacture of EVERY line disclosed by country and by site, undisclosed onward subcontracting a material breach in its own right, audit at any tier without notice with private worker interviews, and fibre origin evidenced for cotton and textiles. This is the package most likely to be made offshore"],
["G24","Clauses with no measurable requirement","Every performance criterion carries a figure and a verification method: hazard levels, severity levels, 1500 mm, 1000 mm, 450–500 mm, 150 mm, 900 mm, 23 kg, 60 °C, 3%, 5%, 4 weeks, 10%"],
["G25","No security requirement","{{spec.16}}: no delivery to a building that is not lockable, sealed deliveries with recorded seal numbers, a broken seal reported within 2 hours and before installation, weekly inventory reconciliation, and responsibility held until the inventory is handed over — because this is the most stealable package on the project and it arrives when site security attention has moved on"],
],
};
