// Employer's Requirements — P4 Furniture, Fittings and Loose Equipment.
// Written against the same twenty-five findings as the P2 gap register.
module.exports = {
  meta: {
    client: "Marrowbridge Infrastructure Ltd",
    project: "Project NORTHREACH — Workforce Accommodation Village",
    package: "P4 — Furniture, Fittings and Loose Equipment",
    ref: "NR-ER-P4", rev: "A", date: "September 2026",
    scope: "Loose furniture to 225 bedrooms, 420 m² of reception and resident amenity space, 180 m² of laundry, drying and stores, and the external resident areas. Fitted joinery is P2; dining furniture is P3",
  },

  opening: [
    ["1","The smallest package on this project, and the one most likely to embarrass it",
      "This is the cheapest of the five packages and it is the last to arrive. It is also the only one that every resident touches, every day, for up to thirty-eight months.\n\nTHE DEFINING FACT. This package has almost no work of its own. Its entire risk lives at its boundary with P2 — where fitted joinery stops and loose furniture starts. P2 builds a wardrobe, a desk and a shelf into the module in a factory four hundred miles away. This package brings the bed, the chair and everything else. If those two lists do not agree, the failure is discovered when a bed is carried into a room that has no space for it, and by then the module has been manufactured. {{§boundary}} exists for that and it is the most important section in this document.\n\nTHE SECOND FACT. Furniture in sleeping accommodation is not furniture. It is fire load, in a room where somebody is asleep. {{spec.3}} states the standards and they are not negotiable by price.\n\nTHE THIRD FACT. Twelve of these rooms are accessible rooms. An accessible room is designed as an empty box and it is THIS package that decides whether it is still accessible once there is a bed in it. {{spec.6}}."],
    ["2","Output specification, and where this document departs from it",
      "The default is an OUTPUT specification. The Employer states the duty — a dimension, a durability class, a fire standard, a clearance — and the Contractor selects, supplies, assembles and warrants the product that meets it.\n\nEvery line of the furniture schedule at {{§schedule}} carries a code.\n\nE — EMPLOYER-PRESCRIBED. The Employer has specified the thing. The Contractor provides it as described and the Employer carries the risk that what is described achieves the duty.\n\nC — CONTRACTOR-DESIGNED. The Employer has stated a duty. The Contractor selects the product, sizes it, and warrants that it performs.\n\nThe prescribed lines here are of three kinds and no others: a DIMENSION that has to agree with fitted joinery P2 has already built, a LIFE-SAFETY OR ACCESSIBILITY requirement, and a HYGIENE requirement that follows from the same bed being used by a succession of people. Everything else is a duty, because the Employer has no business selecting a chair and then owning the fact that it is uncomfortable.\n\nNO PRODUCT IS NAMED IN THIS DOCUMENT. Where a figure looks like a product it is a dimension or a class, and any product meeting it is acceptable."],
    ["3","What is NOT in this package",
      "FITTED JOINERY IS P2. The wardrobe, the desk worktop and the shelving over it are built into the module. They are specified at the P2 room data sheets and they are not reissued here — {{boundary.2}} states how the two lists are reconciled.\n\nDINING FURNITURE IS P3. The tables and chairs in the dining room are in the kitchen and catering package, because they are sized from the covers and the servery throughput rather than from the room. The boundary is at the dining room door and it is scheduled at {{iface.IF-06}}.\n\nBED LINEN, TOWELS AND THEIR LAUNDERING ARE P5. This package supplies the durable items — the mattress, the protector, the pillow and the duvet. The sheets, pillowcases, duvet covers and towels are consumable stock supplied and laundered by the Operator under its linen service. {{spec.4}} and {{iface.IF-09}}.\n\nLAUNDRY AND DRYING MACHINES ARE P5, sized and sited by the Operator against its own waiting-time requirement. This package furnishes the laundry room around them — {{iface.IF-10}}.\n\nANY FIXING INTO THE MODULE STRUCTURE IS P2's TO AGREE. See {{spec.7}}. This package does not put a screw into a wall, a ceiling or a fire-rated element without a detail P2 has accepted."],
  ],

  defs: [
    ["Attrition stock", "Spare furniture held on site from handover to replace breakages without waiting for a delivery. {{spec.12}}."],
    ["Common Schedule", "The single document, issued by the Employer, that divides every item in a bedroom between P2 fitted joinery and P4 loose furniture. Scheduled at P2 IF-05 and required at {{boundary.2}}. It is the artefact this package stands or falls on."],
    ["Contract furniture", "Furniture tested and rated for non-domestic severe use, not domestic furniture bought in quantity. The standards are at {{spec.2}}."],
    ["E / C", "The basis codes at clause 1.2. E means the Employer prescribed it and carries the risk it works; C means the Employer stated a duty and the Contractor warrants the means."],
    ["Encasement", "A mattress protector that fully encloses the mattress and zips shut, rather than a fitted sheet over the top of it. Required at {{spec.5}} and the reason is at {{spec.5}}."],
    ["Furnished room", "A room in which every scheduled item is present, assembled, clean, undamaged and — in an accessible room — checked against the clearances at {{spec.6}}. It is not furnished until it has passed the room acceptance check at {{spec.13}}."],
    ["Hazard level", "The fire performance classification in BS 7176 and BS 7177. This project requires MEDIUM HAZARD as a minimum throughout. {{spec.3}}."],
    ["Loose furniture", "Anything not built into the module. If it can be carried out of the room by two people without tools, it is this package's."],
    ["RT-01 / RT-02 / RT-03", "The three bedroom types: 199 standard, 12 accessible, 14 senior and long-stay. Quantities and the furniture differences are at {{§rooms}} and {{§schedule}}."],
    ["Sample room", "One fully furnished room of each type, approved by the Employer and by P5 before any bulk delivery. {{spec.13}}."],
  ],

  // ---------------------------------------------------------- what is furnished
  roomsNote:
    "Every quantity in this package comes from this table, and every one of them is taken from the P2 requirements rather than restated independently — there must be one version of how many rooms there are.\n\nTHE AREAS ARE THE P2 SCHEDULE OF QUANTITIES, items C1 and C3. The internal subdivision below is the Employer's intended use of that area and is indicative; where the Contractor's furniture layout requires a different split it shall say so with its tender, because the split drives the furniture and not the other way round.",
  // [ref, space, quantity or area, what this package provides, note]
  rooms: [
    ["BEDROOMS — 225","","","",""],
    ["R-01","RT-01 standard bedroom","199 rooms","Bed, mattress, protector, pillow, duvet, bedside unit, task chair, bin, laundry bag, mirror","The base room. Every other room is priced against it"],
    ["R-02","RT-02 accessible bedroom","12 rooms","As RT-01, with the clearances and the transfer heights at {{spec.6}}","THE FURNITURE IS WHAT MAKES THESE ROOMS COMPLIANT OR NOT"],
    ["R-03","RT-03 senior and long-stay bedroom","14 rooms","As RT-01, plus an easy chair and a second bedside unit","P2 gives these rooms a larger desk and more storage. This package adds the thing that makes a long stay bearable"],
    ["RECEPTION AND RESIDENT AMENITY — 420 m² (P2 item C1)","","","",""],
    ["R-04","Reception and waiting","60 m²","Reception counter, waiting seating, parcel lockers, noticeboard","Staffed continuously by P5. The counter is used 24 hours a day"],
    ["R-05","Management and site office","70 m²","Desks, task chairs, pedestals, lockable storage, meeting table","For P5's establishment and the Employer's site team"],
    ["R-06","Resident lounge and television","120 m²","Lounge seating, occasional tables, television mounting","The largest single room a resident uses that is not their own"],
    ["R-07","Quiet room and study","45 m²","Individual study positions, task chairs, task lighting","Somewhere to take a call home that is not a bedroom"],
    ["R-08","Games and recreation","75 m²","Games tables, seating, equipment storage","Two shifts, opposite hours, same room"],
    ["R-09","Multi-faith room","25 m²","Storage, shoe racking, mats, screening","Orientation and screening confirmed with residents, not assumed"],
    ["R-10","Amenity stores","30 m²","Racking and shelving","Holds the attrition stock at {{spec.12}}"],
    ["LAUNDRY, DRYING AND STORES — 180 m² (P2 item C3)","","","",""],
    ["R-11","Laundry and drying","110 m²","Folding tables, seating, laundry trolleys, basket storage","The MACHINES are P5's under its personal laundry service — {{iface.IF-10}}"],
    ["R-12","Linen store","40 m²","Racking, linen trolleys","Stocked and operated by P5"],
    ["R-13","General stores","30 m²","Racking and shelving",""],
    ["EXTERNAL","","","",""],
    ["R-14","External resident areas","Per NR-TW-VIL-0201","Seating and tables at the shelter and the external break areas","Weatherproof and secured against removal, but movable for grounds maintenance"],
  ],
  roomsTotals: [
    ["Bedrooms furnished", "225 — 199 RT-01, 12 RT-02, 14 RT-03"],
    ["Amenity and reception area furnished", "420 m²"],
    ["Laundry, drying and stores furnished", "180 m²"],
    ["Dining furniture", "NOT in this package — P3, 100 covers at its item D4"],
    ["Sectional dates the furniture is delivered against", "Month 3 — 65 beds · month 6 — 150 · month 9 — 205 · month 12 — 225"],
  ],

  // -------------------------------------------------------- the furniture schedule
  scheduleNote:
    "Every line carries a basis code. Clause 1.2 states the only three reasons a line here is prescribed: a dimension that must agree with joinery P2 has already manufactured, a life-safety or accessibility requirement, and a hygiene requirement that follows from a succession of people using the same bed.\n\nNo product is named. Where a figure appears it is a dimension, a class or a standard, and any product meeting it is acceptable.",
  // [ref, item, the duty or the specification, basis, note]
  furniture: [
    ["BEDROOM — ALL TYPES","","","",""],
    ["F-01","Bed frame","Single, 900 × 2000 mm sleeping surface. Metal or solid-section frame with no open tube end, no upholstered base and no fabric-covered headboard. Clear open space beneath the whole frame of not less than 150 mm for cleaning and inspection. Capable of being assembled and dismantled in the room without specialist tools","E","THE DIMENSION IS PRESCRIBED because P2 has already built the wardrobe and the desk around it. The construction is prescribed for the reason at {{spec.5}}"],
    ["F-02","Mattress","BS 7177 medium hazard minimum, permanently labelled. Turnable or single-sided with the rotation regime stated. Cover impermeable or fully protected by F-03. Depth compatible with the transfer height at {{spec.6}} in RT-02","E","Fire performance and hygiene. Everything else about it — spring, foam, firmness — is the Contractor's"],
    ["F-03","Mattress encasement","Fully enclosing, zipped, waterproof, vapour permeable, wipe-cleanable and launderable at not less than 60 °C. One fitted plus one spare per bed","E","A fitted sheet over the top of a mattress is not a protector. {{spec.5}}"],
    ["F-04","Pillow","2 per bed, washable at not less than 60 °C, with a wipe-cleanable protector per pillow","E","Durable stock in this package. The pillowcase is P5's linen"],
    ["F-05","Duvet","1 per bed, washable at not less than 60 °C, tog rating appropriate to a room heated and ventilated to the P2 requirements, with a summer option stated","C","The duvet cover is P5's linen — {{iface.IF-09}}"],
    ["F-06","Bedside unit","Free-standing, stable when the top drawer is fully extended and loaded, with a surface large enough for a phone, a drink and a book, and a charging position reachable from the pillow","C","P2 provides the socket. This package provides the surface it lands on"],
    ["F-07","Task chair","BS EN 1335 type B. Height adjustable, adjustable back support, five-star base on castors suited to the floor finish, upholstery to BS 7176 medium hazard","E","A resident works and calls home from this chair for months. A stacking canteen chair is a back injury with a delivery note"],
    ["F-08","Waste bin","Not less than 15 litres, lidded, wipe-cleanable, with a liner arrangement P5 can service in one movement","C",""],
    ["F-09","Laundry bag or hamper","Not less than 40 litres, ventilated, washable, and identifiable to the room","C","P5 collects it. It has to survive being carried down a stair 150 times"],
    ["F-10","Mirror","Full length, shatter-resistant or safety-backed glass to BS EN 12600 class 2 minimum — read with {{spec.10}} on the standard P2 cites","E","Safety glass in a bedroom is not optional. FIXING is P2's to agree — {{spec.7}}"],
    ["F-11","Room information holder","A single fixed or free-standing holder for the fire action notice, the room number and the resident information","E","P5 puts a fire action notice in every room. It needs somewhere to go that is not tape on a wall"],
    ["BEDROOM — TYPE DIFFERENCES","","","",""],
    ["F-12","RT-02 bed","As F-01, with the top of the mattress between 450 and 500 mm above finished floor level, and a clear space of not less than 150 mm beneath the frame across its full footprint for a mobile hoist","E","{{spec.6}}. The transfer height is the requirement; the bed is the Contractor's"],
    ["F-13","RT-02 chair","As F-07 with arms, stable under a transfer load applied at the front edge, and not on castors","E","A chair on castors is a fall during a transfer"],
    ["F-14","RT-02 furniture layout","A layout drawing per room demonstrating the clearances at {{spec.6}} WITH the furniture in place","E","This is the line that keeps 12 rooms compliant"],
    ["F-15","RT-03 easy chair","One per room, with arms, seat height 450–480 mm, upholstery to BS 7176 medium hazard, cover removable and washable or wipe-cleanable","C","A long-stay room needs somewhere to sit that is not the bed or the desk chair"],
    ["F-16","RT-03 second bedside unit","As F-06, one additional unit, so that both sides of the bed have a surface and a charging position","C","A long-stay room is lived in, not slept in"],
    ["RECEPTION AND AMENITY","","","",""],
    ["F-17","Reception counter","Continuously staffed position with a seated and a standing height, a section at 760 mm maximum with knee clearance for a wheelchair user, and cable management to the P2 outlets","E","BS 8300-2. It is the first thing a resident meets and the only staffed point at 03:00"],
    ["F-18","Reception and waiting seating","Contract seating to BS EN 16139 severity level L2, with not fewer than 20% of positions having arms and a seat height of 450–480 mm","E","People with bad backs and heavy bags. The 20% with arms is the accessibility requirement"],
    ["F-19","Parcel and post lockers","Not fewer than 60 compartments, lockable, with an accessible tier at 400–1200 mm","C","225 people ordering online for 38 months. Under-sized, and reception becomes a parcel store"],
    ["F-20","Noticeboards and wayfinding holders","Reception, amenity, laundry and each block entrance","C","{{spec.7}} governs the fixing"],
    ["F-21","Lounge seating","Contract upholstered seating to BS EN 16139 level L2 and BS 7176 medium hazard, for not fewer than 60 people, in groups rather than in rows, with removable or wipe-cleanable covers","E","THE CAPACITY IS PRESCRIBED. Two shifts, and the lounge is where the one that is awake goes"],
    ["F-22","Occasional and coffee tables","Stable under an off-centre load, no glass, edges radiused","C",""],
    ["F-23","Television mounting and media units","Mounting to the position P2 has provided for","C","{{spec.7}}. The bracket is not fixed to a partition P2 has not agreed"],
    ["F-24","Quiet room and study positions","Not fewer than 12 individual positions, each with a work surface not less than 800 × 600 mm, a task chair to F-07 and a power and data position","E","This is where a resident calls home. Twelve positions for 225 people is a floor, not a target"],
    ["F-25","Games and recreation furniture","Tables and seating for the games provision, and lockable storage for equipment","C","P5 states the provision it will operate"],
    ["F-26","Multi-faith room furniture","Shoe racking, mats, screening and lockable storage, arranged to the orientation the room requires","E","Confirmed with residents through P5, not assumed. It is the cheapest line in this schedule and the one most noticed"],
    ["OFFICE AND MANAGEMENT","","","",""],
    ["F-27","Office desks and pedestals","Contract desking to BS EN 527, not fewer than 10 positions, with cable management","C","For P5's establishment and the Employer's site team"],
    ["F-28","Office task chairs","As F-07, one per desk position at F-27 and one per meeting position at F-29","C","Same chair as the bedrooms, so the attrition stock at {{spec.12}} covers both"],
    ["F-29","Meeting table and chairs","One table seating not fewer than 10, with power and data provision","C",""],
    ["F-30","Lockable storage and filing","Sufficient for the occupancy records P5 must hold securely, lockable to a keying schedule agreed with P5","E","The occupancy record is a fire safety document and personal data. It is not left on a desk"],
    ["LAUNDRY, DRYING AND STORES","","","",""],
    ["F-31","Laundry folding tables","Not fewer than 4, 1800 × 700 mm minimum, impervious, wipe-cleanable, at 900 mm","C","The machines are P5's — {{iface.IF-10}}"],
    ["F-32","Laundry seating","Not fewer than 12 positions, wipe-cleanable, non-upholstered or impervious-covered","C","People wait with their washing. They will sit on the floor if there is nowhere else"],
    ["F-33","Laundry and linen trolleys","Not fewer than 8, with a wheel and brake suited to the floor finish and the external route","C","P5 operates them. It states the quantity it needs"],
    ["F-34","Racking and shelving to stores","Loaded to the shelf capacity stated and marked on each bay","E","An unmarked shelf capacity is an overloaded shelf"],
    ["EXTERNAL AND SPARES","","","",""],
    ["F-35","External seating and tables","Weatherproof, UV-stable, non-splintering, secured against removal but movable for grounds maintenance, and drainable so it can be sat on within 30 minutes of rain","C","Somebody sits here at 06:00 in the wet. Water on the seat is why the bench is not used"],
    ["F-36","Attrition stock","Not less than 3% of every bedroom line and 5% of every seating line, delivered at the FIRST sectional handover and held in the amenity store","E","{{spec.12}}. Stock delivered at the end of the job is stock that arrives after the breakages"],
  ],
};
