// P4 — the element-by-element specification and the interface schedule.
module.exports = {

spec: [
["1","Design responsibility, and the Contractor's Proposals",
  "This is a contractor-selected package. The Employer has stated the duties: the dimensions that have to agree with P2's fitted joinery, the fire standards at {{spec.3}}, the accessible clearances at {{spec.6}}, the hygiene requirements at {{spec.5}} and the durability classes at {{spec.2}}. The products that meet them are the Contractor's selection and the Contractor warrants that they do.\n\nWITH ITS TENDER the Contractor shall submit Contractor's Proposals containing, as a minimum: a schedule against every line of {{§schedule}} naming the product offered, its dimensions, its mass and its test evidence; a furniture layout at 1:50 for RT-01, RT-02 and RT-03; the RT-02 layouts demonstrating the clearances at {{spec.6}}; the access statement at {{spec.8}} for the three largest items; the cleaning products compatibility statement at {{spec.11}}; and its delivery programme against the four sectional dates at {{§programme}}.\n\nEVERY DEPARTURE from this document shall be listed in a Schedule of Departures with the clause, what is offered instead, the reason, the effect on every other requirement, and the price effect as a plus or a minus. A departure not listed is not accepted, whether or not it is visible in a photograph.\n\nTEST EVIDENCE IS SUBMITTED, NOT PROMISED. A catalogue statement that an item is 'contract grade' or 'fire retardant' is not evidence. The test certificate, the standard, the level and the date are.\n\nReview, comment or acceptance by the Employer does not transfer responsibility for the selection."],

["2","Contract furniture, and why domestic furniture bought in quantity is not it",
  "Everything in this package is used by a succession of strangers, at every hour, for thirty-eight months, and is cleaned to a commercial regime throughout. Domestic furniture bought in bulk fails inside a year and it fails in a way that is visible to every resident.\n\nMINIMUM PERFORMANCE, by item type, with the test report submitted for each:\n\nSeating, non-domestic — BS EN 16139 severity level L2 (severe), with BS EN 1728 for the seating strength and durability.\nOffice task chairs — BS EN 1335-1, -2 and -3, type B.\nTables and desks — BS EN 15372 level 5 (severe contract use). Office desking to BS EN 527-1, -2 and -3.\nStorage furniture — BS EN 16121 and BS EN 16122, level 5 where the item is in a resident area.\nBeds and mattresses — BS EN 1725 for the strength, stability and durability of the frame.\nOutdoor furniture — BS EN 581-1 and -2, contract use.\n\nWhere an item is not covered by any of those standards the Contractor shall state the standard it has tested to and why it applies. 'No applicable standard' is not an answer; it is a reason to ask what the item is made of.\n\nWARRANTY. Not less than 5 years on every frame and structural component and 2 years on every moving component and upholstery, running from the sectional handover at which the item is installed and not from the date of order."],

["3","Fire performance, which is the reason this document exists",
  "FURNITURE IN SLEEPING ACCOMMODATION IS NOT FURNITURE. It is the largest single item of combustible material in a room where somebody is asleep, and it is the difference between a fire that is contained and one that is not.\n\nMATTRESSES, DIVANS AND BED BASES — BS 7177, MEDIUM HAZARD as a minimum, permanently and durably labelled with the standard and the hazard level on the item itself.\n\nUPHOLSTERED SEATING, INCLUDING EVERY CHAIR, SOFA AND UPHOLSTERED HEADBOARD — BS 7176, MEDIUM HAZARD as a minimum, permanently and durably labelled.\n\nThose are the levels for hotel and hostel sleeping accommodation and they are the floor, not the target. Domestic furniture complying only with the Furniture and Furnishings (Fire) (Safety) Regulations 1988 does NOT satisfy this clause, and a supplier offering it has misread the building.\n\nCURTAINS, BLINDS AND ANY FABRIC HUNG IN AN ESCAPE ROUTE — BS 5867-2 type B, where any is provided under this package.\n\nTHE LABEL IS PART OF THE SPECIFICATION. An unlabelled item is a non-compliant item, whatever its paperwork says, because in three years the paperwork will be in a file and the label will be on the chair. Labels shall survive the cleaning regime at {{spec.11}} for the whole deployment.\n\nFIRE LOAD IN THE AMENITY BUILDING. The quantity of upholstered seating at F-21 is a fire load in a room with a stated fire strategy. The Contractor shall issue its seating schedule to the Employer's fire engineer for confirmation against that strategy before it orders, per {{iface.IF-12}}. Adding seating to a lounge after the strategy was written is how a compartment stops working.\n\nCOMPLIANCE WITH STATUTE. The Regulatory Reform (Fire Safety) Order 2005 applies to these premises and the responsible person's duty is not discharged by this clause. Nothing here reduces it."],

["4","Linen, and exactly where this package stops",
  "The division is between DURABLE and CONSUMABLE, and it is stated here because it is the boundary that gets discovered on the first day of occupation when 65 beds have no sheets.\n\nTHIS PACKAGE SUPPLIES, once, as durable stock: the mattress, the encasement at {{spec.5}} plus one spare per bed, the pillows and their protectors, and the duvet.\n\nP5 SUPPLIES AND LAUNDERS, as consumable stock throughout the deployment: sheets, pillowcases, duvet covers, towels and bath mats, under its linen service and to its own cycle.\n\nTHE CONTRACTOR SHALL STATE the mattress, pillow and duvet dimensions in its Contractor's Proposals, and the Employer shall issue them to P5 before P5 procures a single item of linen. A 200 mm deep mattress and a fitted sheet cut for 250 mm is 225 beds of linen that does not stay on. {{iface.IF-09}}.\n\nREPLACEMENT of a durable item during the deployment is dealt with at {{spec.12}}, not by P5 buying a different mattress."],

["5","The mattress, and the thing nobody writes into a furniture specification",
  "A bed in workforce accommodation is not slept in by one person. Over thirty-eight months it is used by a succession of people, some of whom arrive tired from another site, and the two things that damage it are fluids and infestation. Neither is in a furniture catalogue and both are certain.\n\nTHE ENCASEMENT. Every mattress shall be fully enclosed in a zipped, waterproof, vapour-permeable, wipe-cleanable encasement, launderable at not less than 60 °C, with one fitted and one spare per bed delivered at handover. A fitted sheet laid over a mattress is not a protector: it protects the top surface of a mattress from the one direction that matters least.\n\nThe encasement is changed and laundered between residents by P5, and the mattress beneath it is inspected at the same time. That is possible only because it unzips, which is why the requirement is a zipped encasement and not a stretch cover.\n\nTHE FRAME, and why it is prescribed at F-01. Metal or solid-section, with no open tube end, no upholstered base and no fabric-covered headboard, and not less than 150 mm of clear open space beneath the whole footprint.\n\nEvery one of those is an infestation requirement. Bed bugs live in the seams, the voids and the open ends of a bed frame, they arrive in somebody's bag through no fault of anybody's, and in shared accommodation they are a matter of when. A frame that can be visually inspected in two minutes and treated in ten is the difference between one room out of service for a day and a block out of service for a fortnight. A hollow tube with an open end cannot be inspected at all.\n\nThe Contractor shall state, in its Proposals, how the bed it offers is inspected and treated, and P5 shall confirm that the answer is workable before the order is placed. Neither party should meet this problem for the first time in month nine.\n\nCONDEMNING A MATTRESS. The Contractor shall state the criteria at which a mattress is withdrawn — fluid penetration through the encasement, structural failure, or an infestation treatment that cannot be verified as successful — and the replacement route at {{spec.12}} shall cover them."],

["6","The accessible room, and the furniture that decides whether it still is one",
  "THIS IS THE CLAUSE THAT CATCHES THE FAULT NOBODY LOOKS FOR. An accessible room is designed, approved and signed off as an empty box. It becomes accessible or not on the day this package puts a bed in it, and by then everybody who checked it has gone.\n\nIN EACH OF THE 12 RT-02 ROOMS, THE FOLLOWING SHALL BE ACHIEVED WITH ALL FURNITURE IN ITS FINAL POSITION and shall be demonstrated room by room on the layout at F-14, not asserted once for a room type:\n\nA clear turning space of not less than 1500 mm diameter, clear of every item of furniture, the door swing and the wheelchair user's own footplates.\nA clear transfer space of not less than 1000 mm to at least one side of the bed, at full length.\nTop of the mattress between 450 and 500 mm above finished floor level, and the Contractor shall state the compressed height and not the label height.\nNot less than 150 mm clear height beneath the entire bed frame footprint, unobstructed, for a mobile hoist.\nEvery item of storage, every surface and every control that a resident uses within the reach ranges of BS 8300-2, from a seated position.\nThe chair at F-13 with arms, stable under a transfer load applied at its front edge, and not on castors.\nNo item positioned so that it reduces the clear width of the door approach or the route to the ensuite below 900 mm.\n\nVERIFICATION. Each of the 12 rooms is measured with the furniture in place and the record issued, before that room is accepted at {{spec.13}}. A drawing showing compliance is not the verification; the measurement in the built room is.\n\nAND IF IT CANNOT BE ACHIEVED, SAY SO IN THE TENDER. If the room as built will not take a compliant furniture layout, that is a finding about the Employer's room and the Employer would rather have it now, while P2 can still change something, than after twelve modules have been manufactured."],

["7","Fixings, and the rule that this package does not put a screw in a wall",
  "Every wall, floor and ceiling in this village was manufactured in a factory four hundred miles away, and some of them are fire-rated, vapour-sealed or acoustically rated elements whose performance was tested before this package existed.\n\nNO ITEM SUPPLIED UNDER THIS PACKAGE SHALL BE FIXED TO THE MODULE STRUCTURE, TO ANY PARTITION, TO A CEILING OR TO A FIRE-RATED OR VAPOUR-SEALED ELEMENT except in accordance with a fixing detail P2 has accepted in writing.\n\nThe Contractor shall submit a fixing schedule listing every item it intends to fix, its mass, its point loads, the position, and the fixing it proposes, and shall submit it in time for P2 to confirm or object before manufacture where the fixing requires a pattress or a reinforced zone — {{iface.IF-04}}.\n\nA television bracket screwed into a partition that was not designed for it is a defect in two packages and it is discovered when the television comes off the wall.\n\nWHERE A FIXING CANNOT BE AGREED the Contractor shall offer a free-standing alternative rather than fix anyway. Every item in the schedule at {{§schedule}} is capable of being provided free-standing except where the Employer has prescribed otherwise, and that is deliberate."],

["8","Getting it into the room, and out again in thirty-eight months",
  "Furniture is installed AFTER the modules are set and BEFORE handover, per {{iface.IF-03}}. There is no stage at which a wall is open.\n\nEVERY ITEM SHALL THEREFORE be capable of being brought to its final position, and removed for replacement, through the completed building — either assembled, or in components assembled in the room without specialist tools.\n\nThe Contractor shall obtain from P2 the clear opening widths and heights of every door, corridor, stair and turn on the route to each room and to each amenity space, and shall check its three largest items against them, allowing not less than 50 mm clearance on the governing dimension and 100 mm along the route. For tender purposes it shall assume a bedroom door clear opening of 800 mm and shall confirm the actual figure before it orders — {{iface.IF-05}}.\n\nA 900 mm bed does not pass through an 800 mm door assembled. That is not a problem; it is a reason the frame at F-01 is required to assemble and dismantle in the room. It becomes a problem only if nobody checks until the lorry arrives.\n\nTHE STAIR. Blocks are two storey and there is no lift. Every item destined for a first-floor room shall pass the stair and its turn, in the components in which it will be carried, and the Contractor shall state that it has checked it.\n\nAT THE END OF THE TERM the same applies in reverse. Under {{§relocation}} this furniture is removed from occupied rooms in a live village; an item that could only be installed before the corridor was finished cannot be taken out after it."],

["9","Weight, and the person who has to move it",
  "P5 moves this furniture for thirty-eight months: room turnarounds, deep cleans, redecoration, replacements and the pest control inspections at {{spec.5}}.\n\nNO SINGLE ITEM SHALL EXCEED 23 kg in the components in which it is routinely moved. Where an assembled item exceeds it, the item shall either separate into components below it or shall carry a permanent, legible two-person handling mark stating its mass.\n\nEvery item in a bedroom shall be movable clear of the wall and the bed shall be movable clear of every wall, by one person, for cleaning and inspection. A bed that takes two people to move is a bed that is not moved, and what is under it is not cleaned.\n\nThe Contractor shall state the mass of every scheduled item in its Contractor's Proposals. That figure is used by P5 to write its method statements and by the Employer to check this clause, and an item delivered heavier than stated is a departure."],

["10","Stability, and the failures that injure somebody",
  "Every item of storage furniture shall be stable to BS EN 16122 with the heaviest drawer or door fully extended and loaded to its rated capacity, without anchoring to a wall. Where an item cannot achieve that it shall not be supplied, because the anchoring the standard would otherwise require conflicts with {{spec.7}}.\n\nEvery chair shall be stable to BS EN 1728 under a load applied at its front edge, at its side, and to its back at full recline where it reclines.\n\nEvery table shall be stable under an off-centre load at the point where somebody will lean on it, which is the corner nearest the door.\n\nNo glass in any resident area except where it is safety glass to BS EN 12600 class 2 or better, and no glass table tops at all.\n\nTWO STANDARDS FOR THE SAME THING, AND THE EMPLOYER STATES IT AGAINST ITSELF. The P2 room data sheets specify window glazing as toughened or laminated to BS 6206 Class A. BS 6206 WAS WITHDRAWN and is superseded by BS EN 12600, in which the classes run 1, 2 and 3 by drop height rather than A, B and C. Class A under the old standard corresponds to Class 1 under the current one, and Class B to Class 2.\n\nThis package specifies BS EN 12600 because it is the standard in force. The two documents are to be read as one requirement and P2 Appendix 8 and the room data sheets are to be corrected to the current standard. A tenderer offering glass certified only to a withdrawn standard has not met this clause, and a tenderer that noticed the conflict and priced around it silently has not either — it is listed as a departure under {{spec.1}}.\n\nSHELF AND RACK CAPACITIES shall be marked on the bay, permanently, per F-34. An unmarked capacity is an overloaded shelf within six months and there is nobody left who knows what it was rated at."],

["11","Cleaning, and surviving the regime it will actually get",
  "P5 cleans these rooms to a stated standard, daily in circulation and at every turnaround in a bedroom, with a defined chemical schedule, for thirty-eight months.\n\nEvery surface supplied under this package shall withstand daily cleaning with the products in the Operator's approved schedule, without discolouring, crazing, delaminating, softening or losing its label, for the whole deployment.\n\nTHE CONTRACTOR SHALL OBTAIN P5's CHEMICAL SCHEDULE and shall submit a written compatibility statement against it, product by product, with its Contractor's Proposals. Where P5 is not yet appointed the Employer will issue an indicative schedule; the Contractor shall confirm against the final one before it orders.\n\nNo unsealed timber, no untreated fabric, no crevice that cannot be reached, and no upholstery seam in a horizontal surface where liquid will sit.\n\nUPHOLSTERY COVERS in resident areas shall be removable and washable at 60 °C, or shall be an impervious wipe-cleanable material. A lounge chair with a fixed woven cover is a chair that is replaced in year two."],

["12","Attrition, model continuity, and what happens in month nineteen",
  "Furniture in a village of 225 people breaks. This clause is written so that a broken chair is replaced in a day rather than becoming the fourteenth different chair in the lounge.\n\nATTRITION STOCK. Not less than 3% of every bedroom line and 5% of every seating line, delivered at the FIRST sectional handover and held in the amenity store at R-10, with an inventory issued to and acknowledged by P5 under {{iface.IF-11}}. Stock delivered at the end of the contract has arrived after the breakages.\n\nMODEL CONTINUITY. The Contractor shall guarantee availability of each supplied model, or a demonstrably compatible successor, for the deployment period of 38 months plus 12 months. Where a model is discontinued it shall give not less than 6 months' written notice and shall offer a compatible alternative, and 'compatible' means it matches on dimension, on fire classification, on finish and on the fixings it uses.\n\nTHE REPLACEMENT ROUTE. The Contractor shall state its lead time for a replacement item ordered by P5 during the deployment. It shall not exceed 4 weeks for any bedroom line. Where it does, the attrition percentage for that line shall be increased and priced accordingly.\n\nNONE OF THIS IS A LUXURY. A village where the lounge has four kinds of chair and two rooms have no desk chair at all is a village that looks neglected, and it looks that way to the people who live in it every day."],

["13","The sample room, and how a room is accepted",
  "THE SAMPLE ROOMS. Before any bulk delivery the Contractor shall fully furnish one room of each type — RT-01, RT-02 and RT-03 — on site, in a completed module, and the Employer and P5 shall inspect and approve them jointly.\n\nThe RT-02 sample is measured against every clearance at {{spec.6}}, in the room, with the furniture in place.\n\nApproval of the sample rooms is a condition precedent to the first bulk delivery. A photograph of a showroom is not a sample room: the point of the exercise is the furniture in the actual room, at the actual dimensions, and it is the only test that finds the item that does not fit.\n\nROOM ACCEPTANCE. A room is accepted when it has passed a room acceptance check against a checklist agreed with P5 before the first delivery, covering: every scheduled item present; every item assembled, stable and undamaged; the encasement fitted and the spare present; the fire labels present and legible on every labelled item; nothing left in the room including packaging; and for RT-02, the clearances measured and recorded.\n\nTHE CHECK IS ROOM BY ROOM AND IT IS SIGNED. A sample-based acceptance is not acceptable for 225 rooms, because the failures are individual: one missing bin, one damaged chair, one room where the bed was put on the wrong side. Each of those is invisible in a sample and obvious to the person who moves in.\n\nHANDOVER OF A SECTION is complete when every room in it has passed and the inventory has been issued to and acknowledged by P5 under {{iface.IF-08}}, not when the delivery is complete."],

["14","Delivery, sequence, and the four dates that matter",
  "This package delivers against the sectional occupation dates, not against a single completion: 65 beds at month 3, cumulative 150 at month 6, 205 at month 9, 225 at month 12.\n\nFURNITURE FOR A SECTION SHALL BE INSTALLED AND ACCEPTED BEFORE THAT SECTION IS OCCUPIED. There is no arrangement in which residents move into an unfurnished room and the furniture follows.\n\nTHE INSTALLATION WINDOW is after module setting and building services commissioning, and before handover — {{iface.IF-03}}. It is short and it is the last thing in the sequence, which means every delay upstream lands on this package. The Contractor shall state, in its Proposals, the minimum installation window it requires per section and the resource it will apply.\n\nWHERE THE SEQUENCE SLIPS, P2 provides secure storage under its own requirements and the Contractor shall not deliver furniture into an unsecured or incomplete building. {{spec.16}} states why.\n\nA delivery accepted into a building that is not ready is a delivery that is stored in a corridor, damaged, and disowned by both parties."],

["15","Packaging, and 225 rooms of cardboard",
  "Furnishing 225 bedrooms and 600 m² of amenity space generates a volume of packaging that is a genuine logistics and waste problem on a site with a laydown area of 0.42 ha, and it is a problem this package creates.\n\nALL PACKAGING SHALL BE REMOVED FROM SITE BY THE CONTRACTOR, on the day it is generated. No packaging shall be left in a room, a corridor, a stairwell or an escape route at the end of any working day, and none shall be placed in the village waste provision, which is sized for residents and not for this.\n\nThe Contractor shall state, in its Proposals, the packaging it expects to generate by volume and how it will be segregated, removed and recycled, and shall report actuals monthly under {{§sustain}}.\n\nThe Employer will evaluate a returnable, reusable or blanket-wrap delivery method favourably, because it removes the problem rather than managing it.\n\nNO PACKAGING IN AN ESCAPE ROUTE, at any time, for any duration. From month 3 there are people asleep in the building next door and the escape route belongs to them."],

["16","Security, because this is the most stealable package on the project",
  "Furniture is valuable, portable, unmarked and, unlike a module or a drainage run, it fits in the back of a van. It arrives at the very end of the programme, when site security attention has usually moved on.\n\nNo delivery shall be made to a building that is not lockable and secured. Where the programme requires earlier delivery, the Contractor shall provide secure storage at its own cost and shall not store furniture in an unsecured shell.\n\nDeliveries shall be sealed and the seal number recorded, checked on arrival, and a broken seal reported within 2 hours and before any item is installed.\n\nAn inventory shall be maintained from the first delivery to the last room acceptance, reconciled weekly against the delivery records, and any discrepancy reported. A shortage found at handover cannot be attributed to anybody; a shortage found in the week it happened can.\n\nFrom first delivery until sectional handover the Contractor holds responsibility for the furniture in the building, under the key control regime P2 and P5 operate, and hands it over with the inventory rather than with the last delivery note."],

["17","Comfort, and the only test that matters",
  "Everything above this clause can be satisfied by a compliant, durable, fire-rated, cleanable set of furniture that nobody wants to sit on.\n\nThe Employer will evaluate the tender partly on the Contractor's Proposals being sat in. The sample rooms at {{spec.13}} shall be available to a panel including residents' representatives or, before occupation, the Employer's and P5's staff, and their view is recorded.\n\nAFTER OCCUPATION the furniture is measured by the residents' satisfaction survey P5 operates. Where a scheduled item is the subject of a sustained adverse response — the same item raised by more than 10% of respondents across two consecutive surveys — the Contractor shall attend, investigate and propose a remedy. Where the item is failing to meet a requirement of this document, the remedy is at the Contractor's cost.\n\nThat is not a soft clause. A desk chair that is unusable after two hours is a resident who works sitting on their bed for thirty-eight months, and it is one of the few things in this village that a person notices every single day."],
],

// [ref, with, what crosses, who certifies, when]
ifaces: [
["IF-01","P2 Modular Accommodation","THE COMMON SCHEDULE — every item in a bedroom divided between P2 fitted joinery and P4 loose furniture, line by line","A single schedule issued by the Employer and signed by both parties","BEFORE EITHER PACKAGE IS LET — {{§boundary}}"],
["IF-02","P2 Modular Accommodation","The dimensions, positions and clear zones of the fitted wardrobe, desk worktop and shelving that this package's furniture has to work around","P2 issues from its room data sheets; this Contractor confirms its layout against them","Before this Contractor orders anything"],
["IF-03","P2 Modular Accommodation","Access for installation after module setting and services commissioning and before handover, and secure storage where the sequence slips","Programme coordination; P2 provides the storage under its own requirements","Per the sectional dates at {{§programme}}"],
["IF-04","P2 Modular Accommodation","EVERY FIXING into the module structure, a partition, a ceiling or a fire-rated or vapour-sealed element","This Contractor submits the fixing schedule; P2 accepts in writing. Nothing is fixed without it","Before P2 manufactures, where a pattress or reinforced zone is needed — {{spec.7}}"],
["IF-05","P2 Modular Accommodation","Clear opening widths and heights of every door, corridor, stair and turn on the installation route","P2 states them; this Contractor checks its three largest items and confirms","Before this Contractor orders — {{spec.8}}"],
["IF-06","P3 Kitchen and Catering","THE BOUNDARY: dining furniture is P3, at its item D4 for 100 covers. Everything on the other side of the dining room door is this package","One common schedule issued by the Employer before either package is let","Before either package is let"],
["IF-07","P1 Civil Works","Delivery access, the unloading position and the route into each building during sectional occupation","P1 states the available routes; this Contractor confirms they suit its vehicle","4 weeks before each sectional occupation"],
["IF-08","P5 FM and Operation","The furnished rooms, the room acceptance checklist and the signed record, and the inventory","P5 acknowledges receipt room by room against the checklist","At each sectional handover — {{spec.13}}"],
["IF-09","P5 FM and Operation","LINEN: the mattress, pillow and duvet dimensions, so that P5's sheets, pillowcases and duvet covers fit them","This Contractor states the dimensions; the Employer issues them to P5 before P5 procures","Before P5 orders any linen — {{spec.4}}"],
["IF-10","P5 FM and Operation","Laundry and drying MACHINES are P5's under its personal laundry service. This package furnishes the room around them","P5 states the machine positions and clearances; this Contractor lays out the furniture to suit","Before this Contractor's laundry layout is fixed"],
["IF-11","P5 FM and Operation","Attrition stock at {{spec.12}}, its inventory, the replacement route, the lead times and the bed inspection method at {{spec.5}}","P5 confirms the arrangements are workable before this Contractor orders","At the first sectional handover"],
["IF-12","Employer's fire engineer","The upholstered seating schedule for the amenity building, as a fire load against the stated fire strategy","The fire engineer confirms; this Contractor does not order until it has","Before ordering the amenity seating — {{spec.3}}"],
],
};
