// Employer's Requirements — P5 FM and Operation. Content, separated from layout.
//
// Written against the same twenty-five questions as the P2 gap register. They
// land differently on a service contract: G01 becomes the management
// responsibility matrix, G02 becomes output versus input specification, G03
// becomes the failures that a service credit does not remedy, G04 becomes the
// service credit regime, G05 becomes rectification times. The register is at
// section 22 and every finding is answered there.
module.exports = {
  meta: {
    client: "Marrowbridge Infrastructure Ltd",
    project: "Project NORTHREACH — Workforce Accommodation Village",
    package: "P5 — Facilities Management and Operation",
    ref: "NR-ER-P5", rev: "A", date: "September 2026",
    term: "Thirty-8 months from service commencement, with the demobilisation and relocation obligations at section 20 surviving it.",
  },

  // ------------------------------------------------------------- the thesis
  opening: [
    ["1", "What this package is, and the one thing that makes it different",
      "This package runs a village of two hundred and twenty-five single-occupancy rooms for 38 months, for people who live there because their work requires it.\n\nTHE ONE THING. The residents work shifts. At the peak, 45 per cent of them are asleep during the day. That single fact reorganises every service in this document: housekeeping cannot be scheduled by the clock, catering cannot serve three meals at conventional hours, transport runs on shift change and not on a timetable, grounds maintenance cannot run a mower past a sleeping block at eleven in the morning, and a fire drill at ten o'clock wakes the night shift who then work a twelve-hour turn.\n\nA facilities management specification written for an office, a student hall or a hotel will fail here, and it will fail in a way that looks like poor performance rather than like the wrong specification. Every service below is written from the shift pattern outward.\n\nTHE SECOND THING. A resident cannot leave. They are not a hotel guest choosing between providers; they are here for the duration of their rotation, a long way from home, and the service is the whole of their life outside work. That creates a duty this document treats seriously at section 12 and does not treat as hospitality."],
    ["2", "Output specification, and where this document departs from it",
      "The default in this document is an OUTPUT specification. The Employer states the outcome required and how it is measured. The Contractor decides the method, the frequency, the resource and the equipment, and carries the risk that its choices achieve the outcome.\n\nThat is the correct default and it is not universal. Some things are specified as INPUTS — a frequency, a method, a ratio — because the Employer requires them for a reason that is not captured by the outcome: a statutory duty, a safety margin, or a decision the Employer is not willing to delegate.\n\nEvery service in section 4 carries a code:\n\nO — OUTPUT SPECIFIED. The Employer states the outcome and the measure. The Contractor designs the service. If the outcome is not achieved, the method was wrong and that is the Contractor's problem.\n\nI — INPUT SPECIFIED. The Employer states the method, frequency or ratio. The Contractor delivers it as described. The Employer carries the risk that doing it produces the outcome, and the Contractor's duty is to say so where it believes it will not.\n\nThis is the single most consequential decision in a facilities management specification and it is usually taken by accident. Specifying \"clean each room daily\" is an input: if the room is dirty, the Employer specified the frequency and the Employer owns the problem. Specifying \"each room clean to the standard at 4.1 when its occupant returns from shift\" is an output, and the Contractor owns it. This document states which, line by line, and the tenderer prices accordingly."],
    ["3", "What is NOT in this package",
      "Construction of anything. This package receives a village built by others and operates it. The four construction packages are P1 Civil Works, P2 Modular Accommodation, P3 Kitchen and P4 Furniture; what each hands over, in what state and against whose certificate, is at section 6.\n\nThe Employer draws attention to one consequence. Where a service in this document cannot be delivered because something handed over under another package is inadequate, the Contractor's duty is to report it under the early warning at section 18, not to work around it silently. A workaround becomes the standard within a month and the defect is never fixed."],
  ],

  // ------------------------------------------------------- basis definitions
  defs: [
    ["Available", "A room, an asset or a facility is available when it can be used for its purpose by the person who needs it, at the time they need it. Not when it is nominally in service."],
    ["CAFM", "Computer-aided facilities management system — the system holding the asset register, the planned maintenance schedule and every work order. Section 9."],
    ["Contractor", "The party to whom this package is let."],
    ["Employer", "Marrowbridge Infrastructure Ltd, or a person authorised in writing to act for it under section 17."],
    ["FRA", "Fire risk assessment, under Article 9 of the Regulatory Reform (Fire Safety) Order 2005."],
    ["HACCP", "Hazard Analysis and Critical Control Points — the food safety management system required by Regulation (EC) 852/2004 as retained."],
    ["Monthly Service Fee", "The monthly sum payable for the services, before service credits. MSF."],
    ["Occupied", "A room is occupied when it is allocated to a named resident, whether or not that person is physically in it at the time."],
    ["O / I", "The basis codes at clause 2. O is an output the Contractor designs the method for; I is an input the Employer has specified. The consequence of each is stated at clause 2 and it is not a matter of emphasis."],
    ["PEEP", "Personal emergency evacuation plan — the individual plan for a resident who cannot evacuate unaided."],
    ["Resident", "A person accommodated in the village. Not a guest, not a customer, and not able to leave — see clause 1."],
    ["Responsible Person", "The person on whom the duties under the Regulatory Reform (Fire Safety) Order 2005 fall. Section 11 states who it is, because it is a legal duty and not a job title."],
    ["Rotation", "The cycle a resident works — for example 14 days on and seven off. Rooms turn over at rotation change and that is the busiest hour of the month."],
    ["Service Commencement", "The date the services begin for a section of the village, per the sectional completion dates at Appendix 6 of the P2 requirements."],
    ["Service Credit", "A reduction in the Monthly Service Fee where a service is not provided to the standard required. A price adjustment, not damages — see 15.1."],
    ["Shift change", "The period around the start and end of a working shift, when the greatest number of residents move at once. Every service peaks here."],
    ["SFG20", "The industry standard maintenance specification, used as the baseline planned maintenance schedule."],
    ["TMV", "Thermostatic mixing valve. The village has one at every basin and shower — 225 rooms, 450 valves, all of them a legionella and a scalding control."],
    ["Unacceptable Failure", "A failure that a service credit does not remedy. Listed at 15.4. The list is short and it is not negotiable."],
    ["Village Manager", "The Contractor's named individual in charge on site. Section 13."],
    ["Working day", "Monday to Friday excluding bank holidays in England and Wales. Note that the village does not have working days — it runs continuously, and response times in this document are stated in hours unless they say otherwise."],
  ],

  // ------------------------------------------------------ the service register
  // [ref, service, the outcome required, basis, note]
  services: [
    ["S-01", "Housekeeping — occupied rooms",
      "Every occupied room clean, serviced and fit to sleep in when its occupant returns from shift, to the standard at 4.1.",
      "O",
      "Scheduled by OCCUPANCY STATE, not by clock. A room whose occupant is on nights is serviced while they are at work, not at ten in the morning."],
    ["S-02", "Housekeeping — turnover between rotations",
      "A vacated room deep-cleaned, linen changed, faults reported and the room re-let ready within 4 hours of vacation.",
      "O",
      "At rotation change up to 60 rooms turn over in a day. Resource for the peak, not the average."],
    ["S-03", "Housekeeping — circulation, amenity and sanitary areas",
      "Circulation, amenity, laundry and shared sanitary areas clean and safe at all hours, with no period of the day when they are not serviced.",
      "O",
      "There is no quiet hour in a shift-working village."],
    ["S-04", "Linen",
      "Clean bed linen and towels available to every resident on a cycle of not less than once per 7 days, and on demand after a soiling incident.",
      "I",
      "The frequency is an input because it is a dignity floor, not an efficiency question."],
    ["S-05", "Personal laundry",
      "Laundry facilities available 24 hours, sized so that no resident waits more than 30 minutes for a machine at the busiest hour of the week.",
      "O",
      "The busiest hour is the evening of a rotation change. Size for it."],
    ["S-06", "Catering — meals at every shift change",
      "A hot, nutritionally adequate meal available to every resident within 1 hour before the start and 1 hour after the end of every shift they work, whatever hour that is, including night shift.",
      "O",
      "THE NIGHT MEAL IS THE ONE THAT GETS DROPPED. It is not optional and it is not a vending machine."],
    ["S-07", "Catering — packed provision",
      "A packed meal and drink available to every resident going to shift, collected without queueing beyond 10 minutes at shift change.",
      "O",
      ""],
    ["S-08", "Catering — dietary, religious and medical requirements",
      "Every stated dietary, religious or medical requirement met at every service, without the resident having to ask again after the first time.",
      "I",
      "Asking twice is the failure. The requirement is recorded at check-in and carried."],
    ["S-09", "Reception, allocation and occupancy record",
      "Every arriving resident allocated a room, issued a key and inducted before they need to sleep; and the occupancy record accurate at all times.",
      "O",
      "The occupancy record is a FIRE SAFETY document before it is an administrative one — see 11.3."],
    ["S-10", "Security",
      "No unauthorised person within the village; every resident able to reach their room safely at any hour; every incident recorded and reported.",
      "O",
      "Cameras, recording and monitoring are this package. The containment and cabling were provided under P2 4.19."],
    ["S-11", "Transport",
      "Every resident able to reach their shift start and return from it without a private car, arriving not less than 15 minutes before shift start.",
      "O",
      "Sized on the shift pattern and the day-shift proportion at Appendix 6 of the P2 requirements, which changes across the deployment."],
    ["S-12", "Planned maintenance",
      "Every asset maintained to a schedule not less onerous than SFG20 for its type, recorded in the CAFM against the asset identifiers received from P2.",
      "I",
      "SFG20 is an input floor. The Contractor may exceed it and shall say where it does."],
    ["S-13", "Reactive maintenance",
      "Faults attended and rectified within the priority times at 4.13, which are deliberately the same three priorities used in the P2 defects regime so that a resident sees one standard.",
      "I",
      "The times are inputs. They are what a resident is told and they are not to be redefined by the Contractor."],
    ["S-14", "Grounds, external areas and winter service",
      "External routes, steps and the transport pick-up safe and passable at every hour the village is occupied, including in ice and snow.",
      "O",
      "A night-shift worker walks to a bus at five in the morning in January. That is the design case, not a fine afternoon."],
    ["S-15", "Waste and recycling",
      "Waste removed before it accumulates, segregated for recycling, with duty of care records for every movement and no waste stored where it attracts pests.",
      "O",
      "Interacts with S-18. A waste failure becomes a pest problem becomes a food safety problem."],
    ["S-16", "Utilities and energy management",
      "Continuity of supply to every block, consumption metered, reported monthly against the sub-metering provided under P2 4.24 and 4.25, and managed down over the deployment.",
      "O",
      "The metering exists. Section 9 requires it to be used rather than described."],
    ["S-17", "IT, network and resident connectivity",
      "Wireless coverage and capacity available to every resident in their room and in amenity space, to the level at P2 section 6.",
      "O",
      "For a resident a long way from home this is the connection to their family. It is a welfare service and it is scored as one."],
    ["S-18", "Pest control",
      "No pest activity in any catering, food storage, waste or accommodation area, on a proactive regime rather than in response to a sighting.",
      "O",
      ""],
    ["S-19", "Resident welfare and support",
      "A resident in difficulty has somewhere to go at any hour, and somebody notices when a resident stops appearing. Section 12.",
      "O",
      "The service most often left out of a facilities management specification, and the most important one here."],
    ["S-20", "Fire safety management",
      "The village managed in occupation so that it remains safe to sleep in: fire risk assessment current, tests and drills done, PEEPs in place, the occupancy record accurate. Section 11.",
      "I",
      "Statutory duties. Not open to method choice — see 11.1 on who the Responsible Person is."],
    ["S-21", "Water safety",
      "The written scheme of control received from P2 at IF-10 operated and recorded, so that the water is safe at every outlet in a village where rooms stand empty between rotations. Section 11.",
      "I",
      "This is the service that kills people if it is done badly. It is specified as an input for that reason."],
    ["S-22", "Food safety",
      "Food produced and served under a documented HACCP system, registered with the local authority, with allergen information available at the point of service. Section 11.",
      "I",
      "An outbreak takes out the workforce and therefore the project. The consequence is not confined to this package."],
    ["S-23", "Village management",
      "A named management team on site, in the numbers and at the times stated at section 13, empowered to decide.",
      "I",
      "The Employer is buying named people, not a headcount. See 13.2."],
  ],

  // -------------------------------------------------- the performance regime
  // [ref, KPI, the target, how it is measured, frequency, weight %]
  kpis: [
    ["K01", "Room ready on arrival", "100% of arriving residents have a room ready when they arrive", "Reception record against the arrivals list", "Every arrival", 6],
    ["K02", "Housekeeping standard, occupied rooms", "Audit score not less than 95%, on a random sample of 10% of occupied rooms", "Joint audit against the standard at 4.1", "Monthly", 6],
    ["K03", "Linen cycle", "100% of residents receive linen at not more than 7-day intervals", "Linen record, audited against the occupancy record", "Monthly", 4],
    ["K04", "Meal availability at every shift change", "100% of shift changes served, including night", "Service log, audited against the shift roster", "Every shift change", 8],
    ["K05", "Food safety records", "100% complete: temperatures, cleaning, allergen and traceability records", "Audit of the HACCP records", "Monthly", 6],
    ["K06", "Resident satisfaction with catering", "Not less than 80% satisfied or better", "Anonymous survey of not less than 25% of residents", "Quarterly", 4],
    ["K07", "Transport reliability", "99% of scheduled departures leave within 5 minutes and arrive not less than 15 minutes before shift start", "Vehicle tracking and driver log", "Every departure", 7],
    ["K08", "Priority 1 response", "100% attended within 1 hour, made safe within 4", "CAFM work order timestamps", "Every occurrence", 7],
    ["K09", "Priority 2 rectification", "95% rectified within 24 hours", "CAFM work order timestamps", "Monthly", 5],
    ["K10", "Block services availability", "Heating, hot water and power available to every block for not less than 99.5% of occupied hours", "CAFM outage record, cross-checked to the metering", "Monthly", 6],
    ["K11", "Water temperature compliance", "100% of sampled outlets within the P2 limits: 41 °C maximum at basin and shower, 50 °C minimum at the TMV inlet within 60 seconds, cold not exceeding 20 °C after 2 minutes", "Monthly sample of not fewer than 20 outlets, rotating so every outlet is tested twice a year", "Monthly", 6],
    ["K12", "Water safety scheme compliance", "100% of the tasks in the written scheme of control completed on time and recorded", "Audit of the scheme records", "Monthly", 6],
    ["K13", "Fire safety routine", "100%: weekly alarm test, monthly emergency lighting test, quarterly drill including one night drill per year, FRA reviewed at least annually and after any material change", "Fire logbook audit", "Monthly", 6],
    ["K14", "PEEPs", "100% of residents who need one have a current PEEP before their first night in the village", "Occupancy record cross-checked to the PEEP register", "Every arrival", 3],
    ["K15", "Occupancy record accuracy", "100% accurate at every roll call and at every audit", "Unannounced roll call against the record", "Monthly, unannounced", 5],
    ["K16", "Security", "Zero unauthorised persons within the village; 100% of incidents reported within 1 hour", "Incident log and CCTV review", "Monthly", 4],
    ["K17", "Network availability", "99% availability to every occupied room, measured over the month", "Network monitoring", "Monthly", 3],
    ["K18", "Welfare contact", "100% of residents flagged under the welfare procedure at 12.3 contacted within the stated time", "Welfare log", "Monthly", 3],
    ["K19", "Reporting", "100% of reports at section 9 delivered complete and on time", "Employer's receipt", "Monthly", 3],
    ["K20", "Labour standards and social value reporting", "100% delivered, in the units offered", "Employer's receipt and the evidence at 19.4", "Quarterly", 2],
  ],
};
