// P5 — pricing, and the twenty-five questions answered.
module.exports = {

pricing: [
["1","Why a flat monthly fee is the wrong shape for this village",
  "The occupancy of this village runs from 65 beds in month four to two hundred and twenty-five at the peak and back to zero by month thirty-eight. It varies by a factor of three and a half, and the variation is known in advance from the demand curve at Appendix 6 of the P2 requirements.\n\nA flat monthly fee prices that variation as risk. The Contractor loads for the months it is half empty, the Employer pays that load in every month including the full ones, and both parties then argue about occupancy for three years.\n\nThis package is therefore priced in two parts, and the split is the most important commercial decision in the tender."],
["2","The two parts",
  "THE FIXED ELEMENT covers the costs that do not vary with occupancy: the management team at {{§team}}, statutory compliance — fire, water, food — security, planned maintenance, the CAFM, insurance, and the on-call cover. Sixty-five occupied beds still require a Village Manager, a fire risk assessment, a water safety scheme and a person on reception at four in the morning.\n\nTHE VARIABLE ELEMENT is priced per occupied bed-night and covers housekeeping, linen, catering, transport and consumables — the services whose cost genuinely moves with the number of people present.\n\nThe Contractor states both. The Employer pays the fixed element monthly and the variable element against the actual occupancy taken from the record at {{spec.9}}. Neither party carries the occupancy risk, because the mechanism prices it."],
["3","The activity schedule","Priced in the structure below. A tenderer that alters the structure produces a return that cannot be compared with the others and it will be marked accordingly. A rate left blank is a rate of nil and the item is deemed included elsewhere."],
],

// [item, description, basis, note]
schedule: [
["A","MOBILISATION","",""],
["A1","Mobilisation — section 1 (65 beds, month 3)","Lump sum","Recruitment, training, systems, the fire risk assessment, food registration, the water safety transfer"],
["A2","Mobilisation — sections 2, 3 and 4","Lump sum, each","Smaller than A1. State each separately"],
["B","THE FIXED ELEMENT — per month","",""],
["B1","Village management team per {{§team}}","£ per month","Name the posts. This line is the one with a headcount behind it"],
["B2","Statutory compliance — fire, water, food","£ per month","Includes the competent persons, the testing regime and the records"],
["B3","Security and reception, continuous","£ per month",""],
["B4","Planned maintenance and on-call reactive cover","£ per month","Excludes materials, which are at F1"],
["B5","CAFM, systems and licences","£ per month","Including the Employer's five read-access users at no charge"],
["B6","Welfare and resident liaison per {{§welfare}}","£ per month","Stated separately so it cannot be absorbed into B1 and then quietly reduced"],
["B7","Insurance, overhead and profit on the fixed element","£ per month",""],
["C","THE VARIABLE ELEMENT — per occupied bed-night","",""],
["C1","Housekeeping — occupied rooms and turnover","£ per bed-night",""],
["C2","Linen and personal laundry","£ per bed-night",""],
["C3","Catering — all 4 service periods including the night meal","£ per bed-night","State the assumed take-up per service period"],
["C4","Transport","£ per bed-night","State the assumed vehicle count at peak"],
["C5","Utilities and consumables recharged at cost","At cost + %","State the percentage. Metered per P2 4.24 and 4.25"],
["D","VARIATIONS TO THE PATTERN","",""],
["D1","Additional service period, if the shift pattern changes","£ per period per month","Priced now because a third shift is a foreseeable change"],
["D2","Standing charge for a month at nil occupancy","£ per month","Sections stand empty at the end. Price it rather than argue it"],
["E","DEMOBILISATION","",""],
["E1","Demobilisation and handback, per section","Lump sum","Condition schedule, data export, records, credentials"],
["F","RATES FOR THE VALUATION OF CHANGE","",""],
["F1","All-in hourly rate by role and grade","Rate","Every category of staff. Fixed for the term"],
["F2","Percentage addition for overhead","%",""],
["F3","Percentage addition for profit","%",""],
["F4","Percentage addition on sub-contracted work","%",""],
["G","THE PRIME OPTION — PRICED, NOT INCLUDED","",""],
["G1","Management and integration, on the transferred value","%","{{§prime}}. Four separate lines. A single percentage will not be accepted"],
["G2","Corporate overhead recovery, on the transferred value","%",""],
["G3","Profit and prime risk, on the transferred value","%",""],
["G4","Controlled contingency, on the transferred value","%","Returnable. State the basis"],
["H","DEPARTURES","",""],
["H1","Each departure from these requirements, listed and priced","Each","{{management.2}}. A departure not listed is not accepted"],
],

// [ref, the finding against the P2 Rev A, where P5 answers it]
register: [
["G01","No design responsibility matrix or Contractor's Proposals mechanism","Section {{§management}} in full: the output/input basis at {{management.1}}, the Service Delivery Plan and Schedule of Departures at {{management.2}}, the thirty-row responsibility matrix at {{management.3}}, and the rule at {{management.4}} that review transfers nothing"],
["G02","Prescriptive and performance specification mixed","Every one of the twenty-three services carries an O or I code with its reason. Fifteen output-specified, eight input-specified. The consequence of each is stated at {{management.1}} and the eight inputs are each justified where they appear"],
["G03","No stated failure mode","{{§credits}}, and specifically the Unacceptable Failures at {{credits.4}} — the failures a service credit does not remedy, in five groups, with the immediate consequence of each"],
["G04","No damages or delay mechanism","{{§credits}}: the pool, the weightings, the three bands, persistent failure at {{credits.3}} and the self-reporting rule at {{credits.5}}"],
["G05","No defects or rectification regime","{{spec.13}}: the same three priorities and times as the P2 defects regime, deliberately, so a resident meets one standard and not two"],
["G06","No temporary works regime","Not applicable to an operating service. The equivalent — what the Contractor provides and maintains — is at {{spec.20}}"],
["G07","Relocation imposed without a requirement","{{demob.3}}: the data, the schedule of consumed assets, and the obligation not to make relocation harder"],
["G08","No information requirements","{{§reporting}}: the CAFM, the data ownership rule, and what is reported daily, weekly, monthly, quarterly and annually"],
["G09","No site constraints section","{{§site}}: the segregation line, induction and conduct, the allocation, and the rule that no bed here is available to the Contractor's staff"],
["G10","No electrical supply characteristics","Received from P2 Appendix 8 rather than restated. {{spec.16}} requires the metering installed under P2 4.24 to be used rather than described"],
["G11","No water supply characteristics or metering","As G10, plus {{statutory.5}}: the scheme received at IF-04, the specific stagnation risk this village creates, and consumption as an early indicator"],
["G12","No evacuation strategy","{{statutory.1}} to {{statutory.4}}: who the Responsible Person is, the fire risk assessment and its review triggers, the routine including one night drill a year, and PEEPs before a resident's first night"],
["G13","A figure that was tight for the technology","{{kpi.K10}} at 99.5% availability and {{kpi.K17}} at 99% are stated as achievable and are measured over the month rather than instantaneously — an availability figure with no measurement period is not a figure"],
["G14","No serviceability criteria","Not applicable. The equivalent — what 'available' means — is defined at {{§definitions}} and is deliberately about the person who needs the thing, not about the asset"],
["G15","No change control","{{§change}}: who may instruct, how a change is valued, and the clause that stops occupancy variation being argued as a change"],
["G16","Float ownership not stated","Not applicable. The equivalent is {{change.3}}: movement within the known demand curve gives rise to no entitlement, and that is why the pricing is split at {{pricing.2}}"],
["G17","No sustainability or social value requirement","{{§sustain}}: energy and water per bed-night against a stated baseline adjusted for occupancy and degree days, food waste, and social value that is contractual and reported quarterly"],
["G18","No testing regime for the thing that fails","{{§audit}}: the benchmark room, the monthly joint audit, unannounced audits including at night, quarterly systems audits, and the resident survey"],
["G19","Missing detail on a service nobody specifies","{{spec.19}} — quiet hours, and the finding that there are none. It is the clause a specification written for any other building type would not contain, and it governs six other services"],
["G20","No obsolescence or support period","{{reporting.1}}: the data is the Employer's, exportable on demand and at demobilisation, with no re-coding of the identifiers the village will be relocated with"],
["G21","No inspection checklist","{{audit.2}}: the benchmark room, agreed and photographed before the first service commencement, so that 'clean' stops being an opinion between two people in a doorway"],
["G22","No definitions","{{§definitions}}: twenty-one terms, including the O and I basis codes and what 'available' and 'occupied' mean"],
["G23","No ethical labour requirement","{{§labour}}, and it is the longest section of its kind in any of these packages — because cleaning, catering, laundry and security are four of the highest-risk sectors in the UK and this package is all four"],
["G24","Clauses with no measurable requirement","{{spec.1}} defines clean in six testable parts; every KPI carries a target, a method and a frequency; every response time is in hours. The weightings sum to one hundred, and the build fails if they do not"],
["G25","No security requirement","{{spec.10}} and {{spec.9}}: perimeter, patrol intervals, CCTV with the no-overlooking rule, credential control inherited from P2, and the occupancy record treated as a fire safety document"],
],
};
