// P5 — management responsibility, mobilisation, the team, statutory duties,
// residents, and the audit regime.
module.exports = {

// ---------------------------------------------- management responsibility
management: [
["1","This is an output-specified service contract, and here is what that means",
  "THIS IS THE CLAUSE THE P2 GAP REGISTER MADE FATAL BY ITS ABSENCE, translated to a service. Without it a tenderer cannot know what it is warranting, and every competent tenderer returns a qualified offer. Qualified offers cannot be compared, which defeats the evaluation.\n\nThe Employer has stated OUTCOMES and MEASURES. The Contractor designs the service that achieves them: the method, the frequency, the resource, the equipment, the rosters and the supervision. It carries the risk that its design achieves the outcome.\n\nWhere this document specifies an INPUT — a frequency, a ratio, a named standard — the Employer has decided it and the Contractor delivers it as described. The Employer carries the risk that doing it produces the outcome; the Contractor's duty is to say so, before award, where it believes it will not. A tenderer that prices an input it thinks is inadequate and says nothing has taken on a problem it could have handed back.\n\nThe matrix at {{management.3}} states which is which, element by element. The service register at {{§services}} codes every service O or I. Twenty-three services: fifteen output-specified, eight input-specified, and the eight are stated with their reasons."],
["2","The Service Delivery Plan",
  "With its tender the Contractor shall submit a Service Delivery Plan: how it will deliver each service, with what resource, on what roster, to what supervision, and how it will schedule to occupancy rather than to the clock.\n\nThe Plan is contractual on award and is subordinate to these Employer's Requirements. Where the two conflict, this document prevails, unless the conflict arises from a departure accepted in writing.\n\nIt shall contain, as a minimum: the organisation chart with named individuals for the posts at {{§team}}; the establishment by service, by shift, showing the peak-day resourcing for room turnover at {{spec.4}}; the catering service plan showing all 4 service periods including the night meal; the transport plan against the shift roster; the planned maintenance schedule; the winter service plan at {{spec.14}}; the noise-by-zone method at {{spec.19}}; and the mobilisation programme at {{§mobilisation}}.\n\nEVERY POINT AT WHICH THE PLAN DEPARTS FROM THIS DOCUMENT shall be listed in a Schedule of Departures with the clause, what is offered instead, the reason, the effect on every other requirement, and the price effect as a plus or a minus. A departure not listed is not accepted, whether or not it is visible in the Plan."],
["3","The management responsibility matrix","The matrix is exhaustive. An element not listed is the Contractor's to design. Codes: CD — the Contractor designs the method to a stated outcome. ED — the Employer has specified it; the Contractor delivers it as described. JT — agreed jointly and neither party may change it alone."],
["4","Review does not transfer responsibility",
  "The Employer will review the Service Delivery Plan, the method statements, the maintenance schedule and every submission required by this document. Comment on, acceptance of, or silence about any of them does not make the Contractor's method the Employer's, does not relieve the Contractor of any obligation, and is not a variation.\n\nThis applies to an accepted submission as fully as to a commented one. It is stated because in a service contract the Employer sees the method every day, and daily visibility is repeatedly argued afterwards to be approval."],
["5","Sub-contracting",
  "The Contractor may sub-contract, and on a village of this size it will: catering, laundry, pest control, lift maintenance, specialist water treatment and security are commonly sub-let.\n\nIt remains liable to the Employer for every sub-contracted service as if it had performed it itself. Every requirement of this document, and in particular the labour standards at {{§labour}} and the welfare obligations at {{§welfare}}, flows down in full and unamended.\n\nThe Contractor shall disclose at tender every service it intends to sub-let and to whom, where known. A sub-contractor introduced later is notified to the Employer before it attends site, with evidence that the flow-down is in place. The Employer may object to a sub-contractor on reasonable grounds relating to the requirements of this document."],
],

// [element, code, what the Employer has stated, what the Contractor is responsible for]
matrix: [
["Cleanliness standard","ED","The measurable standard at {{spec.1}} and the benchmark room","Achieving it, and the method, frequency and resource that does"],
["Housekeeping frequency and rostering","CD","The outcome, and that scheduling is by occupancy state","The schedule, the establishment and the supervision"],
["Entry to occupied rooms","ED","The rule, the log and the do-not-disturb regime","Compliance, training and the auditable log"],
["Linen cycle","ED","7 days maximum, and on demand after soiling","Stock, laundering standard, storage and segregation"],
["Personal laundry provision","CD","The waiting-time outcome at the busiest hour","Machine count, siting, maintenance and the sizing assumption"],
["Catering service periods","ED","Four periods including the night meal, and the queueing limit","Menu, production, servery configuration, staffing and throughput"],
["Menu and nutrition","CD","A 28-day minimum cycle and nutritional adequacy","The menu, the analysis and the resident satisfaction it produces"],
["Dietary and religious requirements","ED","That they are met at every service without being asked again","Recording, carrying and delivering them"],
["Reception staffing","ED","Continuous","The establishment and the roster that delivers it"],
["Occupancy record","ED","Its content, its accuracy and that it is a fire safety document","Maintaining it, and its accuracy at unannounced roll call"],
["Key and credential control","ED","The hierarchy inherited from P2 and the override arrangement","Issue, return, deactivation and the log"],
["Security patrols and CCTV","CD","The outcome, the retention period and the no-overlooking rule","Patrol regime, staffing, camera siting and monitoring"],
["Transport timings","ED","Arrival 15 minutes before shift start; return within 30 minutes of shift end","Fleet, drivers, routes, capacity and compliance"],
["Planned maintenance","ED","SFG20 or the manufacturer's requirement, whichever is more onerous","The schedule, the trades, the records and the CAFM"],
["Reactive priorities and times","ED","The three priorities and their times at {{spec.13}}","Meeting them, and the resource that does"],
["Winter service","CD","That routes are passable before the first movement of the day","Trigger, routes, material, reaction time and the decision-maker"],
["Waste diversion","ED","70% minimum, reported monthly","Segregation, storage, contracts and the duty of care records"],
["Energy management","CD","That consumption is managed from the metered data, not merely paid","Analysis, action, and proposals under change control"],
["Network availability","ED","The coverage and density from P2 section 6, and no charging or throttling","The service, its monitoring and its restoration"],
["Pest control regime","CD","A proactive documented regime and the reporting triggers","Contractor selection, frequency, proofing and records"],
["Noise management","JT","That there is no quiet hour and it is managed by zone and shift","The method statement; the alarm test time is agreed and then held"],
["Fire risk assessment","ED","That the Contractor is the Responsible Person for the village in occupation","The assessment, its review, and everything that follows from it"],
["Fire routine and drills","ED","Weekly test, monthly emergency lighting, quarterly drill, one night drill a year","Doing them, recording them and acting on what they show"],
["PEEPs","ED","That one exists before a resident's first night","Identifying who needs one, writing it, and rehearsing it"],
["Water safety scheme","ED","The scheme received from P2, and that the duty passes at handover","Operating it, recording it, and reviewing it as occupancy changes"],
["Food safety system","ED","HACCP, registration, allergen information at the point of service","The system, the records, the training and the outcome"],
["Welfare provision","ED","That the service exists, is reachable at any hour, and notices absence","Its design, its staffing and its escalation"],
["Management team","ED","The posts, the cover and that they are named individuals","Recruiting, retaining and replacing them under {{team.3}}"],
["Labour standards","ED","The Employer Pays Principle and the flow-down at {{§labour}}","Compliance across its own staff and every sub-contractor"],
["CAFM system","CD","That it holds the asset register in the schema received from P2","Selection, configuration, licensing and the data in it"],
],

// ------------------------------------------------------------ mobilisation
mobilisation: [
["1","Mobilisation runs against the sectional completion dates, not against one",
  "The village opens in four sections — 65 beds by the end of month 3, 150 by month 6, 205 by month 9 and 225 by month 12, per Appendix 6 of the P2 requirements. This package mobilises four times, and the first is the hardest because nothing is established.\n\nThe Contractor shall submit a mobilisation programme within 2 weeks of award showing, per section: recruitment and training, the CAFM loaded from the P2 asset register, the fire risk assessment completed, the water safety duty accepted at IF-04, the food safety registration obtained, the transport contracted, and the Service Delivery Plan turned into rosters with names in them.\n\nSERVICE COMMENCEMENT for a section is the date the first resident may arrive. It is not achieved until the items at {{mobilisation.2}} are complete, and the Employer certifies it."],
["2","What must be true before the first resident arrives",
  "Every one of these, for the section concerned, evidenced and certified:\n\nThe fire risk assessment is complete, the Responsible Person is appointed in writing, the fire logbook is open, the alarm has been tested and the first drill is programmed.\n\nThe water safety scheme has transferred at IF-04, the flushing log is continuous from P2's first fill, and the temperature regime at {{kpi.K11}} has been sampled once with results recorded.\n\nThe kitchen is registered with the local authority, the HACCP system is documented, and the food safety management team is in post — a kitchen cannot serve a first meal on a promise of registration.\n\nThe occupancy record is live, the credential hierarchy is configured, and reception is staffed for the arrival window.\n\nThe CAFM holds the asset register received under IF-02, reconciled against physical labels on a sample of not less than 10% of assets.\n\nThe welfare contact at {{welfare.2}} exists, is staffed and is published in the induction.\n\nTransport is contracted and has run the route once against the actual shift times.\n\nThe Village Manager and the deputy are on site and have completed the P2 training at IF-05.\n\nA section that opens without all of these opens on a promise, and the promise is tested by the first person who needs the thing that is missing — usually at three in the morning."],
["3","Parallel running and the first fortnight",
  "For the first 14 days of each section's occupation the Contractor shall provide a daily written report to the Employer covering: arrivals against the record, faults raised and closed, meals served against expected covers, transport departures against schedule, and every incident.\n\nDaily, not weekly. The first fortnight is when the assumptions in the Service Delivery Plan meet the actual shift pattern, and it is the only period in which correcting them is cheap."],
],

// ------------------------------------------------------------- the team
team: [
["1","The Employer is buying named people",
  "A facilities management tender is won on a management structure and delivered by the people in it. This section states the posts, the cover and the standard, and the Contractor names the individuals in its Service Delivery Plan.\n\nA tender that offers a structure without names, or that names people it has not yet recruited, shall say so plainly. The Employer would rather know at tender than discover at mobilisation."],
["2","The posts","The establishment below is a minimum and is an input. The Contractor may exceed it and shall state where its Service Delivery Plan does."],
["3","Continuity, and what happens when someone leaves",
  "The Village Manager and the Deputy shall not be changed within the first 6 months of service commencement, nor within 3 months of any section's commencement, except through death, illness, resignation or the Employer's own request.\n\nWhere a key post-holder leaves, the Contractor shall notify the Employer within 2 working days, propose a replacement within ten, and provide a handover of not less than 2 weeks where the departure allows it. The Employer may interview and may reasonably object.\n\nA post left vacant for more than 4 weeks is a service failure under {{§credits}}, because on a village the management post IS the service: there is no head office that can absorb its absence at three in the morning."],
["4","Vetting, competence and training",
  "Every person working on this package shall be vetted to a standard appropriate to their role and disclosed at tender. As a minimum: identity and right to work checked and recorded for every person; enhanced checks for anyone with routine unsupervised access to occupied rooms; and a DBS check at the appropriate level for anyone whose role brings them into a welfare or safeguarding capacity under {{§welfare}}.\n\nEvery person completes the project induction and the village-specific module before first entry, per {{§site}}.\n\nThe Contractor shall maintain a training matrix showing, per person: induction, fire, first aid, food hygiene where applicable, manual handling, lone working, safeguarding awareness, and the escalation procedure. It shall be auditable and it shall be audited under {{§audit}}."],
],

// [post, cover required, minimum competence]
posts: [
["Village Manager","On site, full time, with a named deputy providing cover for absence","Experience managing a residential facility of comparable size; IWFM Level 4 or equivalent"],
["Deputy Village Manager","On site, full time, covering the Manager","As above at Level 3, or demonstrable equivalent experience"],
["Duty Manager","Continuous — a Duty Manager on site or immediately contactable and able to attend within 30 minutes, 24 hours a day","Authority to commit resource and to invoke the escalation at {{§escalation}} without seeking permission"],
["Head of Catering","Full time","Level 4 food safety; experience of continuous multi-service-period catering, not of a single-sitting restaurant"],
["Housekeeping Supervisor","Full time, with supervision present across every shift on which housekeeping works","Level 3 or equivalent; trained in the entry and dignity rules at {{spec.3}}"],
["Maintenance Supervisor","Full time, with a competent person on call continuously for Priority 1","Relevant trade qualification; competence for the water safety tasks at {{statutory.5}} or a named specialist under contract"],
["Health, Safety and Fire lead","Not less than 0.5 FTE dedicated to this village","NEBOSH General Certificate or equivalent, plus demonstrable competence in fire safety in sleeping accommodation"],
["Welfare and Resident Liaison","Not less than 1.0 FTE, with contactable cover at every hour","Trained in mental health first aid and safeguarding awareness. NOT a reception role with welfare added to it"],
["Reception","Continuous, staffed","Trained on the occupancy record, the credential system and the escalation procedure"],
],

// ----------------------------------------------------------- statutory
statutory: [
["1","Who the Responsible Person is",
  "THE CONTRACTOR IS THE RESPONSIBLE PERSON for the accommodation village in occupation, for the purposes of the Regulatory Reform (Fire Safety) Order 2005, from each section's service commencement until its demobilisation.\n\nIt is stated in these terms because it is a legal duty carrying criminal liability, and because on a project of this shape it is routinely assumed to sit with somebody else — the Employer, the Principal Contractor, or the party that built the blocks. It does not. The person with control of the premises in occupation is the Contractor and the duty follows control.\n\nThe Contractor shall appoint a named individual to discharge the duty, notify the appointment to the Employer in writing before service commencement, and notify any change within 2 working days. The appointment is not to a job title; it is to a person.\n\nNOTHING IN THIS CLAUSE MAKES THE CONTRACTOR PRINCIPAL CONTRACTOR UNDER CDM 2015. Operating an occupied village is not construction work. Where a relocation, refurbishment or works package later brings construction within this Contractor's scope, the CDM position is decided, priced and appointed separately under IF-14."],
["2","The fire risk assessment",
  "A suitable and sufficient fire risk assessment for every occupied part of the village, completed before first occupation of each section, written to the fire strategy received at IF-11, and identifying in writing any respect in which the two conflict.\n\nReviewed at intervals not exceeding 12 months AND after any of: a change to the block layout or its occupancy; a change to the shift pattern that alters who is asleep when; a fire, a near miss or an unwanted alarm pattern; a change to the adjoining construction site that affects access, egress or the assembly point; and any material change to the resident population, including a resident requiring a PEEP where none was previously required.\n\nThe assessment shall address the conditions that make this village unlike other sleeping accommodation: residents asleep at every hour, a multilingual population, a live construction site adjoining, and blocks that stand partly occupied against the demand curve."],
["3","The fire routine",
  "WEEKLY. Alarm test from a different call point each week, at the time agreed under {{spec.19}} and held. Recorded in the fire logbook.\n\nMONTHLY. Emergency lighting function test. Quarterly and annual duration tests per BS 5266-1. Every result recorded, and a failed luminaire raised as Priority 2 under {{spec.13}}.\n\nQUARTERLY. Evacuation drill, per block, covering the residents actually present. NOT LESS THAN ONE DRILL PER YEAR SHALL BE AT NIGHT, because the evacuation that has to work is the one at three in the morning with people asleep, and a village that has only ever drilled at two in the afternoon has not tested its strategy.\n\nCONTINUOUS. The alarm and detection system maintained per BS 5839-1 by a competent contractor; the cause and effect matrix received from P2 held and re-verified after any change; and the unwanted alarm rate tracked against the target at P2 clause 4.26 and reported monthly. An unwanted alarm at four in the morning wakes a hundred people who then work a twelve-hour shift; the target is a safety requirement, not a convenience.\n\nThe means of escape shall be kept clear. Storage in a corridor, a wedged fire door or a blocked final exit is an Unacceptable Failure under {{credits.4}}, not a housekeeping observation."],
["4","Personal emergency evacuation plans",
  "A PEEP shall exist for every resident who cannot evacuate unaided, before their first night in the village. Not the next working day, not before the next drill.\n\nThe twelve RT-02 accessible rooms are the obvious case and they are not the only one: a temporary injury, a medication effect, a hearing impairment or a language barrier can all mean a resident does not evacuate unaided, and the P2 rooms provide a visual alarm device and a vibrating pad interface in RT-02 for that reason.\n\nEvery PEEP names the assisting person, states where they are at every hour the resident is present, and is rehearsed — a plan naming a person who works days for a resident who sleeps days is not a plan.\n\nThe PEEP register is reconciled to the occupancy record at every audit under {{kpi.K14}}."],
["5","Water safety",
  "The written scheme of control received from P2 at IF-04 shall be operated, recorded and reviewed. THE DUTY PASSES AT HANDOVER and the log is continuous across the transfer — a gap in the record at the handover date is the gap an investigation would find first.\n\nThe Contractor shall appoint a competent Responsible Person for water safety, hold a current risk assessment to HSG274 Part 2 and ACOP L8, and maintain: monthly temperature monitoring on a rotating sample so that every outlet is tested twice a year; weekly flushing of every outlet in an unoccupied room; TMV servicing at the manufacturer's interval across all 450 valves; calorifier and storage inspections; and the actions arising from each.\n\nTHE SPECIFIC RISK ON THIS VILLAGE is stated so it is designed for rather than discovered. Blocks complete against a demand curve and stand partly occupied for months. Rooms are vacated at rotation change and stand empty for a week at a time, every fortnight, for 38 months. Both create stagnant legs in a system designed for continuous use. The flushing regime shall be driven by the occupancy record at {{spec.9}}, not by a fixed list of rooms, and an unexpected fall in a block's water consumption under {{spec.16}} shall be investigated as a water safety matter within 48 hours."],
["6","Food safety",
  "Registration with the local authority as a food business before the first meal is served, and a documented HACCP system operated and recorded.\n\nAllergen information available at the point of service for every item, to the Food Information Regulations and to the requirements for food prepacked for direct sale. A resident with an allergy on a fourteen-day rotation eats forty-two meals here; the information has to be right every time.\n\nTemperature, cleaning, traceability and training records complete and auditable. Food Hygiene Rating obtained and maintained at not less than 5. A rating below 5 is reported to the Employer within 24 hours with the improvement plan.\n\nAN OUTBREAK IS NOT CONFINED TO THIS PACKAGE. Two hundred and twenty-five people eat here and then work on a construction site. A foodborne outbreak removes a proportion of the project's workforce for several days and is a project event, not a catering incident. Any suspected outbreak — two or more residents with similar symptoms within 48 hours — is reported to the Employer and to the local authority immediately, and is an Unacceptable Failure under {{credits.4}}."],
["7","Health and safety, and the incidents that will happen",
  "The Contractor shall operate a health and safety management system covering its own workforce and the residents so far as they are affected by its undertaking, and shall comply with the site rules at {{§site}}.\n\nFirst aid provision available at every hour, with an automated external defibrillator on site, maintained, and its location published in the induction. Over 38 months with two hundred and twenty-five residents, a cardiac event is not a remote possibility.\n\nRIDDOR reporting where required, with the Employer notified of any reportable event within 2 hours and any fatality immediately.\n\nLone working, night working and violence at work assessed and controlled for the Contractor's own staff — a receptionist alone at four in the morning is a lone worker."],
],

// ----------------------------------------------------- residents / welfare
welfare: [
["1","Why this section exists",
  "Most facilities management specifications do not have a section like this, and on a workers' village that omission is the most serious one available.\n\nA resident here is not a customer. They cannot choose a different provider and they cannot go home at the end of the day. They are living, for weeks at a time, in a single room on a site next to the job, often a long way from their family, working twelve-hour shifts, and sometimes not speaking English as a first language. Over 38 months, some of them will be in trouble: illness, injury, bereavement, money, drink, a marriage ending five hundred miles away, or simply the accumulated weight of it.\n\nThe Employer is not asking the Contractor to be a health service. It is requiring that there is somewhere to go, that somebody notices, and that when something serious happens there is a procedure rather than an improvisation."],
["2","The welfare contact",
  "A welfare and resident liaison function, staffed at not less than 1.0 FTE with contactable cover at every hour, distinct from reception. It is not a reception duty with welfare added to it: a resident will not raise a personal matter at a desk where the next person is waiting to collect a key.\n\nIt shall be reachable in person during stated hours, and by phone or message at any hour. It shall be published at induction, in every block, and in the languages of the resident population.\n\nIt shall be able to: arrange a GP or dental appointment and the transport to it; arrange contact with an employer's HR or an occupational health service; provide information about local services in the resident's own language; arrange a private space and time for a call home; escalate a safeguarding concern under {{welfare.5}}; and raise a maintenance or catering matter on a resident's behalf where the resident would rather not.\n\nThe Contractor shall record contacts by category and number, without identifying individuals, and report them monthly under {{§reporting}}. The Employer wants to know whether the service is used, not who used it."],
["3","Noticing when somebody stops appearing",
  "THIS IS THE CLAUSE THAT MATTERS MOST AND IT IS THE ONE THAT IS NEVER WRITTEN.\n\nA resident who does not appear is the earliest indication of something serious, and in a village of two hundred and twenty-five people on rotating shifts, not appearing is invisible unless somebody is looking.\n\nThe Contractor shall operate a documented procedure that triggers when any of the following is observed: a room showing do-not-disturb for more than 24 hours; a resident who has not collected a meal or a packed provision for two consecutive service periods they were expected at; a room not entered by housekeeping for 3 days against the schedule; a resident reported absent from shift by the Employer under IF-13; or any concern raised by another resident.\n\nOn a trigger: a welfare check by a named person, within 4 hours during the day and within 8 hours at night. If there is no response and the room shows occupied, entry under the emergency provision at {{spec.3}}, with a second person present, and the entry logged.\n\nThe Employer is notified of every welfare check performed, monthly and in numbers only, and immediately where the check finds a person who needs help.\n\nA village that does not have this procedure finds people late. That is the whole of the reason for the clause."],
["4","Serious incident, and death in service",
  "The Employer states plainly what a thirty-eight-month deployment of two hundred and twenty-five people means: it is statistically likely that a resident will die during the term, on site or in their room, of natural causes or otherwise. A procedure written afterwards is written badly.\n\nThe Contractor shall hold, from service commencement, a documented serious incident procedure covering: immediate response and preservation of the scene; notification to the emergency services, the Employer and the resident's employer; the coroner's and police interface; securing the room and the resident's property; support for the residents who found or knew them, including access to counselling; communication to the village, agreed with the Employer before it is issued; and the return of personal effects to the family.\n\nIt shall name who does each of those things at three in the morning on a Sunday.\n\nThe Employer will not judge this procedure by its length. It will judge it by whether the people named in it are on site."],
["5","Safeguarding, dignity and harassment",
  "The village accommodates adults, some of whom will be vulnerable at some point during their stay. The Contractor shall hold a safeguarding policy covering vulnerable adults, with a named lead, a reporting route to the local authority safeguarding team, and awareness training for every member of staff with resident contact.\n\nHarassment, bullying, discrimination or violence between residents, or between staff and residents, shall be reported to the Employer within 24 hours and to the police where a criminal offence may have occurred. The Contractor shall not resolve such a matter informally and treat it as closed.\n\nDIGNITY. The rules at {{spec.3}} on entering a room are part of this. So is the expectation that staff address residents by name, that a complaint is answered, and that a resident is not made to feel like a unit of occupancy. The Employer will test this through the resident survey at {{audit.4}} and will act on what it says."],
["6","Alcohol, drugs, and the difference between a rule and a response",
  "The site rules at {{§site}} prohibit attending work under the influence and provide for testing. That is a safety rule and it is not softened here.\n\nThis clause covers what happens in the village rather than on the site. Alcohol is permitted in the village within limits the Employer will state in the village rules, and the Contractor shall enforce them. A resident who is drunk and disruptive is a discipline matter for their employer and the Contractor shall report it.\n\nA RESIDENT WHOSE DRINKING IS A PATTERN IS A WELFARE MATTER, not only a discipline one. The Contractor's staff shall be trained to recognise the difference and the welfare route at {{welfare.2}} shall be offered before the disciplinary route is invoked, save where there is an immediate safety risk. Removing a person from the village without offering help is the cheap answer and it is not the one the Employer is buying."],
],

// -------------------------------------------------------------- the audit
audit: [
["1","How performance is established",
  "By measurement against the key performance indicators at {{§kpis}}, by audit, and by asking the residents. The three are used together because each catches what the others miss: measurement catches what is counted, audit catches what is done when nobody is counting, and the residents catch what neither instrument was pointed at."],
["2","The benchmark room",
  "Before the first section's service commencement the Contractor and the Employer shall jointly agree a benchmark room, cleaned and presented to the standard the Contractor intends to deliver against {{spec.1}}, and shall photograph it.\n\nThe photographs are the standard. Every subsequent housekeeping audit is against them, and 'clean' stops being a matter of opinion between two people standing in a doorway. The benchmark is re-agreed if the standard is ever formally changed, and not otherwise."],
["3","The audit regime",
  "MONTHLY, JOINT. A sample of not less than 10% of occupied rooms, drawn at random by the Employer and not offered by the Contractor, audited against the benchmark. Scored, recorded, and feeding {{kpi.K02}}.\n\nMONTHLY, UNANNOUNCED. The Employer may audit any service at any time without notice, including at night. An audit regime that only ever runs at eleven on a Tuesday measures a service that only has to work at eleven on a Tuesday.\n\nQUARTERLY, SYSTEMS. The fire logbook, the water safety records, the food safety records, the CAFM, the training matrix, the PEEP register and the labour standards evidence at {{§labour}}. Documentary, and failures here are treated as seriously as physical ones because they are the record that everything else was done.\n\nANNUALLY, INDEPENDENT. The Employer may commission an independent audit of fire safety, water safety or food safety, at its own cost, and the Contractor shall give access to everything it asks for."],
["4","Asking the residents",
  "An anonymous survey of not less than 25% of residents, quarterly, covering accommodation, cleanliness, catering, transport, connectivity, security, welfare and dignity.\n\nRun by the Contractor, with the questions agreed with the Employer and not changed between rounds without agreement, and the raw results — not a summary — provided to the Employer. Available in the languages of the resident population.\n\nThe Contractor shall publish to residents what the survey said and what it is doing about it. A survey whose results are never mentioned again teaches residents not to answer the next one, and then the Employer has lost its best instrument."],
],
};
